### ISSUE TITLE
IE11: ng test with differential loading: syntax error when fast-check is used

### ISSUE THREAD

**Issue by delexi** [dubzzz/fast-check#1053]
## 🐛 Bug Report
If fast-check is added to a spec in a fresh Angular 9.1.12 project with differential loading turned on, Karma will report a syntax error in IE11. Upon investigation it seems, that a "class" keyword lands in the vendor.js bundle served by angular:
```javascript
class ArrayArbitrary extends _definition_Arbitrary_js__WEBPACK_IMPORTED_MODULE_2__["Arbitrary"] {
//... it looks like further definitions from fast-check follow this line.
```

## To Reproduce

See example repo: https://github.com/delexi/ng-test-fast-check-ie11

Steps to reproduce:
- Create an Angular 9 project: `npx @angular/cli@9.1.12 new fast-check-ie` (or use example repo)
- Enable differential loading and install fast-check and IE support for karma (or use example repo)
- Add a simple fast-check test (or use example repo)
- In project root run `ng test --configuration=es5`
- If you are quick to press F12 after IE starts up you can capture the syntax error in IE's Console and navigate from there to the correct location in vendor.js mentioned above. Otherwise karma's console output should mention the syntax error as well.

## Expected behavior

I expect that adding fast-check to my angular tests does not break them in IE11.

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            |     2.4.0       |
| node                  |      12.8.2      |
| TypeScript           |        3.8.3    |

**Comment by dubzzz** [comment]
Thanks a lot for report. I'll investigate it and let you know as soon as I get some news or need some more details.

For the moment, you may try to switch (temporarily) to fast-check 1.x, this version is compatible with legacy versions of JavaScript and should work without any need to transpile it.

**Comment by delexi** [comment]
I tried this with version 1.2.6 of fast-check in the example repository. That works as a quick fix for now. I will see next week whether this means rewriting to much stuff because of possible changes in fast-check's API.

**Comment by dubzzz** [comment]
You should give a try to 1.26.0. It should not be far from the latest 2.x version.

Meanwhile, I'm going to investigate how we could fix this issue. Normally, class should have been transpiled by the bundler as you used `--es5` 🤔

**Comment by delexi** [comment]
> You should give a try to 1.26.0. It should not be far from the latest 2.x version.

That is actually the version I was trying to use. Apparently I failed to correctly transfer it from the place I looked it up🤦 I used the correct version now and IE is happy.

API-wise this version seems to not have changed in a way that impacts me. So this is a nice workaround!

**Comment by dubzzz** [comment]
No worry, I'll have a look to your issue more precisely and try to come with a better and more sustainable fix.

**Comment by dubzzz** [comment]
It looks as if `ng test --configuration=es5` was not able to transpile the code provided by `node_modules` to make it compatible with the target browser (at least in tests). I'm wondering if ng-cli provide an additional flag to enforce that 🤔

**Comment by delexi** [comment]
I did another round of googling and came upon this comment: https://github.com/angular/angular-cli/issues/9339#issuecomment-359965689, where they say:
>[...] Since we do not transpile .js files, that code is included as is in your build output. You should transpile ella-utils to compatible JavaScript.

This sounds to me, like the angular cli does not support transpiling dependencies (at least .js dependencies). Does the current fast-check package only contain files that are not transpiled to es5?

**Comment by dubzzz** [comment]
Latest version of fast-check is bundled for es2017. No more es5 (it created performance issues (+30%) and costly to maintain)

**Comment by delexi** [comment]
OK, fair enough :) I think we can go ahead and close this. For anyone coming here in the future: I read somewhere that running babel on the vendor.js output by the angular-cli with some kind of post build step would be a solution.

**Comment by dubzzz** [comment]
Please let me know if you have a nice trick to do that. I'd be really interested about a potential fix that can be applied for any Angular users wanting to support IE11 and use fast-check to test that.

**Comment by delexi** [comment]
Actually, the workaround I was talking about happens to be in the thread I already mentioned. The this and the following comment: https://github.com/angular/angular-cli/issues/9339#issuecomment-360213460. I haven't actually tried these though.
