### ISSUE TITLE
Integer max depending on other arbitrary in `chain` not respected

### ISSUE THREAD

**Issue by jeysal** [dubzzz/fast-check#1081]
## 🐛 Bug Report

Integer max depending on other arbitrary in `chain` not respected.

Maybe I'm misunderstanding how `chain` is supposed to work, but at least this seems incorrect to me.

## To Reproduce

Steps to reproduce:

https://runkit.com/5f90266b82ff2f001ab5dbf8/5f90266bf9995f001aa57401

```js
const fc = require('fast-check')

const int = fc.integer(1, Number.MAX_SAFE_INTEGER)
const smaller = int.chain(i => fc.integer(0, i - 1))
fc.assert(
  fc.property(
    int,
    smaller,
    (i, s) => s < i
  )
)
```

## Expected behavior

Property assertion succeeds, because `smaller` has a `max` bound of 1 less than `int`.

## Actual behavior

Property assertion fails, e.g. with counterexample [1,1], which I thought was not possible according to the definition of the arbitraries.

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            | 2.5.0      |
| node                  | 14.14.0    |

**Comment by jeysal** [comment]
`noBias` and `noShrink` do not seem to solve it.

**Comment by dubzzz** [comment]
@jeysal Thanks for the report. Actually the behaviour is expected. The arbitraries/generators you pass as parameters of a `fc.property` are considered independently so an integer value will be pulled from `int` to build `i`, then another one will be pulled from `int` and then pass through `chain` to build `smaller`.

Here are possible fixes for that:
`fc.integer(1, Number.MAX_SAFE_INTEGER).chain(i => fc.tuple(fc.integer(0, i - 1), fc.constant(i)))`

Or better (shrinker will work better - chain makes shrinking difficult):
`fc.tuple(fc.integer(0, Number.MAX_SAFE_INTEGER), fc.integer(0, Number.MAX_SAFE_INTEGER)).map(([a,b]) => a < b ? [a,b] : [b,a])`

Then you can use it as follow:
`fc.assert(fc.property(myArb, ([smaller, int]) => { /**/ }))`

**Comment by dubzzz** [comment]
Live example: https://runkit.com/dubzzz/5f902a02ced557001a1a96d6

**Comment by jeysal** [comment]
Thanks for the response!
I already had a version working with tuples (similar to your second suggestion, except using `filter`), but was still wondering why `chain` did not work that way.

I assume a version of `chain` that works the way I expected it to would require a lot of changes to internals because fast-check operates very differently at the moment and thus be unrealistic to be implemented? It seems _theoretically_ possible by building a DAG of arbitraries, but probably much more difficult to implement.

**Comment by jeysal** [comment]
(closing already because definitely not a bug, and chain that works the way I expected would be useful, but probably hard to implement)
