### ISSUE TITLE
Attempts to constrain two Arbitrary dates to a particular range aren't working.

### ISSUE THREAD

**Issue by SirensOfTitan** [dubzzz/fast-check#1109]
## 🐛 Bug Report

Attempts to constrain two dates to a particular range: e.g. a start date is before an end date always produces some invalid cases.

## To Reproduce

Steps to reproduce:
I've tried defining a date range in the following ways:
```typescript
  // Using a tuple then a filter to enforce the difference.
  const dateRange = fc.tuple(fc.date(), fc.date())
    .filter(([start, end]) => start <= end);

  // Using a chain approach
  const startTime = fc.date();
  const endTime = startTime.chain((s) => fc.date({ min: s }));
  // I've also tried combining the filter just for fun:
  const endTime = startTime.chain((s) => fc.date().filter((e) => s <= e);
```
During runs, I constantly get a handful of cases that fail these conditions, e.g.
` startDate=+059806-01-27T18:19:45.536Z endDate=1970-01-01T00:00:00.015Z startDate<=endDate=false`

I'm not sure if I'm using arbitrary wrong or what, but I'm feeding the arbitrary that generates this piece straight into an fc.assert/fc.property test.

## Expected behavior
I expect `startDate` to be less than or equal to `endDate` in the usage above.

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            |     2.6.0       |
| node                  |     14.7.0       |
| TypeScript*           |    4.0.5        |

**Comment by dubzzz** [comment]
The issue looks similar to #1081 🤔

Is it the same issue?

**Comment by dubzzz** [comment]
The tuple-based approach should work fine in theory.

Regarding the chain-based approach your chain need to return the two dates (min and max together). When calling property, values coming from the arbitraries are extracted independently. See #1081 regarding this topic.

**Comment by dubzzz** [comment]
Any updates?

**Comment by dubzzz** [comment]
Closing the issue as there is no update. Was not able to reproduce so far, more details on needed
