### ISSUE TITLE
fc.func produces different results depending on usage?

### ISSUE THREAD

**Issue by julamb** [dubzzz/fast-check#1110]
## 💬 Question and Help

Hi,

Thanks for a great library.

I spent a few hours raging on debugging failing tests involving pure functions, and was finally able to identify the culprit. It appears than using it by name or within an arrow function changes the returned values.

Here is a test that shows the issue:

```
describe('Array map function', () => {
    it('should return a new array containing the results of calling the mapper function on every item of the array', () =>
        fc.assert(
            fc.property(
                fc.array(fc.anything()),
                fc.func(fc.anything()),
                (values, mapper) => {
                    expect(values.map(mapper)).toEqual(values.map(v => mapper(v)))
                }
            )
        ))
})
```

See it fail on livesandbox: https://codesandbox.io/s/nifty-lamport-g2hml?file=/pure-functions/main.spec.ts

I guess that calling it one way or another changes the _this_ context of the function and thus produces different results? I'm not sure if this is a bug or not, but I could not find anything about this in the doc.

**Comment by dubzzz** [comment]
Actually the issue if that `values.map(mapper)` is not equivalent to `values.map(v => mapper(v))`. So the issue is expected.

Calling `values.map(mapper)` is equivalent to `values.map((current, index, array) => mapper(current, index, array))`.

**Comment by julamb** [comment]
Right, that makes perfect sense! Thanks :)

**Comment by dubzzz** [comment]
I was thinking about adding something like `fc.funcN(arb)` so that users can specify how many parameters they want to take as input

**Comment by julamb** [comment]
Nice, that would be handy for type of usage!
