### ISSUE TITLE
A quirk of `fc.func()`

### ISSUE THREAD

**Issue by nth-commit** [dubzzz/fast-check#1111]
## 🐛 Bug Report

I notice in the implementation of `fc.func` it has a finitely-sized an array of potential outputs, and then randomly picks one of those values depending on the hash of the inputs. This means it's extremely possible to generate a function a single return value, despite accepting infinite inputs. This caused some issues for me.

## To Reproduce

Imagine a function like this:

```typescript
const whileLike = (predicate: (i: number) => boolean): void => {
  for (let i = 0; i < Number.MAX_VALUE; i++) {
    if (predicate(i)) {
      break;
    }
    // do something
  }
};
```

If we wanted to test this function, we might do something like this:

```typescript
fc.property(fc.func(fc.boolean()), predicate => {
  whileLike(predicate);
  // test something
});
```

It's likely to generate a function that **only** returns false. Which causes it to spin forever.

## Expected behavior

Given virtually infinite inputs, I would expect this function to eventually return (even it takes a long time). If I added a `noBias`, I would expect it to eventually return in pretty reasonable time (because it would equally pick from true or false).
## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            |            |
| node                  |            |
| TypeScript*           |            |

*Only for TypeScript's users

**Comment by dubzzz** [comment]
Thanks for the report.

Actually it is not really a bug but more a missing feature. Why? When you ask fast-check to generate `fc.func(fc.boolean())` it means any function returning boolean values is considered valid. So `() => false` is a valid one.

For the moment there is no built-in way to do what you are looking for.

You should be able to create one by using `fc.infiniteStream` for instance. One of the issue you'll have is that the output will be dependent on the call order.

Something like:
```
const func = arb => fc.infiniteStream(arb)
.map(s => {
  const d = new Map();
  return (...args) => {
    const ins = JSON.stringify(args);
    if (d.has(ins)) return d.get(ins);
    const v = s.next();
    d.set(ins, v);
    return v;
  };
});
```
