### ISSUE TITLE
Typing improvement for `letrec` combinator

### ISSUE THREAD

**Issue by qlonik** [dubzzz/fast-check#1164]
## 🚀 Feature Request

Improve typing of `tie` function in `letrec` combinator by expanding the type signature with the following, allowing it to read from the generic `T`.

```typescript
tie: {
    <K extends keyof T>(key: K): Arbitrary<T[K]>;
    (key: string): Arbitrary<unknown>;
}

// so the full signature becomes:
export declare function letrec<T>(
  builder: (tie: {
    <K extends keyof T>(key: K): Arbitrary<T[K]>;
    (key: string): Arbitrary<unknown>;
  }) => { [K in keyof T]: Arbitrary<T[K]> },
): { [K in keyof T]: Arbitrary<T[K]> };
```

## Motivation

The way how `tie` function of `letrec` combinator is typed means that we have to explicitly cast result of each call to that function. This way it is only needed to specify all return types of all arbitraries in `T`.

## Example

For example, reusing letrec tree from docs. 

```typescript
import * as fc from 'fast-check';

const fst = fc.letrec((tie) => ({
  tree: fc.oneof(tie('node'), tie('leaf'), tie('leaf')),
  node: fc.record({
    left: tie('tree'),
    right: tie('tree'),
  }),
  leaf: fc.nat(),
}));

type Tree = number | { left: Tree; right: Tree };
const snd = fc.letrec<{
  tree: Tree;
  node: { left: Tree; right: Tree };
  leaf: number;
}>((tie) => ({
  tree: fc.oneof(tie('node'), tie('leaf'), tie('leaf')),
  node: fc.record({
    left: tie('tree'),
    right: tie('tree'),
  }),
  leaf: fc.nat(),
}));
```

In the first example, without explicit type specification, it all still defaults to unknown. However, in the second example with explicit type specification, everything becomes well typed.

**Comment by dubzzz** [comment]
Hello @qlonik 

Really good point!

Typings for `letrec` are indeed a bit annoying today.
Your suggestion seems pretty cool actually.

I am still wondering if we could not go a step even further and inferring the type automatically (at least with latest TS versions).
I have not taken time to dig that question.

**Comment by qlonik** [comment]
I haven't played a lot with TS4.0 and TS4.1, so I don't know if the situation with recursive function has been improved. But usually, typescript cannot infer return type of even simple recursive function:

```typescript
// TS7023: 'fib' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
function fib(n: number) {
  return n === 0 || n === 1 ? 1 : fib(n - 1) + fib(n - 2)
}

// TS7023: 'fact' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
function fact(n: number) {
  return n === 0 || n === 1 ? 1 : n * fact(n - 1)
}
```

So, usually it has to be typed explicitly, and I'm not sure if it is going to be possible to infer return type of recursive call automatically at all. Maybe someone already figured out a clever way of inferring it completely automatically, however, I have not seen such a method.

**Comment by dubzzz** [comment]
@qlonik Sorry for the delay. I really think the change you suggested might be super useful. Please feel free to open a PR for it, it will be more than welcome 🎉

**Comment by dubzzz** [comment]
See comment on #1572, but I may have found a way to make it real for v3 🤞

**Comment by dubzzz** [comment]
Released in v3! Once again thanks a lot for the help on those typings
