### ISSUE TITLE
Add function constantFrom<T>(values: T[]): Arbitrary<T>

### ISSUE THREAD

**Issue by benny-medflyt** [dubzzz/fast-check#122]
It would be nice for the cases where we already have an array of constant values to add a function like:

```ts
function constantFrom<T>(values: T[]): Arbitrary<T>
```

**Comment by dubzzz** [comment]
For this kind of usage you should use:
`fc.constantFrom(v0, v1...)`

Given an array of values you might do:
`fc.constantFrom(...allMyValues)`

It expects values and not an array of values but it basically works as the syntax you suggested. Maybe one problem is that it forced you to specify at least one value. 

More at https://dubzzz.github.io/fast-check/index.html#constantfrom

Did you tried the helper above? If so, what were the pain points you experienced?

**Comment by benny-medflyt** [comment]
That doesn't work for me:

```ts
import * as fc from "fast-check";

const foos: number[] = [1, 2, 3];

export const arbFoo = fc.constantFrom(...foos);
```

I get:

    [ts] Expected at least 1 arguments, but got 0 or more.

**Comment by dubzzz** [comment]
Temporary fix: `fc.constantFrom(foos[0], ...foos.slice(1))`

I will fix this issue in a coming patch

**Comment by dubzzz** [comment]
The problem I see with making it working with `fc.constantFrom(...foos)` is that we will lose the type checking provided by typescript.

In the other hand, the need does not seem absurd. I had exactly the same issue (as fast-check checks itself against itself). I think I will go for it even it it reduces type checks.

**Comment by benny-medflyt** [comment]
Why not just add something like:

```ts
function constantFromArray<T>(values: T[]): Arbitrary<T> {
    return fc.integer(0, values.length - 1).chain(i => fc.constant(values[i]));
}
```

This is completely type safe I believe. (or are you worried about empty `values` array?)

**Comment by dubzzz** [comment]
@benny-medflyt  Just issued a PR for the fix suggested above #123 

Please let me know if such fix would be ok for you, so that I patch the current version to make you able to use the fix

**Comment by benny-medflyt** [comment]
Thanks, that looks good :smiley: 
I'll try it out tomorrow

**Comment by dubzzz** [comment]
Just fixed `constantFrom` for the moment, I might have to do the same for `oneof` and `frequency`.

I let you know as soon as the patch has been released

**Comment by dubzzz** [comment]
@benny-medflyt Your issue should be fixed in 1.2.2 (on-going publication by Travis CI). I am gonna handle the two remaining functions in a later patch

**Comment by benny-medflyt** [comment]
Thanks works great! :+1:

**Comment by dubzzz** [comment]
Can you please close the issue if everything is alright on your side?

I will open another issue to track the part specific to `oneof` and `frequency`
