### ISSUE TITLE
Arbitrary.chain suggestion, allow to directly return constants

### ISSUE THREAD

**Issue by benny-medflyt** [dubzzz/fast-check#125]
I've found myself using `fc.constant` a lot together with Arbitrary chaining:

```ts
const square = fc.integer().chain(x => fc.constant(x * x));
```

It would be cool if `chain` could automatically wrap the result in a constant arbitrary if it sees that the result was a non-arbitrary value.

Then I could write this:

```ts
const square = fc.integer().chain(x => x * x);
```

---

The idea is from [testcheck-js](https://github.com/leebyron/testcheck-js) where chain looks like this:

```ts
class ValueGenerator<T> {
    // ...

    then<U>(fn: (value: T) => ValueGenerator<U> | U): ValueGenerator<U>;

    // ...
}
```

https://github.com/leebyron/testcheck-js/blob/c7dce0773142546e1b4e208c13b87e7f8f9be253/type-definitions/testcheck.d.ts#L67

**Comment by dubzzz** [comment]
You should have a look to `.map` operation instead.

It is way more powerful: preserves the full power of shrink, does not need to allocate other arbitraries

**Comment by dubzzz** [comment]
Your example with map:

```
const square = fc.nat().map(x => x*x)
```

**Comment by dubzzz** [comment]
For more details concerning why you should prefer `map` over `chain` (aka `flatMap` or `then`). You can have a look to my first answer in #108. It explains why shrinking `map` is way more powerful than shrinking `chain`.

**Comment by benny-medflyt** [comment]
Oops I did indeed not see `map`, works great, thanks!

I've only just started using "fast-check" and haven't used shrinking yet, but looking forward to the experience hopefully soon :)

Closing

**Comment by dubzzz** [comment]
Feel free to report any other issues or provide feature suggestions
