### ISSUE TITLE
async tests

### ISSUE THREAD

**Issue by naseemkullah** [dubzzz/fast-check#1330]
## 💬 Question and Help

Hello!

I'd like to confirm that I cannot use fast-check with an async test? 
If so is it feasible to overcome this?

i.e.:

```js
fc.assert(
  fc.property(
    fc.string(), fc.string(), fc.string(),
    async (a, b, c) => await isSubstringAsync(b, a + b + c),
  )
)
```

results in:

> Type 'Promise<boolean>' is not assignable to type 'boolean | void'.

Use case: incorporating fast-check with integration testing

**Comment by dubzzz** [comment]
Hello,

For async tests, `fc.asyncProperty` should be used instead of `fc.property`.

Your code updated with `fc.asyncProperty`:

```js
await fc.assert(
  fc.asyncProperty(
    fc.string(), fc.string(), fc.string(),
    async (a, b, c) => await isSubstringAsync(b, a + b + c),
  )
)
```

**Comment by naseemkullah** [comment]
Great, thank you!
