### ISSUE TITLE
How to make one arbitrary relative to another?

### ISSUE THREAD

**Issue by spiffytech** [dubzzz/fast-check#1439]
## 💬 Question and Help

How can I have arbitrary `a` that generates a number, and arbitrary `b` that generates a number greater the one `a` generated?

**Comment by dubzzz** [comment]
There are actually multiple ways to do that using fast-check. Here are some with their pros and cons.

**Filter** - it unfortunately discards half of the generated values
```js
fc.assert(fc.property(
  fc.tuple(fc.nat(), fc.nat()).filter(([a,b]) => a <= b),
  ([a, b]) => {
    expect(a).toBeGreaterThanOrEqualTo(b);
  }
));
```

**Pre-assert** - it unfortunately discards half of the generated values
```js
fc.assert(fc.property(
  fc.nat(), fc.nat(),
  (a, b) => {
    fc.pre(a <= b);
    expect(a).toBeGreaterThanOrEqualTo(b);
  }
));
```

**Chain** - it comes with less efficient shrinker
```js
fc.assert(fc.property(
  fc.nat().chain(n => fc.tuple(fc.nat({max:n}) fc.constant(n))),
  ([a, b]) => {
    expect(a).toBeGreaterThanOrEqualTo(b);
  }
));
```

**Map** - the best, shrinker is ok, no discard - but more difficult to put in place in some cases
```js
fc.assert(fc.property(
  fc.tuple(fc.nat(), fc.nat()).map(([a,b]) => a <= b ? [a,b] : [b,a]),
  ([a, b]) => {
    expect(a).toBeGreaterThanOrEqualTo(b);
  }
));
```

_I definitely need to add a section related to that kind of construct in the official documentation_

**Comment by spiffytech** [comment]
Excellent, I think map will work great for what I need. Thanks!

**Comment by Zirak** [comment]
Forgive a drive-by commenter, but another approach to `map` could be something like:

```js
fc.assert(fc.property(
  fc.tuple(fc.nat(), fc.nat()).map(([a,b]) => [a, a + b]),
  ([a, b]) => {
    expect(a).toBeGreaterThan(b);
  }
));
```

At the risk of overflowing `b`.

**Comment by dubzzz** [comment]
I just updated the documentation to reference this tip - https://github.com/dubzzz/fast-check/pull/1440 (not merged yet)

@Zirak - I also added your solution
