### ISSUE TITLE
Question: How to convert Arbitrary<T>[] to Arbitrary<T[]>

### ISSUE THREAD

**Issue by benny-medflyt** [dubzzz/fast-check#145]
Hi, I have an array of arbitraries: `Arbitrary<T>[]`
I need to convert it to a single `Arbitrary<T[]>`

I tried using this function:

```ts
function f<T>(arbs: Arbitrary<T>[]): Arbitrary<T[]> {
    if (arbs.length === 0) {
        return fc.constant([]);
    } else {
        return fc.tuple(arbs[0], f(arbs.slice(1))).map(([first, rest]) => [first].concat(rest));
    }
}
```

It works, but fails with "Maximum call stack size exceeded" for large arrays. I couldn't figure out a way to write it without recursion.

Help would be appreciated, thank you

**Comment by dubzzz** [comment]
Hi @benny-medflyt, 

In your case, you should use `fc.genericTuple` as documented at https://dubzzz.github.io/fast-check/index.html#generictuple

It does exactly what you are looking for with `f`: `genericTuple<Ts>(arbs: Arbitrary<Ts>[]): Arbitrary<Ts[]>`.

Just tried it at https://runkit.com/dubzzz/fc-generictuple
Please let me know if it fixes your problem.

**NOTE:** *For the moment, `tuple` can only handle a limited number of arbitraries (up to 22). `genericTuple` on the opposite does not have any limits but provide less powerful typings when mixing multiple types of `Arbitrary`.*

Regards,
Nicolas

**Comment by benny-medflyt** [comment]
Thanks! works perfectly!
Closing
