### ISSUE TITLE
How does using .map affect shrinking?

### ISSUE THREAD

**Issue by spion** [dubzzz/fast-check#146]
I would imagine if I have an arbitrary and .map it, it will be shrinked by shrinking the source arbitrary then applying the map function to the result?

**Comment by dubzzz** [comment]
Normally it should be the case: shrink the source then run map.

Make sure your map function is not changing the source, changing the source might affect shrinking in some rare cases. 

Do you have an example where it fails?

**Comment by dubzzz** [comment]
By the way, fast-check uses map internally to build most of its arbitraries (except: `integer` - base of others, `array`- base of others - and `lorem` - based on `chain`).

**Comment by spion** [comment]
I had a bug, indeed map is called after shrinking the base case. Closing.
