### ISSUE TITLE
More perf issues with closure classes

### ISSUE THREAD

**Issue by spion** [dubzzz/fast-check#147]
Looks like V8 really hates those closure classes. Its taking 36s to generate 100 samples, with most of the time spent in the generate method of:

```typescript
  noBias(): Arbitrary<T> {
    const arb = this;
    return new class extends Arbitrary<T> {
      generate(mrng: Random): Shrinkable<T> {
        return arb.generate(mrng);
      }
    }();
  }
```

Should I try to do a PR that removes them all?

**Comment by spion** [comment]
p.s. I can't actually reliably reproduce this with a test case, unfortunately. Sometimes I get amazing performance (1000 runs in 6s), sometimes its really bad (30 runs in 30s). 

I'll try to make a nice isolated test case and if I fail by tomorrow, will close the issue.

**Comment by dubzzz** [comment]
Thanks for the analysis. For the moment, I have not spent so much time on the performances except fixing the closure related issues you raised few times ago. I still have the point in mind :) 

There is definitely a performance issue to fix. Replacing closures should solve most of the problem.

I am OK with replacing closures in a PR. Please let me know if you have time to do the fix, otherwise I will submit one on my side (a bit later).

**Comment by dubzzz** [comment]
Looks strange, `noBias` should not be called multiple times in a run..

**Comment by dubzzz** [comment]
Are you calling `noShrink` explicitly within a `chain`?

**Comment by sledorze** [comment]
@dubzzz @spion guys.. stick with it!

**Comment by spion** [comment]
@dubzzz it is indeed strange, i am still working on trying to reproduce the issue consistently. I must be triggering V8 de-optimizations accidentally somewhere - i am no longer entirely sure its fast-check related.

**Comment by spion** [comment]
Ok, here is a good enough sample to reproduce the issue, I think:

```typescript
//tslint:disable
/**
 * Perf
 */
import * as fc from 'fast-check';

import { Arbitrary } from 'fast-check';

let loremIpsum = fc.record({
  text: fc.lorem(100),
  type: fc.constant('x'),
  attrs: fc.constant({}),
  markup: fc.option(
    fc.array(
      fc.record({
        type: fc.oneof(fc.constant('b'), fc.constant('i'), fc.constant('u')),
        start: fc.nat(1),
        end: fc.nat(100), // we can normalize it later
      }),
      1,
      10,
    ),
  ),
});

let section = (n: number): Arbitrary<{ heading: any; children: any[] }> =>
  fc.record({
    heading: loremIpsum,
    children: fc.array(
      n > 0 ? fc.oneof(loremIpsum, loremIpsum, loremIpsum, section(n - 1) as any) : loremIpsum,
      10,
    ),
  });

console.time('lorem');
fc.assert(fc.property(section(10), s => !(s.children.length === 4 && s.children[0].text == null)), {
  seed: 1531485347737,
});
console.timeEnd('lorem');
```

Only 5 samples were generated, but 20 shrinks. That takes around 4s.

**Comment by spion** [comment]
In my fork, I made some changes that brought it down to 1s:

https://github.com/spion/fast-check/tree/fix/perf-2-stream

but one of those changes is to target ES6 - the TS emitted generators are still behaving kinda slow.

**Comment by dubzzz** [comment]
@spion Thanks a lot for the analysis, fork, commit... I will not be able to give you a full feedback on it this week-end but I will have a look to it asap when I get back.

Can you please run a `npm run format:fix` on your commit so that I can review the diff from my mobile? I tried but barely all lines have been changed according to GitHub diff.

*Going ES6*

For the moment, I would prefer being compatible with most of node versions. I now fast-check is used on projects running node 0.12 (one of js-yaml, query-string or left-pad is using it in its travis build). 

*oneof and shrink of recursive structures*

Quick point concerning the structure you try to generate and the way fast-check will shrink it. You are using a `fc.oneof(simpleStruct, simpleStruct, recursiveStruct)`. Unfortunately when fast-check shrinks it, it will not go from `recursiveStruct` to `simpleStruct` or vice-versa. Maybe using `chain` will be quicker for your case as it will try the `simpleStruct` too on shrink. You might give a try to:

```typescript
fc.nat(2).chain(p => p === 2 ? recursiveStruct : simpleStruct);
```

*Number of shrink can be misleading*

One important point to note is that the number of shrinks represents the depth of the minimal counterexample. If you add a counter counting the number of execution of your check function you might be quite surprised. I need to add such data in the report because number of shrinks is a misleading measure.

**Comment by spion** [comment]
Ran format-fix, but I think i managed to mess things up more than fix can help! :grinning: 

You can make git ignore the problem by looking at https://github.com/dubzzz/fast-check/compare/master...spion:fix/perf-2-stream?expand=1&w=1 (w=1 makes the whitespace differences go away). I'll try and fix it later

> For the moment, I would prefer being compatible with most of node versions

No problem, I'm definitely not planning on actually merging this PR as it is, ES6 included. Its mainly exploration to find the bottlenecks at this stage.

I originally switched to ES6 mainly because I get much better diagnostics from `node10 --prof`  and ES6 code. Turns out, my ES6-specific optimizations did not actually help when target is es3 :grin: 

> one-of

Thanks for the pointers on that! I'll see what I can do in my original code.

**Comment by spion** [comment]
The counter says the assert was attempted 101 times:

count = 101, 4174ms

which makes it 41ms/assert

**Comment by dubzzz** [comment]
What was the performance improvement you measured by extracting the helper functions outside of the methods while keeping es3? If the improvement is significant enough, we should definitely go in this direction.

What was the one of switching to es6 alone?

**Comment by spion** [comment]
Just switching to ES6 doesn't change the time at all, stays at 4s (actually goes from 3.9s to 4.2s)

Only changing the code and keeping ES3 a target : 3.8s

Switching and doing the code change: 1s

Its possible to make the improvement with ES3 as a target too, I just find it more difficult to interpret profiler results :grinning: Don't have the time to do it currently, but I'll try to find some...

**Comment by dubzzz** [comment]
During my holiday I read an article about performance issues and how to deal with it. It was introducing a command line tool called https://www.npmjs.com/package/0x that might help me for the investigations. Just sharing in case it helps you too or in case you have another one in mind :)

**Comment by dubzzz** [comment]
Just did some performance improvements on pure-rand - the library I am using for the random number generation - see #207:
- quicker constructor for mersenne twister generator
- better performances for uniform distributions (thanks to a new signature)

**Comment by dubzzz** [comment]
@spion
Can you retry with the latest master of the repository? Does it fix your issue? 

- I switched to another random number generator - xorshift128+ - which highly reduces memory impact and computation time for random
- In addition, releases 1.6.1 and 1.6.2 revamped deoptimized parts
- Moving to ES6 build would also highly improve the performances but requires a new major. I opened a ticket to deal with that issue

**Comment by spion** [comment]
There are some performance improvements with my troublesome shrinking sample - 8 tests with 21 shrinks (103) assertions are now 3.7s - before, 5 tests with 20 shrinks (101 assertions) ran in 4.1s.

For the non-shrinking parts, I have


| samples  | 1.7.0 | 1.3.0 | 
| ---------|-------|-------|
| 2000     | 18.5  | 20.5  | 
| 4000     | 33    | 38    | 

Its hard to tell how much of it is due to different random numbers generated though, I haven't done any real analysis but on a first glance seems to be

**Comment by dubzzz** [comment]
Just in case, when you say 'before', did you re-run the test with 'before' configuration or are they the values you measured in the past? I am asking that because part of the improvements have been made through minor versions of pure-rand so if you `npm install fast-check@1.0.0` you will already benefit from some of the improvements.

Did you try with latest fast-check version (1.7.0)? Was the target es3 or es6? Which version of node?

On my side with node 10 and both target es3 and es6, I got huge performance improvements. I was using `section(5)` during my benchmarks. See https://github.com/dubzzz/fast-check/blob/master/perf/tasks.js

**Comment by dubzzz** [comment]
By seeing your results more closely, the change that impacted your performances are mainly related to changes made in `Stream`. Changes on generation side might not highly impact your snippet.

8 tests for 20 shrinks seems to show that generation time was not huge compared to shrink time (personal hypothesis I still need to confirm). Thus it means that I have to dig a little bit more into how to improve the shrinking time :)

**Comment by spion** [comment]
I re-ran the exact same test with both 1.3.0 and 1.7.0 making sure beforehand that the package currently installed is the right version via `cat node_modules/fast-check/package.json | grep version`. 

In addition I ran 2K and 4K non-failing samples with both 1.3.0 and 1.7.0

**Comment by dubzzz** [comment]
Can you double check the version of `pure-rand` too?

**Comment by dubzzz** [comment]
For fast-check 1.3.0, to be in the state before my changes in pure-rand you should have "pure-rand": "1.1.1"

**Comment by spion** [comment]
Hrm. I seem to be getting the same result with both versions of pure-rand: 

with 2K samples
21s with pure-rand ~1.1.1 and fast-check 1.3.0; 
21s with pure-rand 1.5.0 and fast-check 1.3.0

**Comment by spion** [comment]
Repro repo: 

https://github.com/spion/test-fast-check-pure-rand-perf

```
yarn install
yarn start
```

My output:

```
36702 % yarn start
yarn run v1.10.1
$ tsc && yarn add pure-rand@1.1.1 && yarn show-pure-rand && node src/index && yarn add pure-rand@1.5.0 && yarn show-pure-rand && node src/index
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ pure-rand@1.1.1
info All dependencies
└─ pure-rand@1.1.1
$ cat node_modules/pure-rand/package.json | grep version
  "version": "1.1.1",
perf: 18635.758ms
Asertion count: 2000
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 0 new dependencies.
$ cat node_modules/pure-rand/package.json | grep version
  "version": "1.5.0",
perf: 18617.112ms
Asertion count: 2000
Done in 41.03s.
```

**Comment by dubzzz** [comment]
@spion Really sorry for the delay, I did not have much time to investigate the issue recently.

I just went through your repository: https://github.com/spion/test-fast-check-pure-rand-perf

Unfortunately as `fast-check@1.7.0` and `pure-rand@1.1.0` are not compatible, yarn downloads both `pure-rand@1.1.0` and `pure-rand@1.5.0`. Basically if you take a look into `node_modules/fast-check` you will see that it comes with its own `node_modules` with `pure-rand@1.5.0` in it.

If I am not wrong, when running the first test:
`tsc && yarn add pure-rand@1.1.1 && yarn show-pure-rand && node src/index`

You actually use `fast-check@1.7.0` and `pure-rand@1.5.0`.

**Comment by dubzzz** [comment]
As the random generator used between `fast-check@1.7.0` and `fast-check@1.3.0` explicitely setting a `seed` might bias the results. We might imagine that for this seed 1.3.0 fails before than 1.7.0..

**Comment by spion** [comment]
I see, that makes sense.

No worries about performance issue by the way - we've found a "happy place" with the current performance of fast-check; we generate smaller structures by reducing the probability of adding nodes with children as the depth goes up, and we assert multiple properties in a single sample. That seems to work pretty well!

**Comment by spion** [comment]
Yes lets close. I haven't had the time to do more tests but I don't have performance issues ATM. Will let you know if something pops up.
