### ISSUE TITLE
Switch to variadic generics for property and tuple

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#154]
Recent addition of "Extracting and spreading parameter lists with tuples" in TypeScript - https://blogs.msdn.microsoft.com/typescript/2018/07/12/announcing-typescript-3-0-rc/

It might be used to simplify multiple prebuild scripts.

Unfortunately it might impact the signatures provided for `fc.property` as rest parameters have to be at the end.

```typescript
// OK
function call<TS extends any[], R>(fn: (...args: TS) => R, ...args: TS): R {
    return fn(...args);
}
// Not OK
function call2<TS extends any[], R>(...args: TS, fn: (...args: TS) => R): R {
    return fn(...args);
}
```

**Comment by dubzzz** [comment]
In order to use this new TypeScript feature for fast-check code and get rid of all the unnecessary prebuild scripts, I see two potential alternatives for the signature of `property`:

- `fc.property([arb1, arb2,...], predicate)` - not sure it is feasible
- `fc.property(predicate, arb1, arb2,...)`

I'm not sure I will be able to keep today's signature and use this feature.

**Comment by dubzzz** [comment]
Done in https://github.com/dubzzz/ava-fast-check

Project must wait TypeScript 3.1 for the official support

**Comment by nth-commit** [comment]
You can replicate the existing API with the new variadic tuple feature in TS 4.0.

(approximated the existing types, Property and Arbitrary)

```typescript
type Property<T> = {}

type Arbitrary<T> = {};

type UnwrapArbitrary<T extends Arbitrary<any>> = T extends Arbitrary<infer U> ? U : never;

type PropertyFunction<T extends Array<Arbitrary<unknown>>, TResult> = (...args: { [P in keyof T]: UnwrapArbitrary<T[P]> }) => TResult;

declare function property<T extends Array<Arbitrary<unknown>>, TResult>(...args: [...T, PropertyFunction<T, TResult>]): Property<TResult>;

declare const arb0: Arbitrary<number>;
const p0 = property(arb0, (x0) => {
  const _x0: number = x0;
  return true;
});

declare const arb1: Arbitrary<string>;
const p1 = property(arb0, arb1, (x0, x1) => {
  const _x0: number = x0;
  const _x1: string = x1;
  return true;
});

declare const arb2: Arbitrary<{ foo: string }>;
const p2 = property(arb0, arb1, arb2, (x0, x1, x2) => {
  const _x0: number = x0;
  const _x1: string = x1;
  const _x2: { foo: string } = x2;
  return true;
});
```

**Comment by dubzzz** [comment]
@nth-commit Sorry for the late reply.

That looks nice 👍 Thanks a lot 👍 

I'll certainly move to something like that in the future. For the moment, I'll try not to break existing users and let them use any TS version >= 3.2. Such change would be feasible with the next major bump of fats-check (not yet planned).

**Comment by dubzzz** [comment]
@nth-commit Thanks a lot for the suggestion. The variadic version will be released for the next major of fast-check.

Here are the associated PRs:
- https://github.com/dubzzz/fast-check/pull/1516
- https://github.com/dubzzz/fast-check/pull/1518

I finally found an even shorter way to have it working.
