### ISSUE TITLE
Link to API Reference in Readme gives 404

### ISSUE THREAD

**Issue by tmueller** [dubzzz/fast-check#1554]
## 💥 Regression Report

The link to the API Reference, that is given in Readme, leads to https://dubzzz.github.io/fast-check/. When going to this URL, github shows a 404 - not found page.

## Versions

Worked up to version: [wayback machines latest version is of November 17, 2020](https://web.archive.org/web/2020*/https://dubzzz.github.io/fast-check/)

## To Reproduce

Steps to reproduce the behavior: click on "API Reference" on github page

## Expected behavior

Page with Api Reference is shown.

**Comment by dubzzz** [comment]
It should be fixed now. My setup for GitHub pages somehow broke. Thanks for the report

**Comment by tmueller** [comment]
Works for me :) Thanks for fixing it that fast.
