### ISSUE TITLE
generate a deterministic uuids using fast-check

### ISSUE THREAD

**Issue by dagda1** [dubzzz/fast-check#1570]
## 💬 Question and Help
I have the following code which I thought would generate a new uuid each time but in a deterministic fashion:

```ts
fc.configureGlobal({ seed: 0 });

export const generateUUID4 = (): string => {
  const Uuids = fc.sample(fc.uuidV(4), { numRuns: 1000 });
  const arb = fc
    .infiniteStream(fc.integer({ min: 0, max: 1000 }).noBias().noShrink())
    .map((s) => Uuids[s.next().value]);

  return fc.sample(arb)[0];
};
```

But this returns the same `uuid` each time.

The only way I can get it working is like this which is horrific with a global variable:

```ts
fc.configureGlobal({ seed: 0 });

const Uuids = fc.sample(fc.uuidV(4), { numRuns: 1000 });
let UuidCounter = 0;

export const generateUUID4 = (): string => {
  const next = Uuids[UuidCounter];

  UuidCounter++;

  return next;
};
```

**Comment by dubzzz** [comment]
Hello @dagda1,

Unfortunately the behaviour you expose there is fully expected. Indeed here is your snippet with comments added:
```ts
// We ask fast-check to default the seed to 0 for any calls to: assert, check but also sample and statistic
fc.configureGlobal({ seed: 0 });

export const generateUUID4 = (): string => {
  // id being defaulted to 0, Uuids will always have the same values for uuids
  const Uuids = fc.sample(fc.uuidV(4), { numRuns: 1000 });

  const arb = fc
    .infiniteStream(fc.integer({ min: 0, max: 1000 }).noBias().noShrink())
    .map((s) => Uuids[s.next().value]);

  // id being defaulted to 0, the call to sample will result:
  // in the exact same stream, thus s.next().value will be the same and Uuids[s.next().value] too
  return fc.sample(arb)[0];
};
```

Basically if you want to use the generator of uuids of fast-check to build uuids you could do something like:
```js
export const generateUUID4 = (): string => {
  return fc.sample(fc.uuidV(4), {seed: Math.random(), numRuns: 1})[0]; // we override the seed
}

// or alternatively
export const generateUUID4 = (): string => {
  const backup = fc.readConfigureGlobal();
  fc.configureGlobal({});
  const uuid = fc.sample(fc.uuidV(4), {numRuns: 1})[0];
  fc.configureGlobal(backup);
  return uuid;
}
```

Nonetheless I do not recommend using fast-check to build proper uuid v4 outside of tests. Indeed, the uuids produced by fast-check are totally correct but they do not come with all the security expected for uuids: they have been designed to be used within tests but not production scenario (they tend to create 000-000 more often for instance).

Why do you need to have `generateUUID4`? Maybe I can give you another way round to make it work?

**Comment by dagda1** [comment]
@dubzzz thank you for the answer. 

i am definitely not using this for production or i would just use uuid v4.

i am creating an api simulator that provides fake apis that devs can use instead of the real api like an auth0 simulator.  

i would like to create deterministic data without persisting it to a db.   i thought that fast-check could save me some dev as there appears some overlap in generating data for tests and data for a simulator.

i appreciate that i am not using your great if functionality outside of the domain it is meant for and really appreciate your response.

 do you think i can use fast check to create say 100 fake users with different uuids deterministicly outside the bounds of a property test?  could i use the infinite stream?

**Comment by dubzzz** [comment]
> I am definitely not using this for production

Perfect!

In order to generate fake users based on fast-check you have several options.

**Option 1** - Build an arbitrary able to generate your users and sample on it

```js
import fc from 'fast-check';

const userArbitrary = fc.record({
  id: fc.uuidV(4),
  username: fc.string(),
  birthday: fc.date(),
  town: fc.oneof('Paris', 'London'),
}, {requiredKeys: ['id', 'username']});

function genOneUser() {
  // using seed=0 in order to always generate the same
  return fc.sample(userArbitrary, {seed:0, numRuns:1})[0];
}

function genNUsers(n) {
  // using seed=0 in order to always generate the same
  return fc.sample(
    fc.set(userArbitrary, {
      minLength: n,
      maxLength: n,
      compare: (u1,u2) => u1.id === u2.id || u1.username === u2.username
    }), {seed:0, numRuns:1}
  )[0];
}
```

**Option 2** - Call manually the arbitraries on generate

```js
import fc from 'fast-check';
import prand from 'pure-rand'; // used by fast-check internally

const mrng = new fc.Random(prand.xorshift128plus(0));

function nextUuid() {
  return fc.uuidV(4).generate(mrng).value;
}

nextUuid() // generate first uuid (stable across runs)
nextUuid() // generate second uuid
```

**Option 3** - Fully rely on pure-rand + maybe the fc.Random wrapper that can be pretty useful

**Comment by dagda1** [comment]
@dubzzz thank you for taking the time to answer.  I am not using your lib as intended but these are great answers.

Fast-check is totally awesome and I love how you are using generators.  Generators are seriously underused in js.

Thank you, sir!   This is great

**Comment by dubzzz** [comment]
As `fc.uuidV` has been designed for pbt, you may want to call it with `noBias` to reduce the chances of collisions `fc.uuidV(4).noBias()`. Indeed by default fast-check will try to produce collisions between uuids to check how the code behave to them. Moreover except if explicitely specified that collisions should never occur, fast-check consider them as valid options so will try them from time to time.

**Comment by dubzzz** [comment]
Maybe you can have a look to `faker` if you only want to fake data.

By the way, faked data can also be used within fast-check if needed even if they are less powerful by design (they try to fake data not to find bugs). See https://github.com/dubzzz/fast-check/blob/main/documentation/Tips.md#combine-with-other-faker-or-random-generator-libraries

**Comment by dagda1** [comment]
@dubzzz I am using faker (converted to arbitraries) but there seems a lot more in fast-check beside the fake data part.

But it might end up just being faker.  You can seed the generation so it will be deterministic
