### ISSUE TITLE
Unnecessary repetitions

### ISSUE THREAD

**Issue by Djaler** [dubzzz/fast-check#1576]
## 🐛 Bug Report

Fast-check shouldn't run more tests that are necessary to check all cases 

## To Reproduce

Steps to reproduce:
```
const arb = fc.record({
    left: fc.boolean(),
    right: fc.boolean(),
});

it('should run test only 4 times', () => {
    fc.assert(fc.property(arb, (data) => {
        console.log(data);
    }));
});
```
If I run this test, it will log data 100 times (default count)

## Expected behavior

Fast-check shouldn't repeat cases and run only 4

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            |  2.13.0          |
| node                  |  14.16.0          |
| TypeScript           |  4.2.2          |

**Comment by dubzzz** [comment]
Hello, 

It is a known limitation of fast-check today.

Runs are always independent from each others (otherwise replaying stuff would be impossible). Indeed for the need of replay, fast-check should, given an offset, generate the given entry without passing over the ones before. 

An other issue, is that arbitraries are opaque structures for assert or property. Property would be unable to know that the arbitrary only produces 4 values and not more. 

On top of that, while in this case comparison is easy, the comparison is not always that simple to do.

Moving the issue as a feature today, rather than a fix.

**Comment by dubzzz** [comment]
One of the possibilities would be to cancel the run when it starts (at property level).

Two possibilities there:
- cancel it via `fc.pre` so another run will be try
- skip it via a simple `if`

The main complexity being: what do we consider equal? Deep equality would fit some needs but not all, and may be difficult to have right (see the number of bugs in Jest, Jasmine or Underscore related to bugs of deep equal).

An easy workaround might be to ask the user for a compare function.

**Comment by Djaler** [comment]
I thought that it can be possible to do something like this (pseudo-code):
```
const valuesHashes = new Set()

for(const i = 0; i < numRuns; i++) {
    const values = generate(arbitraries)
    const currentHash = hash(values)
    if (valuesHashes.has(currentHash) {
        continue
    }
    valuesHashes.add(currentHash)
    
    runProperty(test, values)
}

```

**Comment by Djaler** [comment]
I tried `fc.pre`, but seems it can not help me, because of `too many pre-condition failures encountered`

**Comment by dubzzz** [comment]
> I tried `fc.pre`, but seems it can not help me, because of `too many pre-condition failures encountered`

Indeed `fc.pre` might be useful for a code like this one:
```
const arb = fc.record({
    left: fc.nat(9), // 0,1,2,3,4,5,6,7,8,9
    right: fc.nat(9), // 0,1,2,3,4,5,6,7,8,9
});

const alreadySeen = new Set();
it('should run twice the same value', () => {
    fc.assert(fc.property(arb, (data) => {
        const key = `${data.left},${data.right}`;
        fc.pre(!alreadySeen.has(key));
        alreadySeen.set(key)
        console.log(data);
    }));
});
```

In your case only the `if` will work as you will never be able to run 100 different combinations.

**Comment by dubzzz** [comment]
By the way, the way to implement it (if the if/pre is good enough) might look pretty close to the one I used for `skipAllAfterTimeLimit` and `interruptAfterTimeLimit`, see:
- the property-wrapper: https://github.com/dubzzz/fast-check/blob/e645c3612fc76055ea0f5bab1a80c6c73ecfc1af/src/check/property/SkipAfterProperty.ts
- the enabler: https://github.com/dubzzz/fast-check/blob/e645c3612fc76055ea0f5bab1a80c6c73ecfc1af/src/check/runner/DecorateProperty.ts

**Comment by dubzzz** [comment]
Instead of `hash`, a possible comparator for values might be the stringified version of the entity. It can easily be retrieved with `fc.stringify` and has the benefit to handle many kind of objects including recursive ones, symbols, regexes...

**Comment by Djaler** [comment]
What about functions?

**Comment by dubzzz** [comment]
> What about functions?

```js
fc.stringify((a, b) => a + b) // is: "(a, b) => a + b"
fc.stringify(function plop(a, b) { return a + b; }) // is: "function plop(a, b) {\n        return a + b;\n      }"
```

**Comment by Djaler** [comment]
Looks good!

**Comment by dubzzz** [comment]
For the record `fc.stringify` is the one printing the error messages when a test fails. Here is part of what it can handle so far: https://github.com/dubzzz/fast-check/blob/main/test/unit/utils/stringify.spec.ts

**Comment by dubzzz** [comment]
Version 2.14.0 includes the feature
