### ISSUE TITLE
SIGTERM/SIGKILL behavior

### ISSUE THREAD

**Issue by hamiltop** [dubzzz/fast-check#1596]
## 🚀 Feature Request

Allow a scheduled task to be terminated midway through and test the resulting state.

## Motivation

This might be too large in scope and there might be another way to do this, but we've found a few bugs in our systems where cleanup during exception handling doesn't run. Usually this is because the process was killed abruptly. This results in really weird data issues that are very hard to track down. Simulating it via a test would be amazing.

## Example

Using a non transactional database like dynamodb, you might have code that looks like this:

```
function doThing() {
  writeFoo();
  const foos = readAllFoo();
  if (foos.length > 1) {
    mergeAllFoos(foos);
  }
}
```

If the process is killed or the instance crashes or whatever, you can be left in a state where `foos` has length > 1.

I guess this could be accomplished by some sort of test that will check that a constraint holds at all times throughout a test. In this case, I would want to ensure that `foos.length <= 1` at all times. Maybe there's a way to do this with `fc.schedule` and mocking the database service.

Anyway, would love your thoughts here. Thanks!

**Comment by dubzzz** [comment]
Sorry for the delay, I'll have a look to the issue in the coming days

**Comment by dubzzz** [comment]
`fc.scheduler` might be perfect for your needs. You can, for instance, use it to wrap your api calls using `s.scheduleFunction` and use it to trigger a halt signal with something like `s.schedule(Promise.resolve('running halt')).then(halt)`.
