### ISSUE TITLE
Lorem-ipsum dependencies prevents rollup

### ISSUE THREAD

**Issue by hath995** [dubzzz/fast-check#168]
Lorem-ipsum dependencies prevents Rollup from bundling fast-check for use inside of the browser because it requires the NodeJS os library. Maybe find an alternative or make the dependency optional?

https://github.com/knicklabs/lorem-ipsum.js/blob/master/lib/generator.js#L19

**Comment by dubzzz** [comment]
Would using https://github.com/calvinmetcalf/rollup-plugin-node-builtins/ solve temporary your issue?

**Comment by hath995** [comment]
I'll give it a shot for now, just isn't my preferred solution.

**Comment by dubzzz** [comment]
@hath995 Could you please give more details on the configuration of rollup you are using? I just tried with a very simple one without any error: `npx rollup ./lib/fast-check.js --file bundle.js --format umd --name "myBundle"`

**Comment by dubzzz** [comment]
Just issued https://github.com/knicklabs/lorem-ipsum.js/pull/26 onto lorem-ipsum.js repository. A simple rollup configuration might be useful to add a test checking it does not break on a next version (both on fast-check side and lorem-ipsum.js)

**Comment by dubzzz** [comment]
@hath995 Is it the error you got?

![image](https://user-images.githubusercontent.com/5300235/44491924-032c2d00-a663-11e8-8524-d7d7c7114608.png)

Actually, I think it is just a warning.

**Comment by dubzzz** [comment]
If so you can try to add `external: [ 'os' ]` to your configuration file as stated at https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency

**Comment by dubzzz** [comment]
Just tried to add a test at build time derived from the config you attached.
@hath995 Can you please tell me if it corresponds to your needs?

As soon as my PR on lorem-ipsum.js gets accepted and published I will patch fast-check with the latest version of it.

**Comment by hath995** [comment]
The external: [ 'os' ] setting did not seem to work. Rollup produced an incomplete js bundle.

**Comment by dubzzz** [comment]
I finally succeeded in reproducing the reported issue. The PR does not pass the tests as expected: https://github.com/dubzzz/fast-check/pull/183

But it passes if I manually apply https://github.com/knicklabs/lorem-ipsum.js/pull/26 to node_modules/lorem-ipsum.js. I hope the PR will get accepted quickly so that it fixes your problem.

**Comment by dubzzz** [comment]
By the way, lorem-ipsum.js also causes me troubles on esm builds - but for another problem I need to formalize and report to the owner.

See https://github.com/dubzzz/fast-check/pull/182

**Comment by dubzzz** [comment]
@hath995 My commit has been merged into lorem-ipsum @ 1.0.6. I think removing lorem-ipsum from the node_modules and doing a `npm install` should fix your problem. Meanwhile I will move to 1.0.6 in my package.json to enforce the change.

**Comment by hath995** [comment]
Awesome!
Thanks so much for working on that! I've been swamped with projects but I'd like to keep contributing to fast-check. 
Thanks again!

**Comment by hath995** [comment]
It worked for me! Closing the issue!

**Comment by hath995** [comment]
I've narrowed this down. It seem to be related to the changes you made after 1.5. Reverting back to 1.5 exactly fixes the issue for me. After tracking it down it seems that you didn't use es 6 syntax in one place in the LoremArbitrary.ts

**Comment by hath995** [comment]
created #226 which should fix the issue once you deploy to npm.

**Comment by dubzzz** [comment]
On-going release (1.7.1) - please confirm the issue is fixed with this version (close the ticket if it does)

**Comment by hath995** [comment]
It is fixed! Thanks again!
