### ISSUE TITLE
Custom examples for property(..., context(), ...)?

### ISSUE THREAD

**Issue by ion1** [dubzzz/fast-check#1825]
## 💬 Question and Help

It is unclear to me how to provide a custom example for the following:

```js
fc.assert(
  fc.property(fc.string(), fc.context(), (str, ctx) => /* ... */),
  { examples: [["x", /* what here? */]] }
);
```

`context()` seems to instantiate an class which is not exported. I would prefer not to make my own implementation of `ContextValue`.

It would be the most convenient not to have to include a value corresponding to the context in the examples at all – maybe the arbitraries provided to the property call could be used if there are more of them than elements in the example tuples – but any solution that gets this to work is good enough. Thanks!

**Comment by dubzzz** [comment]
Hello,

There is today no way to build partial or incomplete examples. A proposal to do so was suggested in the issue https://github.com/dubzzz/fast-check/issues/710#issuecomment-657102743 but for the moment it has not been implemented.

Regarding `ContextValue` for the moment, the implementation is not exposed to the user. I should probably either expose the class or add something like `fc.contextFor()` as I did for `fc.scheduler()` (see `fc.schedulerFor()`).

Given what has been released so far, the only trick I'd have is:
```js
const buildContext = () => fc.sample(fc.context())[0];
fc.assert(
  fc.property(fc.string(), fc.context(), (str, ctx) => /* ... */),
  { examples: [["x", buildContext()]] }
);
```

Not perfect but it should work well.

**Comment by tskj** [comment]
Has there been any development on this? This seems like kind of a hacky solution for such a common and basic usecase (I like leaving my logs in the tests, in case it breaks in the future).

**Comment by dubzzz** [comment]
No plan to do anything for this one. Not part of the roadmap neither short nor medium term

**Comment by dubzzz** [comment]
The project being open source, it's done on free time. If you like it or want improvements there is a way to contribute financially to it: https://github.com/sponsors/dubzzz. There are also ways to contribute by opening constructive issues with clear suggestions followed by PRs if you think it takes too long for you.

**Comment by tskj** [comment]
Sure thing!

I have submitted a proper bug report [here](https://github.com/dubzzz/fast-check/issues/3459), and also two suggestions for improving the docs if fixing the bug will never be on the roadmap [here](https://github.com/dubzzz/fast-check/pull/3458) and [here](https://github.com/dubzzz/fast-check/pull/3457)!
