### ISSUE TITLE
Usage Question of map and chain

### ISSUE THREAD

**Issue by sladiri** [dubzzz/fast-check#187]
Hi,

Thank you for this great tool.

I want to generate an array of unique integers. I realise that that there is the built-in set-arbitrary, so this is more of a question about `chain` and `map`. First I tried `chain`, below I use `map`, but my question is, if `chain` wouldn't be the more correct version? Am I using `chain` incorrectly?

I am unsure what the problem with the following arbitrary for a stateful model test is. The stacktrace is at the bottom. This is my attempt with `chain`. If I replace the problematic line with the commented line, it works, but is not really a solution.

```
    const Value = fc.oneof(
        fc.tuple(
            fc.asciiString(),
            fc.integer(),
            fc.constant([]),
            fc.constant({}),
            fc.constant(null),
        ),
    );

    const allCommands = [
        fc
            .tuple(
                fc.asciiString(1, 1),
                Value,
                fc.array(fc.nat(10)).chain(arr => {
                    const unique = R.uniq(arr).map(x => fc.constant(x));  // Ramda's unique helper
                    return fc.tuple(...unique);               // Problematic line
                    // return fc.tuple(fc.constant(0));   // Works fine
                }),
            )
            .map(...),
    ];
```

I can use `map` instead of `chain`, but it seems incorrect to me, since I change the number of elements. Both are arrays in Javascript but shouldn't they be really different tuples?
```
    const allCommands = [
        fc
            .tuple(
                fc.asciiString(1, 1),
                Value,
                fc.array(fc.nat(10)).map(arr => {
                    return [...new Set(arr).entries()];
                }),
            )
            .map(...),
    ];
```

```
TypeError: Cannot read property 'generate' of undefined
    at class_3.generate (...\node_modules\fast-check\lib\check\arbitrary\definition\Arbitrary.js:124:45)
    at ...\node_modules\fast-check\lib\check\arbitrary\TupleArbitrary.generic.js:38:84
    at Array.map (<anonymous>)
    at GenericTupleArbitrary.generate (...\node_modules\fast-check\lib\check\arbitrary\TupleArbitrary.generic.js:38:56)
    at Tuple3Arbitrary.generate (...\node_modules\fast-check\lib\check\arbitrary\TupleArbitrary.generated.js:69:30)
    at class_2.generate (...\node_modules\fast-check\lib\check\arbitrary\definition\Arbitrary.js:84:28)
    at OneOfArbitrary.generate (...\node_modules\fast-check\lib\check\arbitrary\OneOfArbitrary.js:47:30)
    at class_2.generate (...\node_modules\fast-check\lib\check\arbitrary\definition\Arbitrary.js:84:28)
    at ...\node_modules\fast-check\lib\check\arbitrary\ArrayArbitrary.js:66:84
```

**Comment by dubzzz** [comment]
Hi, 

Concerning the way to implement `set` without relying on the built-in method, I would certainly go for a `map` rather than a `chain` (aka `flatMap`):
- `map` is designed to change one type into another one (here array into array) — `map` does not map the `Array` type but the `Arbitrary<Array<number>>` type
- `map` fully preserves the shrinking capabilities, `chain` impacts the shrinking (see original pull request #103 for more details)

Concerning the error you get when using `chain`, it might be because the `tuple` requires at least one item. In your case, the array could be empty. Use `fc.genericTuple` for this case (equivalent to `tuple`, a bit less typed, accepting from 0 to infinity - takes an array of arbitraries as input). By the way you can ask fast-check to generate arrays with at least one item by using `fc.array(arb, minSize, max Size)`. 

Regards,
Nicolas

**Comment by dubzzz** [comment]
Does it answer the question?

**Comment by sladiri** [comment]
Hi, I am sorry for the late reply, I will look into the PR for chain to understand how it is different from map.

So is map valid like this?
`Arbitrary<Array<number>> --> Arbitrary<Array<number>>` 
`Arbitrary<Array<number>> --> Arbitrary<Array<string>>`

This would be invalid map, and chain would be correct?
 `Arbitrary<Array<number>> --> Arbitrary<Optional<number>>`

**Comment by sladiri** [comment]
I guess I will have to take more time to read through the source code, so I would say you answered my initial question, thank you. :)

**Comment by dubzzz** [comment]
`map` should be see as you transform one type into another. The following are valid `map` ():

```js
// generate an array of positive integers
// map it into a single integer
// (very strange map but why not) 
fc.array(fc.nat()).map(arr => arr.indexOf(2))

// create a string from an array of characters 
fc.array(fc.char()).map(arr => arr.join(''))

// your own option of string
fc.tuple(fc.boolean(), fc.string()).map([enabled, v] => enabled ? v : null) 

// why not a function always returning the same thing 
fc.anything().map(v => (() => v)) 
```

`chain` on the contrary must be seen as: you need to generate a value before being able to generate a second one

```js
// generate a size then an array of this size
fc.nat(100).chain(size => fc.array(fc.nat(), size, size)) 
// more efficient way would be 
fc.array(fc.nat(), 0, 100)

// generate the min then the max
fc.integer(-100, 100).chain(min => fc.record({
  min: fc.constant(min), 
  max: fc.integer(min, 100)
}))
// more efficient way would be 
fc.tuple(fc.integer(-100,100), fc.integer(-100,100))
 .map([a, b] => (a < b ? {min:a, max:b} : {min:b, max:a})) 
```

The issue of `chain` is more related to its poor shrinking capabilities. In terms of generation of inputs, both should be OK. 

`chain` is used behind `fc.lorem` while `map` is behind `fc.object`, `fc.char`, `fc.string`...

**Comment by dubzzz** [comment]
Fill free to re-open the issue or ask anything else
