### ISSUE TITLE
Parallel execution for asynchronous properties

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#190]
For the moment async properties are executed sequentially. The framework generate one entry, check it then move to the next one (or shrink it).

The idea would be to run all those tasks in parallel (when a certain flag is set).

**Comment by hamiltop** [comment]
Very interested in this feature. I've seen it in Quviq quickcheck and in scalacheck.

What would it take to implement this feature?

**Comment by hamiltop** [comment]
This is a good high level view of how scalacheck presents failures when running in parallel: http://scalacheck.org/files/scaladays2014/#27

**Comment by dubzzz** [comment]
The point of this issue was more to run asynchronous tests in parallel to have the result earlier - not to assess issues within the algorithms if executed in parallel.

Antother issue: I wanted to add a way to troubleshoot async issues directly from fast-check. But to do so I'll have to hook on all Promises (and timeouts, intervals...) launched by the code and write a scheduler to reschedule them in the time. For the moment, it is still at the level of the draft ;)

**Comment by hamiltop** [comment]
Ah interesting.

I wonder if you could set up command like this:

```
StartAsyncOperationACommand
StartAsyncOperationBCommand
AwaitOperationACommand
AwaitOperationBCommand
```

The await operations would have a run check of "is there a pending corresponding operation?" We can run tests like this now most likely. The only complication would be that we would need to make sure all operations complete. Maybe a `finally` section for commands that we want to make sure run last before we finish the test case.

If that all works this could be polished up a bit, but the general functionality might be really close already.

**Comment by Bulletninja** [comment]
Is this a thing? Meaning, can we run things in parallel now, or are there any plans to support it?

**Comment by dubzzz** [comment]
Not yet a thing. It has been 'de-priotized' so far. I felt that running in parallel was not really useful alone without being backed with things being launched in various threads (via workers). Additionally in my classical usecases I mostly let parallel execution to jest or vitest, as a consequence I felt that it may led to create way to many parallel threads (the ones of the test runner and the ones of fast-check).

But at some point I feel that it could come back. I just need to make my mind around a potential plug-in API to be able to simply add such capacities from outside.

**Comment by azerum** [comment]
I use fast-check to make model-based tests against data structures implemented on top of Postgres (e.g. a queue)

Worker threads are not needed in such case to benefit from concurrent execution, since the code is IO-bound. fast-check could run function passed to `asyncProperty` with some concurrency, which would speed up things a lot
