### ISSUE TITLE
Commands generator should not rely on arrays generator 

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#192]
The first implementation of `fc.commands` relies on `fc.array` in order to generate arrays of commands. A more specific implementation may highly decrease the number of shrinks necessary.

**Comment by ashnur** [comment]
Also a question when commands will be replayable? Or is there already a way to generate a list of commands that can be replayed, just not with `.commands`?

**Comment by dubzzz** [comment]
**What is replayable?**

Replayable in fast-check means: restart the test by starting with the minimal counterexample. It can be done by specifying `seed` and `path` as options of `assert` (eg.: `{seed: 1527422598337, path: "9:0:5:6"}`).
[more details...](https://github.com/dubzzz/fast-check/blob/master/documentation/Tips.md#replay-after-failure)

**Commands are not *fully* replayable**

For the moment, `commands` are not replayable: the `path` does not contain enough data to do so. Nonetheless you can still replay the same test suite by specifying the `seed` (eg.: `{seed: 1527422598337}`). You can even restart directly with the first failing case by specifying the first part of `path` (eg.: `"9"` instead of `"9:0:5:6"` - `{seed: 1527422598337, path: "9"}`).

**Quick explanation**

If the first set of commands causing a failure was: `A, B, A, A, C, D, A, A`.
And the failure was encountered on the third `A`, thus the shrinker of `commands` would shrunk `A, B, A, A` instead of  `A, B, A, A, C, D, A, A`.

Replaying would require to know for each counterexample the id of the step that failed.

Today `{seed: 1527422598337, path: "9:0:5:6"}` means that the first counterexample for seed 1527422598337 was encoutered at the 10th generated value. We then shrunk it. It failed on the first shunk value. Shrunk the shrunk value which failed at the 6th shrunk...

For commands to be replayable we would need to have something like: `{seed: 1527422598337, path: "9(5):0(2):5(1):6(0)"}` where `(*)` is the index of the failing step.

**Replayable commands**

Fully replayable commands can be archieved by using `fc.array` instead of `fc.commands`. But it would impact the shrinking.
