### ISSUE TITLE
Arbitrary function support

### ISSUE THREAD

**Issue by JustinLovinger** [dubzzz/fast-check#199]
fast-check should support arbitrary functions, such as in [jsverify](https://github.com/jsverify/jsverify#arbitrary-functions).
This is essential for testing functions that take functions as arguments, such as `map` and `filter`.

**Comment by JustinLovinger** [comment]
I tried to create a custom arbitrary function `fc.anything().map(returnValue => () => returnValue)`, but the displayed error is not helpful because it doesn't include the value of returnValue, it just displays `() => returnValue`.

**Comment by dubzzz** [comment]
Hello @JustinLovinger, 

This feature is part of my current plans for the next minor (or the one after).
I will start working on it very soon (follow #100).

I am gonna have a look into jsverify to see what kind of function it is able to generate (single value / multiple values / pure / unpure...).

Meanwhile your suggestion of displaying `4.map(4 => () => 4)` is pretty interesting ;)

**Comment by dubzzz** [comment]
@JustinLovinger Please feel free to reopen the issue if neither of `fc.func`, `fc.compareBooleanFunc` and `fc.compareFunc` solves your issue

**Comment by dubzzz** [comment]
Released with 1.6.0

**Comment by dubzzz** [comment]
@JustinLovinger - The feature has been enhanced in fast-check@1.8.0, it provides better logs
