### ISSUE TITLE
fc.integer() causes non-terminating behaviour when given certain non-integer arguments for min and max

### ISSUE THREAD

**Issue by jmacmahon** [dubzzz/fast-check#2038]
## 🐛 Bug Report

When using fc.integer() with `max` and `min` parameters, if `0.5 <= (max - min) < 1`, then running through `fc.assert(fc.property(...))` does not terminate.

## To Reproduce

Steps to reproduce:

Any of the following lines do not terminate:
```ts
      fc.assert(fc.property(fc.integer({ min: 0, max: 0.5 }), () => true))
      fc.assert(fc.property(fc.integer({ min: 0, max: 0.999 }), () => true))
      fc.assert(fc.property(fc.integer({ min: 0.5, max: 1.4999 }), () => true))
      fc.assert(fc.property(fc.integer({ min: 0.5, max: 1 }), () => true))
```

All of the following *do* terminate:
```ts
      fc.assert(fc.property(fc.integer({ min: 0, max: 0 }), () => true))
      fc.assert(fc.property(fc.integer({ min: 1, max: 1 }), () => true))
      fc.assert(fc.property(fc.integer({ min: 0, max: 0.4999 }), () => true))
      fc.assert(fc.property(fc.integer({ min: 0, max: 1 }), () => true))
      fc.assert(fc.property(fc.integer({ min: 0, max: 1.5 }), () => true))
      fc.assert(fc.property(fc.integer({ min: 0.5, max: 1.5 }), () => true))
```

## Expected behavior

I expect either:
- the `min` and `max` values behave as if they were rounded (or floored, or even ceiled) to an appropriate integer value,
- or an error to be thrown for specifying non-integer parameters.

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            | 2.17.0 |
| node                  | 14.16.0 |
| TypeScript            | 4.2.4 |

**Comment by dubzzz** [comment]
Option 2 should probably be the solution.

Nonetheless calling integer with min being a non-integer value does not seem to be a valid usage at all. If we add such protection why not adding some if the user passes a bigint value for the min? Throwing is not and may cause deopt.

**Comment by mso42** [comment]
Does TS accept BigInt as `number`? I think passing a value that type-checks fine but is somehow invalid ought to be caught early somehow.

The particular situation, in case it is helpful, was something like:
```ts
const arb = fc.record({
  a: fc.integer(),
  b: fc.integer()
}).chain(({ a, b }) => fc.record({
  a: fc.constant(a),
  b: fc.constant(b),
  c: fc.integer({ min: 0, max: a/b })
})
```

It was more complex than that (and I'm not at the code right now so can't remember exactly), but the gist is that the `max` was computed from two previous arbitraries. Obviously the solution should be to `Math.floor` the value before passing to `max`, but since the type checker does not have your back here, it's easy to cause problems.

**Comment by jmacmahon** [comment]
[Sorry -- previous comment was from my non-work GH account]

Does TS accept BigInt as number? I think passing a value that type-checks fine but is somehow invalid ought to be caught early somehow.

The particular situation, in case it is helpful, was something like:

```ts
const arb = fc.record({
  a: fc.integer(),
  b: fc.integer()
}).chain(({ a, b }) => fc.record({
  a: fc.constant(a),
  b: fc.constant(b),
  c: fc.integer({ min: 0, max: a/b })
})
```

It was more complex than that (and I'm not at the code right now so can't remember exactly), but the gist is that the max was computed from two previous arbitraries. Obviously the solution should be to Math.floor the value before passing to max, but since the type checker does not have your back here, it's easy to cause problems.

**Comment by dubzzz** [comment]
I re-investigated this issue recently but actually being fully bulletproof on this check is not trivial. There are multiple ways to pass buggy min and max values:
- `min > max` - this one is already checked
- non integer values for min or max:
  - `!Number.isInteger(min) || !Number.isInteger(max)`  - this one gives a fake feeling of security but actually it does not avoid bugs related to valid integer values passing Number.MAX_SAFE_INTEGER
  - `!Number.isSafeInteger(min) || !Number.isSafeInteger(max)`  - would break existing users as `{min:Number.MAX_SAFE_INTEGER, max:Number.MAX_SAFE_INTEGER+1}` is fully working (while a bit border line)
- gap between min and max too large: what is too large?

**Comment by julianmrodri** [comment]
I think im facing a related issue with a `max` and `min` for `bigUintN(256)`.

For example the example below never terminates and doesnt print any values. However if I just leave one of them (either upper or lower bound check) it works.

```
        it.only("Test big amounts", async function () {
            const validAmount = fc.bigUintN(256).filter(a =>  a >= BigInt(500000000000000000) && 
a <= BigInt(1000000000000000000000))
            await fc.assert(
                fc.asyncProperty(validAmount, async (amt) => {
                        console.log("Testing amount: "+ amt.toString())
                    })  
            )
        })
```

Is this the same issue? Why could this be happening? 

 I also noticed that it tries to create really big or really small numbers (depending of which `filter` I put). Is there a way to make it go through different values of the spectrum? 

Thanks!

**Comment by dubzzz** [comment]
@ julianmrodri Not related to this issue. Your issue is linked to the warning:

> But be aware that using filter may highly impact the time required to generate a valid entry.

Visible here: https://github.com/dubzzz/fast-check/blob/main/documentation/AdvancedArbitraries.md#filter-values

In your case you ask the arbitrary for values between `0n` and `115792089237316195423570985008687907853269984665640564039457584007913129639936n` but only keep a very very very limited range. In your case filter will always reject the generated values as the chance to fall in your filtering range is barely null (bigUint arbitrary can produce any value with the same proba - more or less true once we stop biasing generated values).
