### ISSUE TITLE
fc.float() and fc.double() sometimes generate values outside the min/max range supplied

### ISSUE THREAD

**Issue by jmacmahon** [dubzzz/fast-check#2086]
## 🐛 Bug Report

Hi again, I have another bug report for you... sorry about that.

The title says it all.

(I guess one of the problems with writing a property-based testing library is that people keep using it to find bugs in itself 😄)

## To Reproduce

```ts
      const arb = fc.integer().chain(min => fc.record({
        min: fc.constant(min),
        someDouble: fc.double({ min })
      }))
      fc.assert(fc.property(arb, ({ min, someDouble }) => {
        return someDouble >= min
      }))
      /*
       *      Error: Property failed after 2 tests
       *      { seed: -453363165, path: "1:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1:1:0:0:0", endOnFailure: true }
       *      Counterexample: [{"min":2,"someDouble":1.9999999999999998}]
       *      Shrunk 33 time(s)
       */

      const arb = fc.integer().chain(max => fc.record({
        max: fc.constant(max),
        someDouble: fc.double({ max })
      }))
      fc.assert(fc.property(arb, ({ max, someDouble }) => {
        return someDouble <= max
      }))
      /*
       *      Error: Property failed after 2 tests
       *      { seed: -1958135361, path: "1:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1:0", endOnFailure: true }
       *      Counterexample: [{"max":-1,"someDouble":0}]
       *      Shrunk 33 time(s)
       */
```

## Expected behavior

I would expect these tests to pass. Floating points can be fuzzy when doing arithmetic operations, but they do have a consistent ordering (excluding `NaN`), so I *think* this is a reasonable expectation.

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            | 2.17.0           |
| node                  | 14.16.0           |
| TypeScript*           | 4.2.4           |

*Only for TypeScript's users

**Comment by dubzzz** [comment]
Actually the behaviour you described above is fully expected given the following (see https://github.com/dubzzz/fast-check/blob/main/documentation/Arbitraries.md#floating-point):

> min? — default: 0.0 — lower bound of the range (included)
> max? — default: 1.0 — upper bound of the range (excluded)

In your first example: min=2 but max defaults to 1 so it generates numbers in range from 1 (excluded) to 2 (included) and 1.999 is within this range.

In your second example: max=-1 but min defaults to 0 so it generates numbers in range from -1 (excluded) to 0 (included) and 0 is within this range.

New versions for double and float will not have this "strange" handling of reversed ranges. Closing the issue as the current behaviour is fully expected on today's versions of float and double.
