### ISSUE TITLE
float arbitrary does not respect min boundary

### ISSUE THREAD

**Issue by EricCrosson** [dubzzz/fast-check#2110]
## 🐛 Bug Report

What I did:

used the following arbitrary

```typescript
fc.float({
  next: true,
  noNaN: true,
  min: new Float32Array([Number.MIN_SAFE_INTEGER])[0],
  max: new Float32Array([Number.MAX_SAFE_INTEGER])[0],
})
```

## Expected behavior

I expect no number less than -9007199254740991 (`Number.MIN_SAFE_INTEGER`) should be generated

## Actual behavior

-9007199254740992 is generated. 

## Updates

The following codec still generates numbers less than the defined min bound

```typescript
fc.float({
  noNaN: true,
  min: new Float32Array([Number.MIN_SAFE_INTEGER])[0],
  max: new Float32Array([Number.MAX_SAFE_INTEGER])[0],
})
```

as does

```typescript
const numberArbitrary = fc.float({
  min: Number.MIN_SAFE_INTEGER,
  max: Number.MAX_SAFE_INTEGER,
})
```

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            |  2.14.0          |
| node                  |   14.15.3         |
| TypeScript*           |  4.3.5          |

*Only for TypeScript's users

**Comment by EricCrosson** [comment]
Ah, this probably has to do with the `accuracy` -- would not be a bug at all. Apologies for the noise!

**Comment by EricCrosson** [comment]
Err -- actually, I think I mis-interpreted my terminal output as an error because of the way I was scrolling through the output :sweat_smile: one of those days!

**Comment by dubzzz** [comment]
You should probably add `next: true` to the options passed to `fc.float`. It will be the default in next major and fixes many issues linked to legacy version.

**Comment by dubzzz** [comment]
With next, the min and max will be properly respected.
