### ISSUE TITLE
Consider using `JsonValue` from `type-fest` as a type for `fc.jsonObject()`

### ISSUE THREAD

**Issue by futpib** [dubzzz/fast-check#2135]
## 🚀 Feature Request

`fs.jsonObject()` and `fs.unicodeJsonObject()` could be better typed as `Arbitrary<JsonValue>` using [`JsonValue` from 'type-fest'](https://github.com/sindresorhus/type-fest/blob/main/source/basic.d.ts#L32)

## Motivation

When writing tests in typescript one is often forced to cast `Arbitrary<unknown>` to `Arbitrary<Something>` just to get tests to compile. Especially with strict tsconfig an typescript linter rules from [`xo`](https://github.com/xojs/eslint-config-xo-typescript).

## Example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgKQM4QHYDUCGAbAVwFM4BfOAMyghDgHIYBPMIgWgqNRjoG4AoUJFiI4MTjAAK1MABpKAYzKVqtOjgBuOdji6t5ACyLyA1rz58KBDPJjBMlABQArdBgBcKV7kJEAlB7RMb2JEPjhwuCgiGAIoDDgXTH5SczEuKQgwBwZ9YFQ4AHdMAB0GOABzCEKiPDw4ACMjHAJUEggKOFYABjo5AG0FADpEjAB5eqcjGAdfOQp5Qa4oYAxymbgAXTkHGDkRuSWV8t84AF4APlCI0UGAEyIiMABRAEcCfAcKZ1dZhJ-k3z8IA

**Comment by dubzzz** [comment]
Hello, thanks a lot for the suggestion. That will definitely be a great thing.

As fast-check does not want to pull to many external dependencies, it would probably be defined inlined in fast-check itself but something like JsonValue is clearly better than unknown.

**Comment by dubzzz** [comment]
On it 🥳 `type-fest` was not an option as the typings are not compatible with TypeScript 3.2. But I found a way to have some compatible with it.
