### ISSUE TITLE
How do I generate values within a command?

### ISSUE THREAD

**Issue by StoneCypher** [dubzzz/fast-check#2136]
## 💬 How do I generate values within a command?

I am using fast-check ❤️ to test a container I'm writing.  In particular, I'm trying to leverage `command`s heavily - push this, pop that, reverse the other, yadda yadda.

It occurred to me that I'm doing something that may be bad, though, and I want to check.

[You can see the full test case here, if you want to](https://github.com/StoneCypher/circular_buffer_js/blob/main/src/ts/tests/circular_buffer.stoch.ts)

Right now I'm using a pretty close to cut and paste of [your `command` mini-tutorial](https://github.com/dubzzz/fast-check/blob/main/documentation/Tips.md#model-based-testing-or-ui-test) for model based testing.

Cool

The thing is, several of the commands I need to run (resizing the container - to what size?  push an element - what value?) need their own random values

It's not clear where to get them?

I've been calling a generator directly but in retrospect that seems likely to completely trash how this is running

so.

```typescript
class PushCommand implements cb_command {

  constructor(readonly value: number) {}    // eslint-disable-line no-unused-vars

  check = (_m: Readonly<CbModel>): boolean => true;  // allowed to push into a full cb because we test overflows

  run(m: CbModel, r: num_cb): void {

    // HELP GOES HERE
    const HowDoISafelyGenerateSomething = ... ;
    // END OF HELP

    const newValue = HowDoISafelyGenerateSomething;

    if (m.length < m.capacity) {  // cb isn't full, so should work
      r.push( newValue );
      ++m.length;
      assert.deepEqual( r.last, newValue );
    } else { // cb _is_ full, so should fail
      assert.throws( () => r.push( newValue ) );
    }

  }

  toString = () => `push(${this.value})`;

}
```

What I have been doing so far, which is probably terrible, is calling this:

```typescript
function whatever(): fc.Arbitrary<unknown> {

  return fc.anything({
    withBigInt        : true,
    withBoxedValues   : true,
    withDate          : true,
    withMap           : true,
    withNullPrototype : true,
    withObjectString  : true,
    withSet           : true,
    withTypedArray    : true
  });

}
```

in this way:

```typescript
    // HELP GOES HERE
    const HowDoISafelyGenerateSomething = whatever();
    // END OF HELP
```

And that appears to work?

except it occurred to me today that I'm probably trashing a bunch of internal state in your tool

So what's the correct way to generate values inside of a `command` please?

**Comment by dubzzz** [comment]
Sorry for the late reply.

From what I can see in the test file you referenced in the issue, the definition of `PushCommand` is ok. Doing something like:
```ts
const PushARandomInteger = fc.integer().map(v => new PushCommand(v));
```

is the way to do it (at least for the moment, I nothing better to do it).

Regarding resizing, at... or any other command working with indexes in the array my current way to do it would be something like:
```ts
const Resizing = fc.nat().map(v => new ResizeCommand(v))

class ResizeCommand implements cb_command {
  constructor(readonly sizeSeed: number);
  toString = () => 'resize(' + this.sizeSeed + ')';
  check    = (_m: Readonly<CbModel>) => true;
  run(m: CbModel, r: circular_buffer<unknown>): void {
    const newSize = this.sizeSeed % _m.length;
    // resize code
  }

}
```

**Comment by dubzzz** [comment]
You can also have a look to the repositories of @TomerAberbach, most of the recent ones are using fast-check with commands.

For instance:
- https://github.com/TomerAberbach/weak-merge/blob/main/test/merge-weak-maps.js
- https://github.com/TomerAberbach/svkc/blob/main/test/index.js
