### ISSUE TITLE
Creating random objects with specific fields.

### ISSUE THREAD

**Issue by ashnur** [dubzzz/fast-check#216]
Is there a way to merge something like
```
fc.record({id: fc.nat()})
```
and
```
fc.object({ key: fc.string(), values: fc.string(), maxDepth: 0})
```

such that I get an arbitrary of a flat object that has a number of random string key:value pairs but always has a numeric id property?

**Comment by dubzzz** [comment]
For the moment there is no such arbitrary natively.

A way to do that would be to do:

```js
fc.tuple(
    fc.record({ id: fc.nat() }),
    fc.object({ key: fc.string(), values: fc.string(), maxDepth: 0})
).map(([hardcodedKeys, randomKeys]) => ({...randomKeys, ...hardcodedKeys}))
```

**Comment by dubzzz** [comment]
Actually it should be an option of `fc.record` as `withDeletedKeys`.

**Comment by ashnur** [comment]
I am ok with the current method, using tuple + map

**Comment by dubzzz** [comment]
Great ;)
