### ISSUE TITLE
Feature request: have equivalent for call/apply signature

### ISSUE THREAD

**Issue by lifeiscontent** [dubzzz/fast-check#2222]
## 🚀 Feature Request

just like for functions you can call or apply them.

it would be nice to be able to do something similar in fast-check.

## Motivation

allows for better composition of tests rather than having to destructure the arguments

## Example

```js
fc.assert(
  fc.properties(
    fc.oneof(
      fc.tuple(fc.string(), fc.integer()),
      fc.tuple(fc.integer(), fc.string())
    ),
      (a, b) => {
          // where a, b are string, number | number, string
          return myFn(a, b);
    }
  )
);
```

## Notes

if there's a way to achieve something like this now, please share! :)

**Comment by dubzzz** [comment]
Hello,

If I understand well the request, the main way to achieve that today is via... destructuring (but it seems you wanted to avoid it):

```js
fc.assert(
  fc.property(
    fc.oneof( fc.tuple(fc.string(), fc.integer()),
    fc.tuple(fc.integer(), fc.string())
    ), ([a, b]) => { // where a, b are string, number | number, string
      return myFn(a, b);
    }
  )
);
```

In general for such cases I replace the tuple by a record so that I get named values and reduce chances of typos or misordering of values.
