### ISSUE TITLE
Just a big thank you!

### ISSUE THREAD

**Issue by gtod** [dubzzz/fast-check#223]
Hey Nicolas (@dubzzz),

Just a note to say you thank you so much for your work on this library!

I have been programming in TS for a year or so but I have not written many frontend tests.  Today I had a need to write some pretty quickly and I found fast-check, read the docs (I think I saw some using Jest, which I also don't know) and also the sort example and then blazed away just writing my tests.

It was straightforward, nothing went wrong, I loved the `fc.pre` and the whole experience was a real pleasure and the tests ended up very neat and tidy.  So thanks again...

Greg

**Comment by dubzzz** [comment]
Thanks a lot for the feedback, I am really glad it can help people :)
