### ISSUE TITLE
The seed argument for runners should properly accept real numbers

### ISSUE THREAD

**Issue by JustinLovinger** [dubzzz/fast-check#224]
Looking at the documentation [here](https://github.com/dubzzz/fast-check/blob/master/documentation/Runners.md). The `seed` argument is specified as a number type. However, floating point numbers are rounded down to an integer. This is particularly problematic if a standard [0, 1) random double is used as a seed.

Ideally, the `seed` argument should accept floating point numbers.

Barring this, the documentation should specify that `seed` must be an integer.

**Comment by dubzzz** [comment]
Indeed the seed must be an integer, I will add this detail into the documentation to make it clearer.

Nonetheless double still work, they are just truncated to integers. Too sad that TypeScript does not have an integer type :(

**Comment by JustinLovinger** [comment]
Raising an exception if seed is not an integer may be better than silently truncating.

**Comment by dubzzz** [comment]
I am not sure that raising an exception would be a good idea:

1/ It breaks the current behavior. Today users can use it with double values knowing that the resulting seed will be truncated. Using `Math.random() * 100` is a correct possible seed having a hundred values
2/ Double are not really causing problems, they are handled correctly with no harm by the framework. I would have been OK to add exceptions if it caused really nasty bugs
3/ Exceptions are costly, they cause deoptimizations of v8, I prefer limiting them to boundaries. The seed is not consumed directly by fast-check but by another library, pure-rand 

In my opinion, updating the Readme adding a note about truncated doubles should be OK for the moment

**Comment by amonks** [comment]
maybe print a warning if `0 <= seed && seed < 1`?

**Comment by dubzzz** [comment]
The trick for number being `seed>0 && seed<1` might be a good idea. I am OK with it (for this range only for the moment). 

It can be added directly into `QualifiedParameters` class on `read_seed` method.

I think the seed could be transformed into:
`(seed * 0xffffffff) ¦ 0` for `seed > 0 && seed < 1`

With that kind of seed, the user has access to the full range of possible seeds. Such changes does not break existing code (except it fixes double seeds in 0, 1) so go for it :)

**Comment by dubzzz** [comment]
@JustinLovinger - The feature has been released in fast-check@1.8.0, you may have a look to [CHANGELOG](https://github.com/dubzzz/fast-check/blob/master/CHANGELOG.md) if you want to check the other features that have been released
