### ISSUE TITLE
Runners with a given seed and path can run more times than claimed

### ISSUE THREAD

**Issue by JustinLovinger** [dubzzz/fast-check#225]
Despite the runner claiming that it runs once and shrinks 0 times, it can actually run several times.

For example:

```js
const fc = require('fast-check');

fc.assert(fc.property(fc.nat(), fc.nat(), (x, y) => {
    console.log('start');
    return x < y + 1000000;
}), { seed: 1539977860329, path: "6:1:0:0:0:0:0:0:2:3:7:10:12:13:15:17:19:16:16" });
```

Prints:

```
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start

…

Error: Property failed after 1 tests
{ seed: 1539977860329, path: "6:1:0:0:0:0:0:0:2:3:7:10:12:13:15:17:19:16:16" }
Counterexample: [1000000,0]
Shrunk 0 time(s)
Got error: Property failed by returning false
```

Despite claiming that the property fails after 1 test and 0 shrinks, `start` is printed several times.

This makes debugging very difficult, because the user cannot easily log the failing run or drop into an interactive debugger on the failing run. This is exasperated by the last run possibly not being the counterexample.

**Comment by dubzzz** [comment]
Hi @JustinLovinger, 

---

The replay feature provided in fast-check only offsets the starting point of a test. By specifying `{seed, path}` you offset the test for a given `seed` by a given `path`. If you happen to use the `{seed, path}` provided at the end of a failing run to replay a counterexample, your test suite will start with this counterexample first then it will start to shrink it.

So this behaviour is expected.

*I will add a note on this in the Tips section.*

---

Concerning the `failed after X tests` or `Shrunk Y time(s)` the meaning is the following:
- `failed after X tests`: number of tests required before catching the first failing case
- `Shrunk Y time(s)`: the counterexample you have been given is the result of Y shrinks of the original corner case

Most property based testing frameworks are working this way for `X` and `Y`.

For instance, jsverify does the same:

```js
Failed after 4 tests and 0 shrinks. rngState: 8f9fcda76e0418b253; Counterexample: 3; 6;

// While I have:
// - 9 tests executed
// - 4 tests executed to find the first failure (4th run was the failure there)
```

*I will add a note on this in the Runners section.*

---

Regards,
Nicolas

**Comment by JustinLovinger** [comment]
Might I suggest an option for runners that will allow it to run only the given seed and path (counterexample).

For example:

```js
const fc = require('fast-check');

fc.assert(fc.property(fc.nat(), fc.nat(), (x, y) => {
    console.log('start');
    return x < y + 1000000;
}), { seed: 1539977860329, path: "6:1:0:0:0:0:0:0:2:3:7:10:12:13:15:17:19:16:16", onlyPath: true});
```

Which would print:

```
start

…

Error: Property failed after 1 tests
{ seed: 1539977860329, path: "6:1:0:0:0:0:0:0:2:3:7:10:12:13:15:17:19:16:16" }
Counterexample: [1000000,0]
Shrunk 0 time(s)
Got error: Property failed by returning false
```

I think the ability to single out a counterexample is important to allow easy logging and debugging of a counterexample.

I also imagine that, when specifying a `seed` and `path`, most users expect the runner to single out a given counterexample. As opposed to the current behavior where it runs a counterexample and may then continue to run several times. Personally, I believe the above example should be the default behavior when `path` is given, but if you do not wish to change the default behavior, a good tradeoff can be changing the printed options to run only the given counterexample. For example

```
start

…

Error: Property failed after 1 tests
{ seed: 1539977860329, path: "6:1:0:0:0:0:0:0:2:3:7:10:12:13:15:17:19:16:16", onlyPath: true }
Counterexample: [1000000,0]
Shrunk 0 time(s)
Got error: Property failed by returning false
```

P.S. A more general option with the same effect as `onlyPath: true` could be `shrink: false`. However, I would expect it to disable shrinking in all tests, not only when `seed` and `path` are given. This may also be confusing for the user, who may expect `path` to not provide a shrunk counterexample given `shrink: false`.

**Comment by dubzzz** [comment]
Or maybe `stopAtFirstFailure`
