### ISSUE TITLE
Void arbitrary, infinite loop of arb.filter(() => false)

### ISSUE THREAD

**Issue by youngmysteriouslight** [dubzzz/fast-check#2281]
## 🐛 Bug Report

Fast-check has no support of 'void' arbitrary that returns nothing:
1. There is no such predefined arbitrary (that is not a bug)
2. `fc.oneof()` and `fc.constantFrom()` require at least one argument, while `fc.oneof()` with no argument is expected to be void arbitrary (it is not a bug, just inconveniency).
3.  `arb.filter(p)` that is effectively void falls into infinite loop, even when `p` is total (i.e. return `true` of `false` in finite time for every argument) and all the arbitraries on the top level are inhabited.

## To Reproduce

```javascript
const fc = require("fast-check");

const nothing = fc.nat().filter(() => false); // void arbitrary, no instances
// the predicate `() => false` is total

const arb = fc.oneof(fc.constantFrom(1), nothing); // alternative of singleton and void
// `arb` is inhabited with `1`

console.log(fc.sample(arb, 4));
```

## Expected behavior

`[1, 1, 1, 1]` is expected, but the program does not respond.

That behavior is considered to be a bug, because infinite loops in tests must be caused by either tested functions, user functions in arbitraries (e.g. `fc.nat().filter(() => { while (true); })`) or well-documented cases of fast-check functions (e.g. warning about depth constraints for `letrec`)
In more complex cases this kind of behavior may reveal under certain parameters of the runner.

## Your environment

| Packages / Softwares  | Version |
| --------------------- | ---------- |
| fast-check            |   2.17.0   |
| node                  |  14.17.0   |

**Comment by youngmysteriouslight** [comment]
I suppose `Arbitrary.generate` must produce at least one value, that is why there can be no void arbitrary, `fc.oneof` requires some options and `.filter` falls down.

If it is inevitable, a warning must be added to `filter` function, because the described behavior does confuse.

**Comment by dubzzz** [comment]
Hello, 

As there is no void in JavaScript (not returning anything is the same as returning undefined), there is no void in fast-check.

Additionally filter cannot know if the function provided to filter will find a compatible value one day and when so it cannot just stop randomly and say 'void'. There is a point on this subject in `filter` or `fc.pre`. If you want to use a filter that stops earlier and returns 'void' you may want to use `fc.pre`. But it only goes inside the code of the property.

Thanks for the report. The behavior is fully expected and will not be 'fixed' for the moment.

**Comment by youngmysteriouslight** [comment]
Thank you for your answer.

## Concept of void arbitrary

> As there is no void in JavaScript (not returning anything is the same as returning undefined), there is no void in fast-check.

That is another 'void' concept. By 'void' I mean an idempotent of `oneof` and `array` combinators, which has no element to generate, that is, an attempt to generate will fail (either stop and say 'void' or never stop and say nothing).

## The reason why current behavior is claimed to be correct

My guess that every arbitrary must have at least one value to generate seems to be correct.
As I understood, `filter`, `oneof` and other combinators work greedy, they search for a compatible value until they find one.
Than the behavior is fully expected and nothing has to be fixed.

Do I understand your anwer and the concepts of Arbitrary correctly?

## Suggestion

In that case, we shall add this assumptions explicitely to the documentation.
E.g. add
> Warning: ensure that there is at least one value that satisfies the predicate

after ([link](https://dubzzz.github.io/fast-check/classes/Arbitrary.html))
> Be aware that using filter may highly impact the time required to generate a valid entry

## Why I consider it to be an issue (and have considered it to be a bug)

> Additionally filter cannot know if the function provided to filter will find a compatible value one day and when so it cannot just stop randomly and say 'void' (a bit like a `while(predicate) `). 

Yes, it cannot.
Ideally it doesn't have to. In my example, one doesn't need to know whether `nothing` (once or never) generates a value in order to indicate that another alternatives are inhabited. As I understand, it is not the approach of fast-check.

> Thanks for the report. The behavior is fully expected and will not be 'fixed' for the moment.

I have rushed to claim it a bug. It is rather a feature of concepts than a bug of implementation.

Still, the following equivalences (up to distribution, but not an order) were expected to hold:
1. `fc.oneof(...list.filter(p)) ~ fc.oneof(...list).filter(p)` for every total pure `p`
2. `fc.oneof(...list.filter(p), ...list.filter(q)) ~ fc.oneof(...list.filter(x => p(x) || q(x)))` for every total pure `p`, `q`
3. `fc.oneof` has an idempotent
but they do not, and that is confusing.
