### ISSUE TITLE
Unclear How to Generate Array With Specific Kind of Object

### ISSUE THREAD

**Issue by neilchaudhuri** [dubzzz/fast-check#2282]
## 💬 Question and Help

I wrote a Typescript function that takes an array of objects with a `position` (type `number` starting at 1 not 0) field sorted ascending and consecutive (*i.e* 1,2,3 and not 1,3,4), an old position `O`, and a new position `N` and returns a new array with the same properties but with the value moved from position `O` to position `N` (meaning items are shuffled accordingly as needed).

This strikes me as a great place to use PBT, but I am having a lot of trouble figuring out the fast-check API to write this test. Particularly, how do I generate objects with `position` fields and constrain the input array array so that the objects start at position 1 and the positions ascend consecutively?

I couldn't find examples for that address these needs, so if you can point me to something I missed, I would appreciate it.

**Comment by neilchaudhuri** [comment]
This is what I came up with, which I hope is the right idiomatic approach:

```
const arb: Arbitrary<OrganizePositionValues> = fc.integer().filter(i => i >= 0).chain(n => {
        return fc.array(fc.string(), {maxLength: n}).chain(ids => {
            return fc.tuple<number[]>(fc.integer(1, n), fc.integer(1, n)).map(t => {
                return {array: ids.map((id, i) => ({id: id, position: i + 1})), oldPosition: t[0], newPosition: t[1]}
            })
        })
})
```

**Comment by dubzzz** [comment]
Hello @neilchaudhuri,

Not sure to fully get the aim but the arbitrary you wrote is totally right except that you probably don't need the first chain.
If it does what you were looking for, you should probably rewrite it as follow:

```ts
const arb: Arbitrary<OrganizePositionValues> = fc.record({
  oldPosition: fc.integer({min: 1}), // from what I understand from your snippet it can be out of range
  newPosition: fc.integer({min: 1}), // same for this one
  array: fc.array(fc.string()).map(ids => ids.map((id, i) => ({id: id, position: i + 1}))) // it seems it does not have any minimal size, nor real maximal one
})
```

The snippet above does the same as yours but it is more efficient in terms of generator (`maxLength:n` with `n` coming from `fc.integer({min: 1})` could led to really large arrays - up to max safe integer which is illegal in js) but also in terms of shrinks (what happens in case of errors).

It will generate:
- an `array` containing items being strings along with a position starting at 1 and going to `array.length`
- two positions between 1 and max safe integer (probably our of the array from time to time)
