### ISSUE TITLE
Arbitraries/Examples for Solidity/Ethereum types

### ISSUE THREAD

**Issue by julianmrodri** [dubzzz/fast-check#2312]
## 💬 Question and Help

Hi! Im interested in implementing `fast-check` for smart contract testing, allowing me to randomly create values to test different sets of functions and parameters in our smart contracts in Solidity. 

Are there any examples or types that are already prepared for this that I can reuse? (like creating addresses, valid amounts, etc all compatible with Solidity/Eth types). Specifically we are using `ethers.js` in our case.

A possible amount could be `uint256` which max amount is : 2**256 - 1. We have to use a BigNumber library for this and I don't see that being supported in `fast-check` right?

Any help would be appreciated. Would love to be able to use this. Thanks!

**Comment by dubzzz** [comment]
You should probably check `fc.bigUintN(256)` (more details at https://github.com/dubzzz/fast-check/blob/main/documentation/Arbitraries.md#bigint)

**Comment by julianmrodri** [comment]
Thanks. Now I think I found a more complex issue. All tests run in `async` functions, as may operations use `await` (when doing operations agains the blockchain). Is this supported?

**Comment by dubzzz** [comment]
You probably want to do that:

```js
   it.only('Should transfer tokens correctly', async function () {
      await fc.assert(
        fc.asyncProperty(fc.bigUintN(256), async (amount) => {
          // Mint some tokens to the caller contract
          await token.mint(caller.address, amount)

          // Transfer
          await caller.safeTransfer(addr1.address, amount)
          expect(await caller['getBalance(address)'](addr1.address)).to.equal(amount)
          expect(await caller['getBalance(address)'](caller.address)).to.equal(0)
        })
      )
    })
```

**Comment by julianmrodri** [comment]
Thank you very much. That works!

**Comment by julianmrodri** [comment]
I think I have a final question I couldnt find in the docs. In my case because the "state" of the tests persists through the different iterations, do I have a way to kind of reset to a "Default" state (fixture) for each try?

**Comment by dubzzz** [comment]
There is a `beforeEach` method on the property.

**Comment by dubzzz** [comment]
You may want to have a look to 'tip 1' in https://github.com/dubzzz/fast-check/blob/main/documentation/Runners.md#properties

**Comment by julianmrodri** [comment]
> There is a `beforeEach` method on the property.

Yeah, the problem is that my state persists in the blockchain (works like a database) so even if I run the operations in a `beforeEach` they persist, because all this happens in the context of a single test.

So the `beforeEach` and `afterEach` will be run but the transaction remains in the DB. Only a manual cleanup seems to be the solution unfortunately.

**Comment by julianmrodri** [comment]
Ideally I could do the clean-up by resetting the `mocha`/`waffle` context to the one before that single test executed. But couldn't find a way to do that.  Mocking the blockchain is what im doing in the "Model" (yes im doing Model Based testing which is quite suitable for my use case). So my real test needs to be with the actual blockchain.

Do you know if `mocha` provides a way to reset the context of a test which I could trigger in the `afterEach` for example? 

Thanks for all your support!

**Comment by julianmrodri** [comment]
Also @dubzzz  does the `beforeEach` run before EACH command generated?  (in Model Based Testing?) Or it tries different commands together and the `beforeEach` is only ran once in that case? Thanks!
