### ISSUE TITLE
Run async commands in sequence, not parallel (Model Based Testing)

### ISSUE THREAD

**Issue by julianmrodri** [dubzzz/fast-check#2333]
## 💬 Question and Help

Hi, would like to know if there is a way when running Model Based Testing, using `async` commands to setup a way to avoid commands being executed in parallel (when using `maxCommands` > 1). In my case im noticing one command getting intertwined with another and causes inconsistency in the assertions and I would prefer to run them in sequence.

This is how our system behaves an any other type of overlapping between commands would not be realistic. 

Also im using `beforeEach` to cleanup the model and system so if this is executed while other command is running it resets my data and makes current command execution to fail. 

Any advice if this can be achieved would be highly appreciated. Thanks!

**Comment by dubzzz** [comment]
There is an async version dedicated to async commands. You'll need to implement AsyncCommand , run the commands with a asyncModelRun and put everything inside an asyncProperty.

beforeEach and afterEach of asyncProperty can also be async if needed.
