### ISSUE TITLE
Infinite loop during tests in ` test/unit/arbitrary/float.spec.ts`

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#2425]
It seems that there is possibly an infinite loop in ` test/unit/arbitrary/float.spec.ts`. More investigations need to be carried out to find what goes wrong, when and why.

The issue might have been highlighted by recent updates on tests helpers.

**Comment by quinn-dougherty** [comment]
Hi, is there a set of heuristics or debugging tools that you're aware of for diagnosing when we think a shrinker is caught in an infinite loop?

**Comment by dubzzz** [comment]
Not really, I used the debugger for this one
