### ISSUE TITLE
`jsonObject` name is misleading (better name: `jsonValue`)

### ISSUE THREAD

**Issue by futpib** [dubzzz/fast-check#2457]
`jsonObject` name implies `typeof x === 'object'` when in reality it generates any JSON-representable value (`object`, `string`, `number`, `null`).

A better name for this arbitrary would be `jsonValue`.

https://github.com/dubzzz/fast-check/blob/dbf7d08b174857103d73b678fc0031f12de0e812/src/arbitrary/jsonObject.ts#L9-L19

**Comment by dubzzz** [comment]
It would definitely be a good idea 👍
