### ISSUE TITLE
Programmatic access of seed for given test run

### ISSUE THREAD

**Issue by beezee** [dubzzz/fast-check#2470]
## 💬 Question and Help

Hi there. I'm running into an issue where a property is exceeding the timeout for the test runner (jest in my case) - but because the failure doesn't come from "inside the test," I am never shown the seed used to initiate the property run. This makes reproduction next to impossible.

Is there a way I can get access to the current seed inside the property definition so I can just dump to console and guarantee I'll be able to recover it the next time this timeout occurs? Any better approaches to solve this?

**Comment by dubzzz** [comment]
Hello,

There is, at the moment, no way to access the seed inside a property. But there are ways to solve the problem by using: ava-fast-check or jest-fast-check.

In fast-check's test suite, I'm using a trick based on the global configuration of fast-check: I generate a seed outside of fast-check and inject it in all the tests via global configuration.

The best and easiest option is probably *-fast-check packages.
