### ISSUE TITLE
Adding a sequence combinator

### ISSUE THREAD

**Issue by ben-eb** [dubzzz/fast-check#2479]
Hello! 👋 

## 🚀 Feature Request

We've been using this little utility in our code for some time:

```typescript
const sequence = <T>(
    arbitraries: Array<fc.Arbitrary<T>>
): fc.Arbitrary<T[]> =>
    arbitraries.reduce(
        (constantArbitrary, arbitrary) =>
            constantArbitrary.chain((combined) =>
                arbitrary.chain((result) => fc.constant([...combined, result]))
            ),
        fc.constant([] as T[])
    );
```

It's a combinator that can take an array of arbitraries and produce an arbitrary of an array of results. For example, these definitions are equivalent:

```typescript
sequence([ fc.constant(1), fc.constant(2), fc.constant(3) ]);

fc.constant([ 1, 2, 3 ]);
```

## Motivation

This is useful if we want to use the result of an arbitrary to create a pool of values that restrict further arbitraries:

```typescript
const record = (id) => fc.record({
  id: fc.constant(id),
  name: fc.lorem()
});

fc.set(fc.nat())
  .chain(
    ids => sequence(ids.map(record))
  );
```

We're happy with how this works in practice and wondered if it would be something you'd be happy to support here?

Thanks! 👍

**Comment by dubzzz** [comment]
Hello 👋,

If I understand it well `sequence` is more or less `tuple`.

From my understanding, `sequence` could be written as follow:
```ts
function sequence(arbs) {
  return tuple(...arbs);
}
```

Contrary to a chain-based implementation the tuple-based will preserve all the shrinking capabilities of the source arbitraries.

Is `tuple` similar to `sequence`? Or did I miss something?

Regards,
Nicolas

**Comment by ben-eb** [comment]
@dubzzz Wow, that's awesome! I've refactored everything to `fc.tuple` and everything works like a dream. Thank you! 👍
