### ISSUE TITLE
Incorrect example in Getting Started

### ISSUE THREAD

**Issue by pandanoir** [dubzzz/fast-check#2511]
## 🐛 Bug Report

The example in [Getting Started page](https://dubzzz.github.io/fast-check.github.com/#getting-started) is incorrect.

```
for (let idx = 1 ; idx < sortedArr.length ; ++idx)
  if (sortedArr[idx - 1] <= sortedArr[idx])
    return false;
``` 

The comparison in the condition is reverse. It should be `sortedArr[idx - 1] > sortedArr[idx]`.

**Comment by dubzzz** [comment]
Thanks a lot for the report, fix submitted should be re-deployed pretty soon
