### ISSUE TITLE
Model-Based Testing: not possible to generate initial state asynchronously

### ISSUE THREAD

**Issue by maciejmyslinski** [dubzzz/fast-check#252]
This is a feature request.
Currently, the first argument passed to `fc.asyncModelRun` cannot return `Promise`.
This is unfortunate when you want to render some UI as a real model in an async way.

**Comment by dubzzz** [comment]
Fixed in 1.8.1

**Comment by dubzzz** [comment]
Can you confirm it works with this version?

**Comment by dubzzz** [comment]
Issue #248

**Comment by maciejmyslinski** [comment]
yaaas! The most recent version fixes this issue, thank you! 🤗
