### ISSUE TITLE
Method to create an array of records with 2 date properties in chronological order

### ISSUE THREAD

**Issue by mishabruml** [dubzzz/fast-check#2536]
## 💬 Question and Help

Hey,

Looking to create an array of records:

```typescript
{
   startDate: Date
   endDate: Date
   ...some more (irrelevant) properties
}
```

I want the resulting array of records to be in chronological order by startDate, where the startDate of array[i+1] is the endDate of array[i], and the duration (difference between start and end date) to be random number of days (between some limits). This would in effect produce a timeline of startDate, endDate, startDate, endDate, startDate and so on

Can this be done without `array.sort()`?

I have tried to tackle this in a number of different, and complicated ways, but am yet to find a "perfect" and simple solution. Interested to see what you can come up with! Thanks!

**Comment by dubzzz** [comment]
Hi @mishabruml,

Sorry for the delay, I totally missed the issue you opened.
I think the best and only way today it to sort the array right after.

I'd write the arbitrary as follow:
```ts
const dateRangeArbitrary = fc.record({
  date1: fc.date(),
  date2: fc.date(),
})
  .map(({date1, date2}) => date1 < date2 ? {startDate:date1, endDate: date2} : {startDate: date2, endDate: date1});

const sortedArrayOfRanges = fc.array(dateRangeArbitrary)
  .map(ranges => [...ranges].sort((r1, r2) => r1.startDate - r2.startDate)); // using [... to clone the array and not alter the source
```
