### ISSUE TITLE
Best practice for doing multiple assertions on the same property?

### ISSUE THREAD

**Issue by leonvdb** [dubzzz/fast-check#2650]
## 💬 Question and Help

Hey there! 
I am new to fast-check and have a question on how to best do multiple assertion on the same property data.

Take this example: 

_From fast-check examples ([link](https://github.com/dubzzz/fast-check/blob/main/example/001-simple/sort/main.spec.ts))_
```
fc.configureGlobal({ numRuns: 20 })

describe('sort', () => {
  it('should have the same length as source', () => {
    fc.assert(
      fc.property(fc.array(fc.integer()), (data) => {
        expect(sort(data)).toHaveLength(data.length);
      })
    );
  });

  it('should have exactly the same number of occurences as source for each item', () => {
    fc.assert(
      fc.property(fc.array(fc.integer()), (data) => {
        const sorted = sort(data);
        expect(_.groupBy(sorted)).toEqual(_.groupBy(data));
      })
    );
  });

  it('should produce an ordered array', () => {
    fc.assert(
      fc.property(fc.array(fc.integer()), (data) => {
        const sorted = sort(data);
        for (let idx = 1; idx < sorted.length; ++idx) {
          expect(sorted[idx - 1]).toBeLessThanOrEqual(sorted[idx]);
        }
      })
    );
  });
});
```

You can see that the arbitrary definition is the same in each of these assertion (`fc.array(fc.integer())`). 
With `numRuns` set to 20 and 3 separate assertions it means that `data` will be generated 60 different times. 

However as the generated `data` will be similar in each assertion I wouldn't mind at all to do my validations on the 20 same data values and save the time that it takes to generate the other 40.

I want to have only a single validation in each it() statement of course. Unless I start putting it() statements inside `fc.assert` (which I guess is not really recommended in the docs anywhere and creates very messy output), I don't see any good way to achieve this. 

I can think of alternative ways to achieve this by separating the generation of `data` and doing the actual validation outside of `fc.assert()`, but then this does nothing except for providing me with different data values to validate with. (No fast-check output at all) 

Does anyone have a good way of solving this or is there no way to avoid regenerating `data` for each separate validation? 
What if the arbitrary is more complicated (more expensive to generate) and you want to do even more validations on it? 
Will `numRuns * timeToGenerateData * numberOfValidations` scale well? 

Thanks for any advice :)

**Comment by dubzzz** [comment]
Hey @leonvdb,

As of today, the recommended approach is: _one `fc.assert` per test_ or more precisely something like:

```ts
test("should check a", () => {
  fc.assert(
    fc.property(..., () => {
      // one assertion or more precisely one test
    })
  })
});
test("should check b", () => {
  fc.assert(
    fc.property(..., () => {
      // one assertion or more precisely one test
    })
  })
});
```

They are multiple reasons behind this one:
- it makes reduction of errors better: the `fc.assert` will only deal with one kind error so the reported error will be for this case only
- error reporting is better for test frameworks
- overhead of generating values is considered negligible (overall) compared to the execution of the check itself or the overhead of the test framework itself: regarding this one I'll do some measurements and come back to you with what I measured on different projects I have and using fast-check

Meanwhile, if you want not to spend too much time in fast-check runs, I highly recommend you to use: `fc.configureGlobal({ interruptAfterTimeLimit: 4000 /* max time spent in fast-checkf or one fc.assert*/ })` (documented in https://github.com/dubzzz/fast-check/blob/main/documentation/Tips.md#setup-global-settings and https://github.com/dubzzz/fast-check/blob/main/documentation/Tips.md#avoid-tests-reaching-the-timeout-of-your-test-runner).

The only alternative I'd have to gather several tests together would be to use:
```ts
function itFastCheck(name: string, fun: () => void): void {
  try {
    fun(); // or Promise<void> + await for async code
  }
  catch (err) {
    throw new Error(`Test: ${name} failed with:\n${err}`);
  }
}
// and use itFastCheck within your fc.assert with something like:
fc.assert(
  fc.property(fc.array(fc.integer()), (data) => {
    itFastCheck(
      'should have the same length as source',
      () => expect(sort(data)).toHaveLength(data.length));
    itFastCheck(
      'should have exactly the same number of occurences as source for each item',
      () => {
        const sorted = sort(data);
        expect(_.groupBy(sorted)).toEqual(_.groupBy(data));
      });
  })
);
```

I'll come back to you with some measurements of the impact of fast-check measured on real life code examples.

**Comment by dubzzz** [comment]
Here are some performance measurements I did on two projects using fast-check:

- on fast-check itself, we have 608 property based tests and here is how time goes:
  - 1.8% generating random values,
  - 97.7% user code of the property,
  - 0.4% fast-check running some internals
 
 - enterprise codebase with property based testing mostly used to cover some critical parts of the code:
   - 27% generating random values,
   - 71% user code of the property,
   - 1% fast-check running some internals

In the second case, I may have to investigate further which properties cause such a huge time in "generating random values" case. In the measurements I extracted, there weree some very slow properties that probably are not generating values properly (relying to much on filter for instance).

I have a third case I'll cover with the very same measurements so that we will get a more comprehensive picture of the question "how costly is it to generate the values?". Anyway, from fast-check point of view, the aim will always be to make it as small as possible and help users not to fall into cases with high performance costs.

**Comment by dubzzz** [comment]
I just did the same measurements on the project https://github.com/dubzzz/advent-of-pbt-2021. Here are the results:

If we consider the global time taken cross tests:

- generating values is responsible for 5,30% of the time
- running the predicate code for 93,12%
- the overhead of the framework not linked to generation of values is 1.56%

If we consider the impact by scaling all the tests to the same basis:

- generating values is responsible for 22,60% of the time
- running the predicate code for 69,13%
- the overhead of the framework not linked to generation of values is 8,26%

_In previous run if test 1 took 1 minute and test 2 took 2 hours, then the percentage would mostly have been driven by test 2. In this new kind of measurement we compute the percentages test by test and then average them altogether._

**Comment by dubzzz** [comment]
Closing the issue for the moment, as there was no update for a while
