### ISSUE TITLE
Way to create an array of records from a constant array where records are unique by property

### ISSUE THREAD

**Issue by mishabruml** [dubzzz/fast-check#2711]
## 💬 Question and Help

Hi, struggling to figure out how to do this:

Possible keys  `[a, b, c]`

```ts
const fooKeys = ['a', 'b', 'c'];
const foo = fc.record({ key: fc.constantFrom(fooKeys), value: fc.nat() });

const arrayOfFoo = fc.array(foo);

const anotherArrayOfFoo = fc
    .tuple(fc.subarray(fooKeys), fc.nat())
    .map(([keys, value]) => keys.map((key) => ({ key, value })));
```

the first approach `arrayOfFoo` means that `value` is generated each time, which is desired, but `key` may suffer duplicates (undesired)

the second approach `anotherArrayOfFoo` means that we are guaranteed to have only 1 or less of each key in the array (desired) but `value` is the same for each record

Is there a way to combine the approaches to achieve an array of foo records where each `key` appears only 1 or 0 times, and `value` is a unique `nat()` for each record?

**Comment by DavidTimms** [comment]
This seems to work, but it isn't pretty. Because of the constraints on the type of `fc.tuple`, I've had to use a type-assertion. There may well be a more elegant solution, but I don't see it right now.

```ts
const fooKeys = ['a', 'b', 'c']

const arrayOfFoo = fc.subarray(fooKeys).chain(keys => {
  if (keys.length === 0) {
    return fc.constant([])
  } else {
    const fooRecords = keys.map(key =>
      fc.record({ key: fc.constant(key), value: fc.nat() })
    )
    return (fc.tuple as any)(...fooRecords)
  }
})
```

**Comment by dubzzz** [comment]
My recommended approach would be:

```ts
const fooKeys = ['a', 'b', 'c'];
const foo = fc.record({ key: fc.constantFrom(fooKeys), value: fc.nat() });
const arrayOfFoo = fc.set(foo, { compare: { selector: v => v.key }, maxLength: fooKeys.length });
```

In the recommended approach, `maxLength` is obviously optional but it gives a clear hint to set to avoid it from doing unneeded computations. Compared to the `chain`-based approach suggested by @DavidTimms it will be more efficient for shrinking.

**Comment by mishabruml** [comment]
thank you! looks great. I didn't know about the compare function so that is awesome, thanks

**Comment by dubzzz** [comment]
Closing, at it seems that the issue has been fixed
