### ISSUE TITLE
Large number of property runs leads to timeouts in Mocha

### ISSUE THREAD

**Issue by amw-zero** [dubzzz/fast-check#2721]
The problem I'm running into is that when large values are given to the `{ numRuns: n }` parameter to `fc.assert`, the test in Mocha fails with this error:

```
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

I didn't open this up as a bug because this is a Mocha-specific problem, but one of the main ways to get value out of property based tests is to run them for a long time on many inputs. I like to set the `numRuns` value very high and let the tests run for hours sometimes. Is there some trick for getting this to work? Or is Jest more widely supported?

To reproduce, run the following test in Mocha. This is the example on the Github README with `numRuns` set to 1,000,000:

```
import fc from "fast-check";

// Code under test
const contains = (text, pattern) => text.indexOf(pattern) >= 0;

// Properties
describe('properties', () => {
  // string text always contains itself
  it('should always contain itself', () => {
    fc.assert(fc.property(fc.string(), text => contains(text, text)));
  });
  // string a + b + c always contains b, whatever the values of a, b and c
  it('should always contain its substrings', () => {
    fc.assert(fc.property(fc.string(), fc.string(), fc.string(), (a,b,c) => {
      // Alternatively: no return statement and direct usage of expect or assert
      console.log("body")
      return contains(a+b+c, b);
    }),
    { numRuns: 1000000 }
    );
  });
});
```
Output:

```
    1) should always contain its substrings


  1 passing (6s)
  1 failing

  1) properties
       should always contain its substrings:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by dubzzz** [comment]
Hello,

You may probably be interested by this part of the documentation. It gives some ways to prevent such problems:
https://github.com/dubzzz/fast-check/blob/main/documentation/Tips.md#avoid-tests-reaching-the-timeout-of-your-test-runner

```ts
fc.configureGlobal({
  interruptAfterTimeLimit: 4000, // Default timeout in Jest 5000ms
  markInterruptAsFailure: false, // When set to false, timeout during initial cases will not be considered as a failure
});
```

I used something close to that kind of configuration on the repository of my company. It prevents property based tests to take too long, to make test runner timeout... but keeps the strength of property based by only limiting the number of runs for slow machines and slow tests.

**Comment by dubzzz** [comment]
@amw-zero Did my suggestion help?

**Comment by amw-zero** [comment]
I ended up just setting the Mocha test case timeout. I don’t know why I was hesitant to increase it at first, but I think it’s fine. If a large number of runs are desired (and that’s generally what I like to do), the timeout of the test case simply has to be increased to account for that.

Once I did that I haven’t ran into any problems, so I didn’t look to tweak fast-check any farther. Thanks.
