### ISSUE TITLE
Sampling a property throws an error inside fast-check: "this.arb.withBias is not a function"

### ISSUE THREAD

**Issue by nth-commit** [dubzzz/fast-check#2736]
## 🐛 Bug Report

I want to be able to change the assert function to a sample and see what values might be input into my test. 

However, when I sample a property, I get the following error:

```
    TypeError: this.arb.withBias is not a function

      45 |
      46 | test('reproduction', () => {
    > 47 |   fc.sample(fc.property(fc.integer(), () => {})).forEach(console.log)
         |      ^
      48 | })
      49 |

      at ConverterToNext.generate (node_modules/fast-check/lib/check/arbitrary/definition/ConverterToNext.js:33:55)
      at Property.generate (node_modules/fast-check/lib/check/property/Property.generic.js:28:32)
      at node_modules/fast-check/lib/check/runner/Tosser.js:9:28
      at node_modules/fast-check/lib/check/runner/Sampler.js:26:62
      at mapHelper (node_modules/fast-check/lib/stream/StreamHelpers.js:19:15)
          at mapHelper.next (<anonymous>)
      at Object.sample (node_modules/fast-check/lib/check/runner/Sampler.js:33:16)
      at Object.<anonymous> (test/connectDisconnectModel.test.ts:47:6)
```

## To Reproduce

`fc.sample(fc.property(fc.integer(), () => {})).forEach(console.log)`

## Expected behavior

Doesn't throw, prints out all the delicious generated parameters.

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            |  2.22.0          |
| node                  | 16.3.0           |
| TypeScript*           |  4.5.5          |

*Only for TypeScript's users

**Comment by nth-commit** [comment]
This seems to be a workaround:

```typescript
const property = fc.property(fc.integer(), () => {})
// @ts-ignore
property.withBias = () => property

fc.sample(property, {}).forEach(console.log)
```

So either:
- Properties needs a no-op implementation of `withBias`
- Properties dispatches any `withBias` calls to all the input generators
- `ConverterToNext.generate` checks for the existence of a `withBias` method before trying to call it

**Comment by dubzzz** [comment]
Woups this is indeed not expected. Good catch 😱

**Comment by dubzzz** [comment]
Still haven't checked it further, but it's in my radar

**Comment by dubzzz** [comment]
Will be fixed with v3

**Comment by dubzzz** [comment]
Fixed in v3
