### ISSUE TITLE
The signature and async behavior of assert should be clarified

### ISSUE THREAD

**Issue by gibson042** [dubzzz/fast-check#2749]
##  Bug Report

https://dubzzz.github.io/fast-check/index.html#assert says that `assert` returns a promise and "Has to be awaited", but [actual behavior](https://github.com/dubzzz/fast-check/blob/350d517/src/check/runner/Runner.ts#L196-L200) seems to be more nuanced—it returns a promise only if the property being tested is async, but otherwise finishes synchronously and returns undefined.

### Synchronous
```sh
$ node -e 'const fc = require("fast-check");                                                       
  let count = 0;
  const result = fc.assert(
    fc.property(fc.nat(), n => { count++ })
  );

  console.log(
    `${count} invocations before fc.assert returned ${result}`
  );
  Promise.resolve().then(
    () => console.log(`${count} invocations at end of turn`)
  );

  const then = result && result.then;
  if (typeof then === "function") {
    then.call(result,
      v => console.log(`${count} invocations at resolution`),
      err => console.error(err)
    );
  }'
100 invocations before fc.assert returned undefined
100 invocations at end of turn
```

### Asynchronous
```sh
$ node -e 'const fc = require("fast-check");
  let count = 0;
  const result = fc.assert(
    fc.asyncProperty(fc.nat(), n => { count++ })
  );

  console.log(
    `${count} invocations before fc.assert returned ${result}`
  );
  Promise.resolve().then(
    () => console.log(`${count} invocations at end of turn`)
  );

  const then = result && result.then;
  if (typeof then === "function") {
    then.call(result,
      v => console.log(`${count} invocations at resolution`),
      err => console.error(err)
    );
  }'
0 invocations before fc.assert returned [object Promise]
1 invocations at end of turn
100 invocations at resolution
```

## Expected behavior

Documentation should accurately describe behavior, which should be possible by editing comments in [Runner.ts](https://github.com/dubzzz/fast-check/blob/350d517/src/check/runner/Runner.ts#L153-L194) (and possibly just reordering, documentation appears to be derived from the first signature).

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            | 2.22.0     |
| node                  | 16.10.0    |

**Comment by dubzzz** [comment]
Opened to suggestions. Please feel free to open a PR so that we can discuss on it

**Comment by dubzzz** [comment]
Normally the return type is either a `void` when using `property` or `Promise<void>` when using `asyncProperty` (if you use TypeScript). The last case handles the indeterminated state of a property not being explicitly declared as sync or async at compile time.
