### ISSUE TITLE
Cannot find name 'bigint'

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#277]
When launching `tsc` with the latest version of fast-check I get:

```
node_modules/fast-check/lib/random/generator/Random.d.ts:42:34 - error TS2304: Cannot find name 'bigint'.

42     nextBigInt(min: bigint, max: bigint): bigint;
```

On old versions of TypeScript

**Comment by dubzzz** [comment]
With TypeScript 3.1

**Comment by ashnur** [comment]
Drop TS?

**Comment by ashnur** [comment]
Or maybe something like this https://github.com/GoogleChromeLabs/babel-plugin-transform-jsbi-to-bigint ?

**Comment by dubzzz** [comment]
I thought about JSBI solution, but I prefer not having an additional dependency just for one arbitrary that requires to be polyfilled for 'old' node versions (they will be old soon).

It is strange that TypeScript has not forecasted such problems. I think there might be a way to do that. The feature was not supposed to break the API and I am pretty sure that the compilation issue only appears with very specific tsconfig (I did try that manually when I developed the feature without the issue).

**Comment by dubzzz** [comment]
Issue looks very similar to https://github.com/vfile/vfile-message/issues/3

The suggested flag might be a good workaround if there is no better way :/

`"skipLibCheck": true`

**Comment by dubzzz** [comment]
io-ts experienced a similar issue with `unknown`, I will try to find a workround like they did

More: https://github.com/gcanti/io-ts/issues/228

**Comment by dubzzz** [comment]
Just published https://www.npmjs.com/package/bigint-as-any-ts

**Comment by dubzzz** [comment]
Closing the issue, possible fixes are:

1- **Move to TypeScript >=3.2**

2- **Skip lib checks**

Add `"skipLibCheck": true` in `tsconfig.json`

3- **Import a polyfill for type bigint**

You can use https://www.npmjs.com/package/bigint-as-any-ts

```bash
npm install -d bigint-as-any-ts
```

Then before starting your test:

```typescript
import "bigint-as-any-ts";
// other imports here
```

4- **Write your own polyfill**

Add the following snippet before starting your test:

```typescript
declare global {
  type bigint = any;
}
// other imports here
```

**Comment by ashnur** [comment]
I personally do not gain anything from TypeScript, so for me the invention and spread of use of TypeScript is one of the worst things that happened lately. Doubled the complexity of all builds, everything moves slower, has more issues, there are more compiler to compile the same code to the same targets differently ... not fun. :)

**Comment by shelbykauth** [comment]
Uh... I'm using Typescript 4.1.3 (installed today), and I'm getting the `Cannot find name 'bigint'` error everywhere.
