### ISSUE TITLE
Better support for deno

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#2781]
## 🚀 Feature Request

Related to https://github.com/dubzzz/fast-check/issues/2779

## Motivation

Full support for deno could be a plus, we would need to dig a little bit to see how to bring such supports into fast-check (and pure-rand at the same time).

**Comment by moodmosaic** [comment]
Perhaps support for deno is good enough. Here's what @LNow ended up doing: https://github.com/LNow/testing-example/pull/2/commits/1b3758e033e2a08d11bda217ed3203e17b326ecf
