### ISSUE TITLE
`readConfigureGlobal()` is typed as being able to return undefined

### ISSUE THREAD

**Issue by TomerAberbach** [dubzzz/fast-check#2825]
## 🐛 Bug Report

It looks like [`readConfigureGlobal()` is typed as returning `GlobalParameters | undefined`](https://github.com/dubzzz/fast-check/blob/main/src/check/runner/configuration/GlobalParameters.ts#L118), but from what I can tell it's not possible for the global parameters to be undefined. The [parameters start out as an empty object](https://github.com/dubzzz/fast-check/blob/main/src/check/runner/configuration/GlobalParameters.ts#L5) and can only be set to a [non-undefined `GlobalParameters`](https://github.com/dubzzz/fast-check/blob/main/src/check/runner/configuration/GlobalParameters.ts#L109) or [reset back to an empty object](https://github.com/dubzzz/fast-check/blob/main/src/check/runner/configuration/GlobalParameters.ts#L128).

## Expected behavior

I would expect the return type of `readConfigureGlobal()` to be `GlobalParameters`.

**Comment by dubzzz** [comment]
Good catch, there is indeed probably no reason to have the undefined (there was possibly one in the past when I relied on window/global)

**Comment by dubzzz** [comment]
As the fix is a one-liner you more or less already wrote in the content of this issue, you probably want to open the PR. Otherwise I could do it, but definitely you already did all the work.
