### ISSUE TITLE
Add a timeLimit parameter 

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#286]
The addition of `fc.commands` and `fc.asyncModelRun`, in recent releases of fast-check, makes it possible to use fast-check against UI with Selenium for instance. However, those UI tests can be very long in case they encounter a failure. Indeed the shrinking might be tricky because iteration on UI is slow. 

In parallel to an effort to increase velocity of the shrinker of commands #284 (on it but no breakthrough for the moment), this ticket aims to add a `noStartAfterTime` flag into `fc.assert` and `fc.check`. 

Expected behaviour of the flag:
- Not set: the run can take as long as it needs to converge
- Positive integer: once this number of milliseconds has been passed, no more property execution will start (already started ones have to end). It should stop both shrinker and classical execution

Given that new flag, one should be able to write the following:

`fc.assert(prop, { numRuns: Number.MAX_SAFE_INTEGER, noStartAfterTime: 60000 }))`

Which will ask fast-check to test new entries for 60s, no matter the number of runs it takes.

**Comment by JustinLovinger** [comment]
The flag name is confusing to me. Something like `timeLimit` or `maxTime` might be more clear. Or even something like `maxMilliseconds`, so the format of the time is obvious.

**Comment by dubzzz** [comment]
It will not really be the maximal time, but the maximal time after which no new test will start. Flag needs to be explicit with that in mind.

It clearly needs something explicit

**Comment by JustinLovinger** [comment]
I think programmers are generally used to the idea that time limits are approximate.

I admit it took me reading the full description and then a few seconds to realize that `noStartAfterTime` was about how long a test can run. My first thought when reading the issue title was that `noStartAfterTime` would skip a test after some real world time. As in "do not start this test after this time". I think the root problem is that it is not clear what "start" refers to.
