### ISSUE TITLE
Printing fc.Command's toString()

### ISSUE THREAD

**Issue by moodmosaic** [dubzzz/fast-check#2864]
## 💬 Question and Help

In the [example](https://github.com/dubzzz/fast-check/blob/main/documentation/Tips.md#model-based-testing-or-ui-test) I can see that there's a `toString()` defined:

```typescript
class PopCommand implements fc.Command<Model, List> {
  check(m: Readonly<Model>): boolean {
    // should not call pop on empty list
    return m.num > 0;
  }
  run(m: Model, r: List): void {
    assert.equal(typeof r.pop(), 'number');
    --m.num;
  }
  toString = () => 'pop';
}
```

How do you get this (the `toString()` function) printed out in the console when running the tests?

**Comment by moodmosaic** [comment]
Hmm, I guess it'll print only when shrinking(?)

**Comment by dubzzz** [comment]
It'll only be used in case of errors. More precisely, fast-check will only use it if it needs to print the value so mostly if the property failed.

**Comment by moodmosaic** [comment]
Yep, that's what I guessed. Thank you the confirmation. 👍

**Comment by moodmosaic** [comment]
So when I see `[object Object]` it means some of the custom types I'm using have no `toString()` method implemented? E.g.

```
Cargo V1 generated tests
Error: Property failed after 1 tests
{ seed: 1027953230, path: "0:1:1:0:0:0:0", endOnFailure: true }
Counterexample: [[object Object] /*replayPath="ABBA0F:q"*/]
                 ^^^^^^^^^^^^^^
Shrunk 6 time(s)
Got error: Error: Expected ok, got (err u100)
```
