### ISSUE TITLE
How to chain records nicely (spreading, adding a property) / feature request for improvement

### ISSUE THREAD

**Issue by mishabruml** [dubzzz/fast-check#2917]
## 💬 Question and Help
```typescript
type A = {
  foo: boolean;
  bar: string;
  fuzz: number;
};

type B = A & {
  buzz: boolean;
};

const recordA = fc.record<A>({
  foo: fc.boolean(),
  bar: fc.string(),
  fuzz: fc.integer(),
});

const recordB: Arbitrary<B> = recordA.chain((a) =>
  fc.constantFrom({
    ...a,
    buzz: fc.boolean(),
  })
);
```

The above gives an indication of what I am trying to achieve, but doesn't work (due to the fact that `buzz` will yield type error `'Arbitrary<boolean>' is not assignable to type 'boolean'.`

I've solved it like this: 

```ts
const recordB: Arbitrary<B> = fc
  .tuple(recordA, fc.boolean())
  .chain(([a, bool]) =>
    fc.constantFrom({
      ...a,
      buzz: bool,
    })
  );
```

but it doesn't seem that pretty. I'm wondering if there is a better/recommended approach? It would be **awesome** if you could do something like:
```ts
const recordB: Arbitrary<B> = fc.record({ ...recordA, buzz: fc.boolean() });
```

**Comment by waynevanson** [comment]
Here is a combinator for you, hope it helps.

```ts
const intersect =
  <
    A extends Record<string, unknown>,
    B extends Record<string,unknown>
  >(fa: Arbitrary<A>, fb: Arbitrary<B>): Arbitrary<A & B> =
    fc.tuple(fa, fb).map(([a,b]) => Object.assign({}, a, b))
```

**Comment by mishabruml** [comment]
Thanks for that, it looks good, I'll give it a go 😄 

> ```ts
> const intersect =
>   <
>     A extends Record<string, unknown>,
>     B extends Record<string,unknown>
>   >(fa: Arbitrary<A>, fb: Arbitrary<B>): Arbitrary<A & B> =
>     fc.tuple(fa, fb).map(([a,b]) => Object.assign({}, a, b))
> ```

theres a typo in this for anyone reading! It should be 

```ts
const intersect =
  <
    A extends Record<string, unknown>,
    B extends Record<string,unknown>
  >(fa: Arbitrary<A>, fb: Arbitrary<B>): Arbitrary<A & B> => // typo here; should be =>
    fc.tuple(fa, fb).map(([a,b]) => Object.assign({}, a, b))
```

**Comment by dubzzz** [comment]
A bit late for the reply but I'd have gone for the solution suggested by @waynevanson. This is definitely the recommended approach to build such arbitrary today as it works well with shrinking (better than using chain).

**Comment by mishabruml** [comment]
This inspired me to write

```ts
export const extendRecord = <
  A extends object,
  B extends Record<string, unknown>
>(
  record: A,
  arbitrary: Arbitrary<B>
): Arbitrary<A & B> => {
  const arbFromA: Record<string, Arbitrary<A>> = {};

  Object.entries(record).map(([key, value]) => {
    arbFromA[key] = fc.constant(value);
  });

  return intersectRecords(fc.record(arbFromA), arbitrary) as Arbitrary<A & B>;
};
```

Which can be used like so: 
```ts
const aArb = fc.record({ foo: fc.string() });
const bArb = fc.record({ bar: fc.boolean() });
const abArb = aArb.chain((a) => extendRecord(a, bArb));
```

Which may not seem so useful on its own, but becomes particularly useful if you want to map a arbitrary array of record arbitraries
```ts
const arrayOfA = fc.array(aArb);
const arrayOfAB = arrayOfA.chain((arr) =>
  fc.tuple(...arr.map((a) => extendRecord(a, bArb)))
);
```

**Comment by mishabruml** [comment]
@dubzzz would you consider some utility methods based on these functions to allow combining of records? Its a common use-case (in my team, anyway)

**Comment by mishabruml** [comment]
It may not be clear from the examples due to brevity, but these become useful when the records are rich/deep objects with many properties. If object B is an extension of object A in the sense that its exactly the same but just adds one or two properties, it makes sense to combine them functionally rather than write the new arb out by hand 😄

**Comment by dubzzz** [comment]
> would you consider some utility methods based on these functions to allow combining of records?

So far, there is no plan to add built-ins for such usages. I prefer letting them as being the responsibility of the users of the library. The rational behind this choice is: not to extend the scope of the library too much with bunch of utilities. If utilities start to be crucial, they will probably come as a separate package, but so far it is not part of the short term plan for fast-check.

It seems that what you would need is something like:

```ts
type MergedRecords<Ts extends unknown[]> = Ts extends [infer T0, ...infer TOthers] ? T0 & MergedRecords<TOthers> : unknown;
function mergeRecords<Ts extends unknown[]>(...rs: { [K in keyof Ts]: Arbitrary<Ts[K]> }): Arbitrary<MergedRecords<Ts>> {
  return tuple(...rs).map(items => Object.assign({}, ...items))
}
// This typing is not 100% perfect as it does not handle cases in which there is a collision for the attributes defined by each of
// the arbitraries. But it already does a pretty good job. If needed, the thing to update is MergedRecords, it should not really be a &.
```

And you probably want the same for tuples:
```ts
type MergedTuples<Ts extends unknown[]> = Ts extends [infer T0, ...infer TOthers] ? T0 extends unknown[] ? [...T0, ...MergedTuples<TOthers>] : [] : [];
function mergeTuples<Ts extends unknown[]>(...rs: { [K in keyof Ts]: Arbitrary<Ts[K]> }): Arbitrary<MergedTuples<Ts>> {
  return tuple(...rs).map(items => items.reduce((v, acc) => [...acc, ...v], []))
}
```

**Comment by mishabruml** [comment]
thanks 😄

**Comment by mishabruml** [comment]
@dubzzz The `mergeRecords` function I understand, but I'm not quite sure how to use the `mergeTuples` function, could you give an example usage? thanks

**Comment by dubzzz** [comment]
> I'm not quite sure how to use the mergeTuples function, could you give an example usage

Was just thinking of it when I wrote the comment but I don't have any usage for it 😂

**Comment by mishabruml** [comment]
Ah ok!

In reference to my use case of merging an array of (already generated) objects with a new record arbitrary, do you have any suggested method that improves on mapping my `extendRecord` example and spreading into a tuple?

**Comment by waynevanson** [comment]
The pattern I'd recommend is lifting your structures from `A` to `Arbitrary<A>` and composing it from there, like in the intersect example.
