### ISSUE TITLE
Regex arbitrary

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#301]

**Comment by dubzzz** [comment]
Won't do for the moment

**Comment by edobrb** [comment]
Hello, is there a chance this feature will be implemented?

**Comment by edobrb** [comment]
For anyone wondering, it's implemented: https://fast-check.dev/docs/core-blocks/arbitraries/combiners/string/#stringmatching

**Comment by dubzzz** [comment]
Actually by regex arbitrary, I meant something able to generate entities of type regex. But yes, stringMatching is probably the one most of people are looking for
