### ISSUE TITLE
Integrate jest timeouts to @fast-check/jest

### ISSUE THREAD

**Issue by CMCDragonkai** [dubzzz/fast-check#3084]
## 🚀 Feature Request

Jest tests themselves have a timeout. It would be nice if these timeouts that are added into the `testProp` was used for fast check's timeout.

## Motivation

This makes it easier to know that the fast check `interruptAfterTimeLimit` will be always be under the timeout given to the full jest test itself. I suggest that it may need to be the jest timeout minus 1 second.

## Example

```
import { itProp, testProp, fc } from '@fast-check/jest';

describe('', () => {
  itProp('should run too', [fc.nat(), fc.nat()], (a, b) => {
    return a + b === b + a;
  }, 5000);
});
```

The `5000` should then be used for the `interruptAfterTimeLimit`.

**Comment by dubzzz** [comment]
Definitely something to that could be interesting. fast-check's already receives a time-out as part of its options, it could either leverage it to set the one of jest or the opposite.

**Comment by CMCDragonkai** [comment]
If I'm using the jest package, how does the `timeout` and `interruptAfterTimeLimit` work with jest's global default timeout.

Like if `jest.setTimeout(20000);`, then if I use `timeout` that should override it just like if I used `timeout` parameter with the `test` function.

Then if I use `interruptAfterTimeLimit`, does that also override the `jest.setTimeout()`?

**Comment by dubzzz** [comment]
So far: `timeout` and `interruptAfterTimeLimit` of `fast-check` are fully disconnected from `jest.setTimeout()`. What I usually do for projects using both is:

```js
// in jest.setup.cjs
fc.configureGlobal({timeout: 4000});
// alternatively: fc.configureGlobal({timeout: 4000, interruptAfterTimeLimit:4000, markInterruptAsFailure: false});
jest.setTimeout(5000)
```

See https://github.com/dubzzz/fast-check/blob/296cde419382eac6fe257ac4105a893dbdf5cfcc/packages/fast-check/documentation/Tips.md#setup-global-settings

**Comment by dubzzz** [comment]
Probably one of the next feature I'm gonna to tackle
