### ISSUE TITLE
alphanumeric generator generating empty strings

### ISSUE THREAD

**Issue by jasikpark** [dubzzz/fast-check#3169]
## 💬 Question and Help

I'm working on testing a validator that accepts a string starting with a letter followed by alphanumeric characters with fast-check. I have this code:

```ts
 it('should return on true on valid generated inputs', () => {
    const alphanumericChar = fc.mapToConstant(
      { num: 26, build: (v) => String.fromCharCode(v + 0x61) },
      { num: 10, build: (v) => String.fromCharCode(v + 0x30) }
    );
    const letterChar = fc.mapToConstant({ num: 26, build: (v) => String.fromCharCode(v + 0x61) });

    const letters = fc.stringOf(letterChar);
    const alphanumericString = fc.stringOf(alphanumericChar);

    const prometheusMetricArbitrary = fc.record({ start: letters, rest: alphanumericString }).map(({ start, rest }) => {
      if (!/^[a-z|A-Z]+$/.test(start)) {
        throw new Error(`start is messed up: ${start}`);
      }
      if (!/^[a-z|A-Z|0-9]+$/.test(rest)) {
        throw new Error(`rest is messed up: ${rest}`);
      }
      return `${start}${rest}`;
    });

    fc.assert(
      fc.property(prometheusMetricArbitrary, fc.context(), (input, ctx) => {
        ctx.log(`input: ${input}, output: ${validateStatsNamespaceAndSubystem(input)}`);
        expect(validateStatsNamespaceAndSubystem(input)).toBe(true);
      })
    );
  });
  ```

but the assertions in `prometheusMetricArbitrary` are failing w/ empty strings generated..

**Comment by jasikpark** [comment]
```
 it('should return on true on valid generated inputs', () => {
    const alphanumericChar = fc.mapToConstant(
      { num: 26, build: (v) => String.fromCharCode(v + 0x61) },
      { num: 10, build: (v) => String.fromCharCode(v + 0x30) }
    );
    const letterChar = fc.mapToConstant({ num: 26, build: (v) => String.fromCharCode(v + 0x61) });

    // generate a valid prometheus metric
    const prometheusMetricArbitrary = fc
      .record({
        first: fc.oneof(letterChar, fc.constant('_')),
        second: alphanumericChar,
        rest: fc.stringOf(fc.oneof(alphanumericChar, fc.constant('_'))),
      })
      .map(({ first, second, rest }) => {
        return `${first}${second}${rest}`;
      });

    fc.assert(
      fc.property(prometheusMetricArbitrary, fc.context(), (input, ctx) => {
        ctx.log(`input: ${input}, output: ${validateStatsNamespaceAndSubystem(input)}`);
        expect(validateStatsNamespaceAndSubystem(input)).toBe(true);
      })
    );
  });
```

yuh

I needed to require `minLength: 1` for my `stringOf` call lol

ended up specifying the first two chars directly since they're important for the format

**Comment by jasikpark** [comment]
It would be great to have the defaults documented for constraints in the jsdoc comments

**Comment by dubzzz** [comment]
Aren't they already documented? If we check `stringOf` in the documentation generated from the jsdoc we have https://dubzzz.github.io/fast-check/functions/stringOf.html, leading us to https://dubzzz.github.io/fast-check/interfaces/StringSharedConstraints.html. Well the options are documented, but I should agree that I barely never document the `@-defaultValue`. By not documented do you talk about it (the at default)?

**Comment by dubzzz** [comment]
If so, can I ask you to create another issue saying 'add missing documentation for default values in jsdoc' (or similar title) and close this one but reference it into the new one? It would make tracking easier.

**Comment by jasikpark** [comment]
yep, that's more of what i was getting at - having jsdocs for the defaults would be great

i was assuming i would get at least 1 of something out of a particular arb until i realized i needed to constrain it to at least one

**Comment by jasikpark** [comment]
https://github.com/dubzzz/fast-check/issues/3179
