### ISSUE TITLE
Is there a combinator with type `Arbitrary<T>[] -> Arbitrary<T[]>` ?

### ISSUE THREAD

**Issue by tsuberim** [dubzzz/fast-check#326]

**Comment by dubzzz** [comment]
`fc.tuple` or `fc.genericTuple` should fit your needs

**Comment by dubzzz** [comment]
Here are the associated documentations:
- `fc.tuple`: https://dubzzz.github.io/fast-check/index.html#tuple
- `fc.genericTuple`: https://dubzzz.github.io/fast-check/index.html#generictuple

**Comment by tsuberim** [comment]
Thanks
