### ISSUE TITLE
Merge the two documentation pages

### ISSUE THREAD

**Issue by gunar** [dubzzz/fast-check#330]
Documentation currently exists in two places:

1. https://dubzzz.github.io/fast-check/
2. https://github.com/dubzzz/fast-check/tree/master/documentation

Quick-hack would be to just add links to each other.

**Comment by gunar** [comment]
@dubzzz 	what do you think? It's the third time I've had to look for this link :)

**Comment by dubzzz** [comment]
Links towards https://dubzzz.github.io/fast-check/ and https://github.com/dubzzz/fast-check/tree/master/documentation are already available on the README of the project.

Feel free to come with a PR
