### ISSUE TITLE
How to generate one example of an arbitrary?

### ISSUE THREAD

**Issue by lastmjs** [dubzzz/fast-check#346]
I would like to genereate one value from an arbitrary outside of the property function. How can this be done? For example, I might want to use a random string somewhere:

```javascript
function createRandomString() {
  return fc.string().generate();
}
```

I'm not sure how to do that, since the generate function requires a parameter that I'm not sure how to find

**Comment by lastmjs** [comment]
fc.sample! Thanks...

**Comment by dubzzz** [comment]
You can also use `fc.statistics` if you want to extract statistics on the generated values
