### ISSUE TITLE
Document examples feature

### ISSUE THREAD

**Issue by jasikpark** [dubzzz/fast-check#3499]
## 💡 Idea

The "examples" option that can be passed to add seeds / unit tests should be documented more clearly 

## Motivation

I've wanted to de-duplicate my prop tests and my unit tests but I didn't see the Examples example

## Example

reading docs to find the feature

**Comment by dubzzz** [comment]
I added a page dedicated to examples in my new documentation (still on-going). You might find it at: https://fast-check.dev/docs/configuration/user-definable-values/

**Comment by jasikpark** [comment]
thx! those docs look great! want to close this issue now?

**Comment by dubzzz** [comment]
Let's close it if the new page fits your needs. By the way more pages are coming

**Comment by jasikpark** [comment]
yay
