### ISSUE TITLE
@fast-check/vitest cannot find module

### ISSUE THREAD

**Issue by ben-laird** [dubzzz/fast-check#3657]
## 🐛 Bug Report

`vitest-fast-check.js` cannot find an internal module it needs to function. `fast-check` itself works perfectly fine in `vitest`, so I wonder if it's a problem with my own import system. Sorry if this issue isn't relevant currently because `@fast-check/vitest` is so new.

Error:

```sh
Error: Cannot find module '/path/to/project/node_modules/.pnpm/@fast-check+vitest@0.0.2_vitest@0.28.5/node_modules/@fast-check/vitest/lib/esm/internals/TestBuilder' imported from /path/to/project/node_modules/.pnpm/@fast-check+vitest@0.0.2_vitest@0.28.5/node_modules/@fast-check/vitest/lib/esm/vitest-fast-check.js
```

## To Reproduce

Steps to reproduce:

- Run `pnpm i -D @fast-check/vitest` to install
- Create test:

```ts
// ./test/sanity.test.ts
import { fc, test } from "@fast-check/vitest";

test.prop([fc.string()])("Passing sanity test", (s) => {
  const testing = s === s;
  console.log(testing)
};
```

- Run `pnpm test` (which runs `pnpm vitest run`)

## Expected behavior

Library should find file imported from `@fast-check/.../internals/TestBuilder`

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| fast-check                 | ^3.6.3       |
| @fast-check/vitest   | ^0.0.2       |
| node                           | 18.7.0        |
| TypeScript\*              | 4.9.5         |

\*Only for TypeScript's users

**Comment by dubzzz** [comment]
Interesting, I'll check it. In theory, I'm running checks against the final version of the package in the CI but such tests tend to be tricky given the myriad of package managers, bundlers... So there is probably something I missed.

**Comment by dubzzz** [comment]
v0.0.3 on its way! Should be available in a few minutes with a fix for you 😃

**Comment by dubzzz** [comment]
Published!

**Comment by ben-laird** [comment]
Works brilliantly, thanks so much!
