### ISSUE TITLE
Feature request: Pass model to `toString()` in model based testing.

### ISSUE THREAD

**Issue by gruhn** [dubzzz/fast-check#3665]
## 🚀 Feature Request

In "Model based testing", would it be possible to give access to the model in the `toString()` method?

Let's say I want to test a data structure like `Map`. I may have a command for adding entries to the data structure, such as
```typescript
class AddEntryCommand implements Command<...> {
  constructur(
     readonly key : string, 
     readonly value : string
  ) { }

  // ...

  toString() {
     return `addEntry("${key}", "${value}")`
  }
}
```
But what if I also want to have a command for deleting entries? If I implement it like below, I guess it's fairly unlikely that the command is often executed, because the random `key` has to match a previously added random `key`, right?

```typescript
class DeleteEntryCommand implements Command<...> {
  constructur(
     readonly key : string
  ) { }

  check(model) {
     // return false if key doesn't exist in the model
  }

  // ...

  toString() {
     return `deleteEntry("${key}")`
  }
}
```

Instead I could pass a random index `n` to the delete command, and then delete whatever the `n`-th entry in the data structure is (maybe also doing some modulo computation to make sure the index is really in-bounds):
```typescript
class DeleteEntryCommand implements Command<...> {
  constructur(
     readonly n : number
  ) { }

  run(model, real) {
     // get n-th entry from `model` and delete it in both `model` and `real`
  }

  // ...

  toString() {
     return `deleteEntry(${n})`
  }
}
```
But then the error output is less instructive, because it doesn't tell me, which concrete key was deleted. If the `toString()` method would accept the model as an argument, I could derive the key from the index.

I'm very open to alternative solutions though.

**Comment by dubzzz** [comment]
If you want to add a bit more verbosity into the `toString` of your command you may rely on the trick I used for this command: https://github.com/dubzzz/connect-four-react/blob/master/e2e/limited-model/commands/ReopenViaUrlCommand.ts

It basically consists into setting something on the instance itself (aka this) when run gets triggered. Something like:

```
class DeleteEntryCommand implements Command<...> {
  constructor(
     readonly n : number
  ) { }

  run(model, real) {
     this.model = model;
     // get n-th entry from `model` and delete it in both `model` and `real`
  }

  // ...

  toString() {
     return `deleteEntry(${this.model?.blabla})`
  }
}
```

**Comment by gruhn** [comment]
Ahh of course. That’s perfectly sufficient, thanks 🙏

**Comment by dubzzz** [comment]
Closing the issue for now then 👍
