### ISSUE TITLE
Counter example command sequence incorrect

### ISSUE THREAD

**Issue by NotHolst** [dubzzz/fast-check#367]
We have encountered some strange behaviour with the counter example when using the state machine framework.
Testing the counter examples manually did not yield any errors/bugs, which is why we implemented a custom counter example recorder to see if they matched. The output from this test can be seen below.

```
// This is the output from our custom callstack implementation.
CALLSTACK: db.insert({".":""});
db.count();
db.count();
db.remove({".":""});
db.count();

Property failed after 2 tests
...
Counterexample: [INSERT({".":""}),REMOVE({"-":""}),COUNT /replayPath="BBBFbW:q"/]
Shrunk 7 time(s)
Got error: AssertionError [ERR_ASSERTION]: 0 == 1
```

Seemingly this bug is only triggered under very specific conditions, which makes it hard to come up with a minimal example. Therefore it might be easier to pull our repository which generates the error.  The example produces multiple different bugs, hence it might require multiple attemps to get the exact bug. The outputted counter example is always as described above.
https://github.com/igern/Propertybased-Testing-Fastcheck
LokiStateMachine.ts is the file containing the test.

**Comment by dubzzz** [comment]
Hello @NotHolst, 

> Testing the counter examples manually did not yield any errors/bugs

While looking at the code, I detected that one of the commands - `RemoveCommand` - was doing calls to `Math.random` within its `run` method (same issue if it was during the `check`). It makes it undeterministic.

The advice with the current version of fast-check - *no `fc.random()` producer for the moment but might come later* - would be to do:

```ts
class RemoveCommand implements fc.Command<SimpleDb, Collection<any>>{
    record: object;
    constructor(readonly seed: number) { }
    check = (model: Readonly<SimpleDb>): boolean => model.count() > 0
    run(model: SimpleDb, loki: Collection<any>): void {
        this.record = model.data[Math.round(this.seed * (model.count() - 1))]
        model.remove(this.record);
        try {
            loki.findAndRemove(this.record)

        } catch (error) {
            console.log(model.callStack)
            throw error
        }
    }
    toString(): string {
        return `REMOVE(${JSON.stringify(this.record)})`
    }
}

///----

fc.nat().noShrink().map(s => new RemoveCommand(s))
```

For the moment, I am trying to reproduce locally. I'll come back to you later

**Comment by dubzzz** [comment]
I do not reproduce locally. I tried to run your code against the error that was reported by fast-check and it fails (as reported by fast-check).

```ts
// Manual replay: INSERT({".":""}),REMOVE({"-":""}),COUNT
// The following code is equivalent to the error that was reported by fast-check

const model = new SimpleDb();
const real = new loki('loki.json').addCollection('testing');

new InsertCommand({".":""}).run(model, real);
new RemoveCommand(0).run(model, real);
new SizeCommand().run(model, real);

// It throws
```

Concerning the `custom callstack implementation` be aware that fast-check reported an error on `INSERT({".":""}),REMOVE({"-":""}),COUNT` but most of the time it tried many others after. So the associated log is not necessarily the last one.

In order to replay only this case you can do the following (see https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/Tips.md#replay-after-failure-for-commands):
```ts
fc.assert(
  fc.property(
    fc.command(allCommands, {maxCommands: 100, replayPath: /*replayPath from the error logs*/}),
    cmds => {/*your test code*/}
  ), { seed: /*seed from the error log*/, path: /*path from the error log*/, endOnFailure: true }
);
```

**Comment by dubzzz** [comment]
@NotHolst any updates?

**Comment by NotHolst** [comment]
Hello, sorry for the delay.

We followed your advice and setup an example that generates the aforementioned error.
However, when we run the replay after failure the bug is not shown in the console as shown below.

```
Counterexample: [INSERT({".":""}),REMOVE({"-":""}),COUNT// Actual run counter example 
Counterexample: [INSERT({".":""}),REMOVE({".":""}),COUNT // Replay counter example
```

Just to reiterate, the bug is real, LokiJS can't handle removal of entries with a dot in their name. More information in this issue:
https://github.com/techfort/LokiJS/issues/777

The issue we were facing was that the counter-example doesn't actually reproduce the bug. If the counter-example is run in LokiJS it acts as intended, because removing an entry with a dash should not remove an entry with a dot as the key.

```
import * as loki from "lokijs";
var database = new loki('loki.json');

var db = database.addCollection('children');
db.insert({ "." : "" })
db.findAndRemove({ "-" : "" })

console.log(db.count()) // Returns 1
```

The fix suggested did not work as we're still getting incorrect counter example printed

We have updated the GitHub repository to focus more on the issue, and added your fixes and suggestions.

**Comment by dubzzz** [comment]
Hello,
I'll checkout your repo again with latest code to see if I can understand the reason while fast-check fails to replay.
I'll come back to you asap

**Comment by dubzzz** [comment]
@NotHolst Can you confirm the repository with the test is still https://github.com/igern/Propertybased-Testing-Fastcheck?
If so how do you run the tests? `npm install && npm run start` just does not work.

**Comment by Manatho** [comment]
Hey one of the other guys working on the repo, it has been updated so `npm install && npm run start` should work now.

It may take a couple of runs for it to find the bug, took me 4 attempts testing it just now, so the following might pop up first:
```
// My first run:
Counterexample: [INSERT({}),INSERT({}),REMOVE({}) /*replayPath="ADSI:K"*/]

// My second run:
Counterexample: [INSERT({".":0,"":null}),REMOVE({".":0}) /*replayPath="CPR:F"*/]

// My third run
Counterexample: [INSERT({}),INSERT({}),REMOVE({}) /*replayPath="C8F:F"*/]

// My fourth run with the problematic run
Counterexample: [INSERT({".":0}),REMOVE({"-":0}),COUNT /*replayPath="AAAACBAue:VF"*/]
```
If needed the replay run can be found commented in src/lokiStateMachine.ts at lines 115-128, so a simple matter of uncommenting it if you want to check on that.

**Comment by dubzzz** [comment]
Took me a while to find it but I finally have a possible explanation.

Basically when shrinking a scenario some new `RemoveCommand` are newly instanciated (basically when the input changes) but some are re-used (if the input for the constructor is the same).

The resulting error in the log is printed at the end of the execution of the whole test suite. So if the result of `toString` depends on the values encountered during `run` we might not see the actual error at the end of the execution.

In your case, if you re-run `run` of `RemoveCommand` you alter the result of `toString`.

--

_I was hoping that `fc.cloneMethod` would have solved your issue but unfortunately it seems not to work properly with commands today. I need to check this code to understand._

**Comment by dubzzz** [comment]
@NotHolst @Manatho Can you confirm you do not encounter the issue anymore with my PR https://github.com/igern/Propertybased-Testing-Fastcheck/pull/1?

**Comment by NotHolst** [comment]
Yes, the issue is no longer there after the PR, thank you for your help :)
