### ISSUE TITLE
scheduledModelRun not returns counterexample

### ISSUE THREAD

**Issue by krzysztofpniak** [dubzzz/fast-check#3704]
## 🐛 Bug Report

fast-check not transform errors thrown while using scheduledModelRun.

## To Reproduce

Steps to reproduce:
1. open your repo
2. open `examples/005-race/todolist/model-based/AddItemCommand.ts` file and add `expect(1).toEqual(2);` to  the end of `run` function
3. run test

## Expected behavior

I should see standard fast-check error report with seed, and other stuff. Instead, I see plain error returned by jest expect:
```
Error: expect(received).toEqual(expected) // deep equality

Expected: 2
Received: 1
```
if I replace `scheduledModelRun` to `asyncModelRun` it works.

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| fast-check           |  3.7.1  |
| node                 |  18  |

**Comment by dubzzz** [comment]
Seems that I cannot reproduce your issue. Or at least I get reported the correct error on my side:

![image](https://user-images.githubusercontent.com/5300235/233925219-fbcb2867-e106-4411-bd6e-614e988c014e.png)

**Comment by dubzzz** [comment]
Cc @krzysztofpniak I recently (3.8.3 and 3.9.0) fixed issues on this helper. It might solve some of your initial issues.
