### ISSUE TITLE
@fast-check/vitest cannot be imported in TS node16/nodenext resolution

### ISSUE THREAD

**Issue by jakebailey** [dubzzz/fast-check#3718]
## 🐛 Bug Report

Clear and concise description of the bug.

The lack of types mappings for the ESM exports prevents TS from resolving the package, giving:

> Could not find a declaration file for module '@fast-check/vitest'. '.../node_modules/@fast-check/vitest/lib/esm/vitest-fast-check.js' implicitly has an 'any' type.
  There are types at '.../node_modules/@fast-check/vitest/lib/vitest-fast-check.d.ts', but this result could not be resolved when respecting package.json "exports". The '@fast-check/vitest' library may need to update its package.json or typings.ts(7016)

## To Reproduce

Steps to reproduce:

Create a TS project and set module=node16 in tsconfig. Try to import `@fast-check/vitest`.

See also: https://arethetypeswrong.github.io/?p=%40fast-check%2Fvitest%400.0.3 and https://publint.dev/@fast-check/vitest@0.0.3

These tools can help to determine if a package is properly typed / configured.

## Expected behavior

No error.

Likely, you need types entries for the export maps, as well as d.ts emit for the ESM code (right now it's js emit only?)

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| fast-check           | -          |
| node                 | 19.8.1     |
| TypeScript\*         | 5.0.0      |

\*Only for TypeScript's users

**Comment by dubzzz** [comment]
Oups good catch, sorry for the inconvenience. I'll try to send a fix later today.

**Comment by dubzzz** [comment]
Version should be released pretty soon on npm. Just waiting GitHub actions to go back to normal

**Comment by dubzzz** [comment]
Version published 🚀

**Comment by jakebailey** [comment]
Thanks!
