### ISSUE TITLE
Add code sandbox links to the documentation 

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#373]

**Comment by bios21** [comment]
You can use maybe https://npm.runkit.com/fast-check as a start before making your own.

**Comment by mbmaeso** [comment]
I would like to claim this issue. Could you describe what exactly do you want to add as a link? Thank you!

**Comment by Lawrence4code** [comment]
I'd like to work on this, please.

**Comment by dubzzz** [comment]
For the moment I don't exactly know how I want to handle this Ticket. Let's say that the issue is somehow frozen. 

My dreamt solution would be a codesandbox that automatically syncs with code snippets stored within fast-check (in example/). The advantage of this approach is that snippets will always be aligned with fast-check as it will use them directly as non regression test suites.

**Comment by giogonzo** [comment]
> My dreamt solution would be a codesandbox that automatically syncs with code snippets stored within fast-check (in example/)

Just saw this passing by: https://github.com/facebook/react/pull/17241
Looks like it's not public yet, but something to keep in mind for the future

**Comment by CompuIves** [comment]
> My dreamt solution would be a codesandbox that automatically syncs with code snippets stored within fast-check (in example/). The advantage of this approach is that snippets will always be aligned with fast-check as it will use them directly as non regression test suites.

This should be possible with our GitHub import. You can import a repository with path from GitHub, and the sandbox will stay in sync whenever the GitHub changes. An example of this is here:

This repo: https://github.com/reduxjs/redux/tree/master/examples/todomvc
Has this CodeSandbox URL: https://codesandbox.io/s/github/reduxjs/redux/tree/master/examples/todomvc

I think the next step is to find the best way to demo `fast-check`, maybe we could use our test view, or we would create a container project and show the terminal output/

**Comment by dubzzz** [comment]
@CompuIves It's definitely what I'm looking for. As `fast-check` is a test framework the appropriate view would be the test view.

I'll have a look into GitHub import feature

**Comment by dubzzz** [comment]
@CompuIves Thanks a lot for the comment. It drove me towards the `GitHub import` feature of CodeSandbox. I updated my repo to have it properly configured for CodeSandbox.

🎉  It works fine now: https://codesandbox.io/s/github/dubzzz/fast-check/tree/master/example?previewwindow=tests
