### ISSUE TITLE
Adopt better file layouting 

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#387]
One should be able to `import nat from 'fast-check/arbitraries/nat'`. Revamping the file layouting may allow such imports.

For reference: rxjs or MaterialUI are great libs allowing this kind of imports.

**Comment by dubzzz** [comment]
See `exports` field in `package.json` - https://nodejs.org/api/esm.html#esm_package_exports

**Comment by dubzzz** [comment]
_Work in Progress_

- arbitraries
  - numeric
    - _internals_
    - integer
      - _internals_
    - nat
  - string
    - hexa
    - base64
- runners

**Comment by dubzzz** [comment]
Or like ramda:

- arbitrary/
  - _internals/
  - nat
  - integer
  - string
- runner/
  - check
  - assert
  - statistics
- utils/
  - modelRun
  - stringify
  - hash
  - pre

**Comment by dubzzz** [comment]
Circular imports might be detected by https://www.npmjs.com/package/dpdm. It may help to detect wrongly placed files or (in the future) avoid introducing circular dependencies.

**Comment by jasikpark** [comment]
another good example potentially is [lodash](https://github.com/lodash/lodash) / https://www.npmjs.com/package/lodash-es:

`import { at } from "lodash/at";`
