### ISSUE TITLE
Typescript transformers

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#3879]
## 💡 Idea

Transformers might be pretty helpful when users want to magically generate values based on their types. While automatic stuff will not be able to magically infer that two attributes or fields have to follow a set of rules, they can already give a hand on many cases.

Here is a tweet telling about the possible addition of transformers natively in Typescript.

https://twitter.com/andhaveaniceday/status/1658598536160894977?t=CU1WPwNSieJl1RFHOHo0vw&s=19

If we do implement such feature, worth having it into a dedicated package.

**Comment by hsommerlandreason** [comment]
I'm actually doing something similar as a small side project.
Or I'm working on automatically generating runtime checkers/parsers from Typescript definitions. And I have ben literally thinking about automating generating of fest-check generators as well :P

Working with the typescript AST is a bit of a pain in general but it is incredibly doable, this far nothing has been that complicated, there is just a bazzilion different cases to cover.

**Comment by dubzzz** [comment]
Closing for now. Not yet planned on TypeScript's side.
