### ISSUE TITLE
Any plans to introduce stateful property testing?

### ISSUE THREAD

**Issue by anilanar** [dubzzz/fast-check#392]
PropER seems to be the most popular in that arena: https://propertesting.com/book_stateful_properties.html

There seem to be some quickcheck impls too: http://hackage.haskell.org/package/quickcheck-state-machine

Given that many web applications in JS/TS are adopting Elm/Redux architecture, this could be very useful.

**Comment by dubzzz** [comment]
It already exists - see `fc.commands`: https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/Tips.md#model-based-testing-or-ui-test

**Comment by dubzzz** [comment]
Feel free to re-open if it does not fit your proposal
