### ISSUE TITLE
Support for merging of arbitraries into arrays

### ISSUE THREAD

**Issue by silentstormm** [dubzzz/fast-check#3948]
## 🚀 Feature Request

I would like to be able to create multiple arbitraries and merge them into an `Arbitrary<Array<...>>`

## Motivation

This would allow, for example, to create an arbitrary array where **at least** one element matches the user's needs - currently this is only possible with predicates.

## Example

To create an array starting with at least two numbers and ending with at least one string using `fc.concat(...arbs, options?)`:
```ts
fc.concat(fc.array(fc.nat(), {minLength: 2}), fc.array(fc.string(), {minLength: 1}))
// example output: [1, 4, 'asdf'], [385, 9563, 29, 127, 593, ''], [238, 35, 'qwerty', 'uiop', 'lorem', 'wahoo']
```

The results of `fc.concat` could also be shuffled, in this case creating an array with at least one number and string and exactly one boolean:
```ts
fc.concat(fc.array(fc.nat(), {minLength: 1}), fc.array(fc.string(), { minLength: 1 }), fc.boolean(), {shuffled: true})
// example output: [1, 'df', true], [385, false, 7, '', 53, 'fdidhdf'], [true, 238, 35, 'qwerty', 49, 'lorem', 'wah']
```
(shuffle could also be its own function to allow shuffling tuples)

Additionally, either `fc.concat` could have an option to not flatten array arbitraries or there could be another function which does that:
```ts
fc.concat(fc.array(fc.nat()), fc.array(fc.string()), {preserveArrays: true})
// or 
fc.merge(fc.array(fc.nat()), fc.array(fc.string()))
// example output: [[], []], [[1, 4], ['asdf']], [[238, 35], ['qwerty', 'uiop', 'lorem', 'wahoo']]
```

**Comment by dubzzz** [comment]
Hey,

First thanks a lot for your interest in fast-check.

So far, I do not plan to add such built-in helpers natively in fast-check: building them is rather free with the existing arbitraries.

```js
function concat(...arbs) {
  return tuple(...arbs).map(items => items.flat())
}
```

I feel that having them would not provide that much. As users will still have to map them again to something more tailored to their needs. As so far, I want to focus the API on core blocks adding lots of values (complex to build right) I prefer not adding it. At least for now.

**Comment by silentstormm** [comment]
Oh, I guess I didn't get what `.map` does 😅. That makes so much sense though, thanks!
