### ISSUE TITLE
fc.stringOf() does not honor its maximum length constraint

### ISSUE THREAD

**Issue by elefevre** [dubzzz/fast-check#3965]
## 🐛 Bug Report

`fc.stringOf()` does not honor its `maxLength` constraint and defaults to a maximum length of 16 instead.

## To Reproduce

```
let observedMaxLength = 0;
fc.assert(fc.property(
    fc.stringOf(fc.constant("a"), { maxLength: 1024 }), // any value above 16 for maxLength yields the same outcome
    str => {
        observedMaxLength = Math.max(observedMaxLength, str.length);
    }));
console.log({ observedMaxLength }); // always 16, regardless of the number of runs
```

Notes:
- the outcome depends on `minLength` somewhat. For example, `{ minLength: 16, maxLength: 1024 }` yields `{ observedMaxLength: 42 }` and `{ minLength: 42, maxLength: 1024 }` yields `{ observedMaxLength: 93 }`;
- if the `maxLength` configuration is missing, then the observed maximum length is 10; that may or may not be the desired outcome.

## Expected behavior

Some of the generated values should have a length closer to the requested `maxLength`.

## Your environment

| Packages / Softwares | Versions |
| -------------------- | ---------- |
| fast-check           |  3.7.0 |
| node                 |  18.15.0  |
| TypeScript         |  4.7.4  |

**Comment by dubzzz** [comment]
As documented on [stringOf::max](https://fast-check.dev/docs/core-blocks/arbitraries/combiners/string/#stringof), there are some specific things to know with the max: the max is what the framework is allowed to generate at max, it does not mean it has to do so. If you want to reach this max you can play with the size, more details [here](https://fast-check.dev/docs/configuration/larger-entries-by-default/#size-explained) or just pass `size: 'max'` next to the `maxLength`.

**Comment by elefevre** [comment]
Oh, hm. Thanks! Not easy to wrap my head around the explanation, but I see what I should do now.
I do appreciate your fast response and the detailed documentation! 🙏
