### ISSUE TITLE
Using filter fails to find obvious edge case?

### ISSUE THREAD

**Issue by MarcCoquand** [dubzzz/fast-check#398]
## 💬 Question and Help
Hello, I am testing fast-check with a bridge control system. So we have one constant of max allowed cars and one variable which is amount of cars on the bridge:
```
const Car = require('./car');
test('Car MLOut', () => {
    fc.assert(
        fc.property(fc.nat().filter(n => n <= Car.MAX_CARS), n =>
            expect(Car.MLout(n) <= Car.MAX_CARS).toBe(true)
        )
        , { verbose: true, numRuns: 1000000 });
});
```
where MAX_CARS is 50 for this purpose and the function `MLout = n => n+1`. Even after 1000000 cases fast-check fails to find the edge case that if n=50 then it will fail. Am I doing this correctly?

**Comment by dubzzz** [comment]
Hello @MarcCoquand,

Actually you should prefer `fc.nat(Car.MAX_CARS)` over `fc.nat().filter(n => n <= Car.MAX_CARS)`.

The reason why it does not found a corner case is the following:

`fc.nat().filter(n => n <= Car.MAX_CARS)` means generate any integer value between `0` and `2 ** 31 -1`. By default, fast-check tends to favour small integers over large ones for the first runs so for first runs there is a high probability to generate integers within `0` to `30 = Math.floor(Math.log(0x7fffffff) / Math.log(2))` (small integers will still be favoured in later runs but with less chance to be selected).

If you run `fc.sample(fc.nat().filter(n => n <= Car.MAX_CARS))` you might see that barely all your values are within the small integers range.

Replacing your generator by `fc.nat(Cars.MAX_CARS)` might be enough.

**Comment by MarcCoquand** [comment]
Thanks dubzzz that worked!
