### ISSUE TITLE
Add arbitrary for ULID

### ISSUE THREAD

**Issue by vecerek** [dubzzz/fast-check#4009]
## 🚀 Feature Request

Similarly to the [UUID](https://github.com/dubzzz/fast-check/blob/2feb5c376c1296f037ec994a732e5f8420dc3e2a/packages/fast-check/src/arbitrary/uuid.ts) arbitrary, I would like to ask if we could also add one for [ULID](https://github.com/ulid/spec)s?

## Motivation

I would like to add support for ULIDs in [@effect/schema](https://github.com/Effect-TS/schema) similarly to their [UUID schema](https://github.com/Effect-TS/schema/blob/d57c92fd0007dbb7c3a53ed31ce3cd8151e8368f/src/Schema.ts#L2734-L2752). They rely on `fast-check` for generating arbitraries. So, I thought adding ULIDs here would be a reasonable starting point.

## Example

```ts
const myUlid = fc.ulid();
```

**Comment by dubzzz** [comment]
Sounds to be a good idea.

Today's philosophy in fast-check is to offer general use and not that simple to build built-ins and ulid seems to fit. Before you start the implementation: by default we consider our built-in arbitraries should be able to generate any value of the type (here: ulid even for year 10k) but if needed we may offer ways to reduce the 'scope' via constraints passed to the arbitrary at build time (for ulid we can imagine minDate and maxDate). Anyway, I'd go for full ulid first (first PR) and add constraints in next PRs.

As you seem to be willing to implement it, please go ahead and feel free to ask if you need pointers or help 😉

**Comment by dubzzz** [comment]
Just thinking...

As it has a date based part, it could be interesting if the shrinker shrinks the date part appart, so that if the code consuming the ulid has an issue with the date it will explodes on that date limit.

The way to do that is to have something like:

```js
fc.tuple(
  datePartArbitrary, // no need to be date arb
  nonDatePartArbitrary
).map(joinFunction)
```

Or by replacing `tuple` by `record`. See existing arbitraries such as ipV4, uuid... for more details.

**Comment by vecerek** [comment]
@dubzzz thank you for the pointers. It is my first time trying to contribute to this project, and I haven't fully wrapped my head around it just yet. Here are some of my thoughts about the challenges I'm facing:

- as you correctly described above, ULIDs consist of two parts (1) a timestamp of 48 bits, and (2) a randomness part of 80 bits
- I could generate the first part as an integer, but I can't do the same with the second part since numeric literals with absolute values equal to 2^53 or greater are too large to be represented accurately as integers
- I could probably split the second part into two distinct parts of randomness, 40 bits of length each.
- ULIDs are 128 bits long just like UUIDs, in their string representation they are 26 characters long. The first character is 0-7 (3 bits), the leftover 25 characters are the base32 crockford characters (125 bits): 10 digits + 22 letters (excluded letters are: I, L, O, U)
- Once I have the 3 integer values (48-bit, 40-bit, and 40-bit), I need to figure out the mapping to a string (somewhat similar to your `numberToPaddedEightMapper` function in `buildPaddedNumberArbitrary`).
- I'm thinking about how to take the first 3 bits, and then loop through the rest taking 5 bits at a time and map each value [accordingly](https://www.crockford.com/base32.html).

Do you think I'm on the right track or am I approaching this from the wrong end?

**Comment by dubzzz** [comment]
> but I can't do the same with the second part since numeric literals with absolute values equal to 2^53 or greater are too large to be represented accurately as integers

You may want to use `bigUint` for that second part 🤔

**Comment by dubzzz** [comment]
The rest of the plan either with directly 80bits or twice 40bits looks good to be 👍

> - Once I have the 3 integer values (48-bit, 40-bit, and 40-bit), I need to figure out the mapping to a string (somewhat similar to your numberToPaddedEightMapper function in buildPaddedNumberArbitrary).
> - I'm thinking about how to take the first 3 bits, and then loop through the rest taking 5 bits at a time and map each value accordingly.

**Comment by dubzzz** [comment]
For the first iteration, you may only need the mapper. But on the long run, it might be worthy to have the unmapper: this second helper function is used whenever fast-check is requested to check a user defined value (neither critical not required for the first iteration).

**Comment by vecerek** [comment]
@dubzzz I ended up taking a different approach. 

### Encoding

I first determine the length of the base32-encoded string by calculating the base 32 log of the value. Then, I'm doing some math in order to get the number into a representation like this:

```math
symbol_n * 32^n + symbol_{n-1} * 32^{n-1} + ... + symbol_0 * 32^0
```

I do this in a while loop, so I basically have a stream of these symbols and I'm just translating them into the actual base32-encoded characters using a lookup table.

### Decoding

I decode each base32 string character first. This gives me an array of symbols which I reduce using the above formula. That yields an integer.

**Comment by vecerek** [comment]
@dubzzz any estimate on when the new release drops? Once it does, we can close this issue.

**Comment by dubzzz** [comment]
Release soon. Merging the changelog and launching it

**Comment by dubzzz** [comment]
Done
