### ISSUE TITLE
Provide date arbitrary

### ISSUE THREAD

**Issue by BourgoisMickael** [dubzzz/fast-check#403]
## 🚀 Feature Request

Provide date arbitrary for native `Date` and `moment` dates

## Motivation

Because there is no date arbitrary

## Example

`fc.date() // 2019-08-17T14:08:44.096Z`
`fc.stringDate() // 'Sat Aug 17 2019 16:17:29 GMT+0200 (CEST)'`
`fc.ISOstringDate() // '2019-08-17T14:17:21.020Z'`

**Comment by dubzzz** [comment]
Very good point, `fc.date()` should definitely be part of fast-check as it's pretty error prone.

Most of the implementation I've seen so far make use of `Date.now()`. It makes the arbitrary unreliable as it depends on a _random_/not-controlled value.

I believe we should have:
- `fc.date()`
- `fc.date(minDate, maxDate)`

Or:
- `fc.date(constraints?: {minDate?: Date, maxDate?: Date}`)

Concerning the two other arbitraries, it'll depend on how we can ensure that it produces the same values whatever the JS runtime, the langage of the user.. But ISO format should be feasible and fit with all those constraints. For `fc.stringDate` we should either force a locale, ask one or take one at random as part of the arbitrary.
