### ISSUE TITLE
Exclusive min/max for number arbitraries

### ISSUE THREAD

**Issue by zbjornson** [dubzzz/fast-check#4046]
## 🚀 Feature Request

`fc.double()` and friends take `min` and `max` options that are inclusive. It would be useful (especially for `float`/`double`) to support exclusive bounds. 

## Motivation

Without this feature, we either need to use `fc.double({min}).filter(v => v > min)` or `fc.double({min: nextafter(min, Infinity)})` (where `nextafter` is like [C++'s fn](https://en.cppreference.com/w/cpp/numeric/math/nextafter)).

## Example

Maybe:
```js
fc.double({minEx: 1.25, maxEx: 5.5})
```
or `minExcl`. Using another option like `exclusiveMin: true` wouldn't be much shorter than `.filter()`, but still an improvement.

---

This library is great, thanks for developing it.

**Comment by dubzzz** [comment]
I'd rather go for a `nextafter` or `nextbefore` and not add complexity to the API. Having to support extra constraints on arbitraries tend to make them more difficult to maintain and make them evolve in the case of a library.

**Comment by dubzzz** [comment]
Actually I think your idea is great. Adding it as built-in options is probably the best option. Let's go for this idea.

**Comment by dubzzz** [comment]
Implemented and released 🚀

**Comment by zbjornson** [comment]
Awesome, thanks a lot!
