### ISSUE TITLE
Document how to use in conjonction with faker

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#405]
## 🚀 Feature Request

Document how fast-check arbitraries can be extended by existing faker libraries and how to achieve this.

## Motivation

fast-check do not and will not provide all the possible fakers in its core. As faker libraries are well fitted to generate such data, users should be able to plug them easily and safely into fast-check.

## Example

Example: https://runkit.com/dubzzz/faker-to-fast-check

**Comment by BourgoisMickael** [comment]
Nice, I wanted to ask a way to use faker as arbitrary. Perfect.

**Comment by dubzzz** [comment]
@BourgoisMickael I updated the documentation to add a section about fakers, see https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/Tips.md#combine-with-other-faker-or-random-generator-libraries

**Comment by BourgoisMickael** [comment]
I think it could be implemented directly on `fc`, so we don't have to write those functions we could just do  `fc.fakerToArb(faker.address.streetAddress)`, or `fc.fromFaker(faker.address.streetAddress)`

**Comment by dubzzz** [comment]
I prefer not making the core of fast-check dependant on a third party which is not needed most of the time. Moreover the integration with faker is really specific to it and does not apply to other 'faker' libs (like lorem-ipsum.js for instance) 

I can maybe provide a fast-check-faker lib for that purpose if there is such a need.

**Comment by BourgoisMickael** [comment]
Ok, it's good like that then
