### ISSUE TITLE
Add custom reporter for fc.assert

### ISSUE THREAD

**Issue by BourgoisMickael** [dubzzz/fast-check#406]
## 🚀 Feature Request

Provide a way to customize the output of `fc.assert` with a custom reporter, as discussed in [#399](https://github.com/dubzzz/fast-check/issues/399#issuecomment-522310927) 

## Motivation

If I want to customize the output, I have to call `fc.check`, format the result and then throw an error. It would be simpler to just provide a formater to `fc.assert`.
Also the `error` field contains already formatted error message + stack trace, so currently I need to substract each part that I want to reformat.
It would be nice to have an `errorMessage` and an `errorStack` containing the raw values.

## Example

```js
function customReporter (details) {
  const message = `Custom failure message\n Failure after ${details.numRuns}` +
  `Got error: ${details.errorMessage}\n...`

  return message
}

fc.assert(
  fc.property(
    fc.integer, num => { throw new Error (num) }
  ),
  { reporter: customReporter }
)
```

**Comment by dubzzz** [comment]
It took me a while to make my mind on this topic but here are several possibilities I came with. None of them are perfect but putting them in this ticket might help me to make my mind on it.

**1. No custom reporter**

No custom reporter, users have to use `fc.check`.
But they will be able to access to the default error formater of the framework if needed by using something like `fc.formatRunDetailsIfFailed(outputOfCheck)` or `fc.defaultErrorMessage(outputOfCheck)`.

Given that capabilities the users will be able to do:

```js
const out = fc.check(property);
if (out.failed) {
  throw new Error(fc.formatRunDetailsIfFailed(out));
}
```

Or wrap it to use this custom reporter again and again:

```js
function assertWithCustomReporter(property, parameters) {
  const out = fc.check(property, parameters);
  if (out.failed) {
    throw new Error(fc.formatRunDetailsIfFailed(out));
  }
}
```

Issues:
- Difficult to type the function `assertWithCustomReporter`
- Dealing with sync and async properties would need to do two different wrappers

Advantages:
- Reporters can be asynchrounous - This is clearly a must have if we want something that will work for most of the possible usages: for instance we can imagine that the reporter will be used to write stuf on the hard-drive after a failed test execution...

**2. Custom reporter parameter**

_Synchronous & Asynchronous reporters_

If fast-check wants to include that as a possible parameter that can be passed along the `seed`, we need to be able keep in mind that we want reporters to be potentially asynchrounous but also to be definable into our global config.

Here is a possible way to deal with asynchronous reporters while preserving the fact that we want this setting to be configurable at global level:

We can offer two parameters `reporter` and `asyncReporter`. Whenever `asyncReporter` is defined, any synchronous assert will be rejected with an error stating that `asyncReporter` cannot be set when running synchronous properties.

Now if `reporter` alone is set, no issue, both the synchronous and the asynchrounous version of `fc.assert` will make use of it.

If both are defined, there is clearly a conflict. As synchrounous `fc.assert` will reject, we may just do the same for the asynchronous version. Actually specifying both is clearly error-prone so warning the user does not seem to be too problematic. And in case users complain about that we may think again about that topic.

With that users will be able to define globally custom reporters as follow:

```js
// With synchronous reporter (both versions of `fc.assert` will be running)
fc.configureGlobal({ reporter: customReporter })
fc.assert(syncProperty) // it used the custom reporter
fc.assert(asyncProperty) // it used the custom reporter

// With asynchronous reporter (only async version of `fc.assert` will be running, sync will reject)
fc.configureGlobal({ asyncReporter: customAsyncReporter })
fc.assert(syncProperty) // it throws
fc.assert(asyncProperty) // it used the custom reporter

// By setting the reporter when calling `fc.assert`
fc.assert(syncProperty, { reporter: customReporter })
```

_Ins and Outs_

Now what would be the **in**s and **out**s of the reporter.

Here are some thoughts we may have:
- **YES** - Do we expect the reporter to throw? _In other words: can the reporter override what is considered to be a failure?_
- **YES** - Is it always called? _In other words: Do we call it on both success and errors?_
- **Always override** - Can it optionally override default? Or does it always override it? _In other words: Is custom reporter replacing `throwIfFailed` when specified? Note: the current implementation for the async version of `fc.assert` is the following `(property, params) => fc.check(property, settings).then(throwIfFailed)`_

_Default reporter_

The last part is: how do we make our users able to access the default reporter?

Do we pass the error/string that would have reported to the reporter? Do we let the reporter in charge to format everything on its own? Do we provide a `fc.formatRunDetailsIfFailed` as suggested in **1.**? Or maybe something even more customizable (ie I want to see A, B, but not C in the report)?

---

The topic is still WIP on my side but I wanted to give you some updates on it ;)

**Comment by dubzzz** [comment]
`reporter` option has been released

**Comment by dubzzz** [comment]
@BourgoisMickael I'm closing the issue as it should be fixed now. Please feel free to re-open and let me know if `reporter` does not answer to your needs
