### ISSUE TITLE
Publish an extension jsverify-to-fast-check 

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#413]
## 🚀 Feature Request

Publish an extension jsverify-to-fast-check to wrap jsverify arbitraries into arbitraries that could be consumed by fast-check. 

It should keep the shrinking capabilities of the initial arbitrary. 

## Motivation

Such extension should help users to migrate from jsverify to fast-check in a smooth way. 

## Example 

None.

**Comment by dubzzz** [comment]
Repository will be: https://github.com/dubzzz/jsverify-to-fast-check

**Comment by TheSpyder** [comment]
There is one other thing I will sorely miss when I try to migrate, which is a follow up on #109 and #133

In jsverify, `jsc.property(name: string, ...)` is short for

```
it(name, function () {
  jsc.assert(jsc.forall(...));
}
```

Have you had any more thoughts on offering an equivalent in fast-check?
