### ISSUE TITLE
Infinite loop when trying to replay failure

### ISSUE THREAD

**Issue by brapifra** [dubzzz/fast-check#415]
## 🐛 Bug Report

I'm trying to reproduce a failure with a specific `seed` and `path`, but the unit test just enters an infinite loop. The most intriguing thing is that jest doesn't timeout :thinking: 

Apparently, if I change the path to `2:0`, it doesn't enter an infinite loop. However, a wrong path shouldn't prevent jest from timing out.

## To Reproduce

```typescript
import fc from 'fast-check';

describe('suite', () => {
    it('unit test', () => {
        const property = fc.property(fc.nat(), num => {
            console.log(num);
            console.log('******');
        });

        fc.assert(property, { seed: -1386863032, path: '2', endOnFailure: true });
    });
});
```

## Expected behavior

It should only run the property `numRuns` times and it shouldn't prevent jest from timing out.

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            |     1.16.0       |
| node                  |     10.14.1       |
| TypeScript*           |      3.4.5      |

*Only for TypeScript's users

**Comment by dubzzz** [comment]
Thanks a lot for the report, I think I know what is the issue.
I'll come back to you as soon as I get a fix done and released for it.

**Comment by dubzzz** [comment]
I'll release a version containing the fix shortly

**Comment by dubzzz** [comment]
The fix will be backported in all the minor versions of fast-check that have been impacted by the regression. It will be released in: `1.3.1`, `1.4.1`, `1.5.1`, `1.6.3`, `1.7.2`, `1.8.3`, `1.9.4`, `1.10.2`, `1.11.1`, `1.12.2`, `1.13.1`, `1.14.1`, `1.15.2`, `1.16.1`.

**Comment by dubzzz** [comment]
@brapifra Version 1.16.1 is available on NPM, please let me know if it does not fix the issue on your side

**Comment by brapifra** [comment]
It fixed the issue. Thanks! @dubzzz
