### ISSUE TITLE
Why does jsonObject arb return a number ?

### ISSUE THREAD

**Issue by ZeRego** [dubzzz/fast-check#416]
## 💬 Question and Help
It seems fc.jsonObject returns a number in some cases. Is this intentional ? If yes, we should probably improve the documentation.

My use case:
`fc.oneof(fc.jsonObject(), fc.constant(undefined));`
Result: 
`1.1102230246251565e-16`

**Comment by dubzzz** [comment]
This behaviour is fully expected. `fc.jsonObject()` is supposed to produce JavaScript instances that satisfy: `JSON.parse(JSON.stringify(entity))` equals `entity` \[[tested here](https://github.com/dubzzz/fast-check/blob/2942e62144716f80bb61113b5df851164804eefa/test/unit/check/arbitrary/ObjectArbitrary.spec.ts#L330)\].

Please feel free to suggest a documentation or jsdoc update if you believe we can make it clearer 👍 

---

In https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/Arbitraries.md#objects-any

> fc.jsonObject() or fc.jsonObject(maxDepth: number) generate an object that is eligible to be stringified and parsed back to itself (object compatible with json stringify)

In https://dubzzz.github.io/fast-check/#/2-API/fast-check/jsonObject

> For any JSON compliant values

---

**Quick tips** - if you want to preview what are the generated values of an arbitrary you can use `fc.sample` as follow:

```js
const fc = require('fast-check');
fc.sample(fc.jsonObject()); // produce an array containing the 100 first values
                            // that would have been generated by fc.jsonObject()
```

See https://runkit.com/dubzzz/5d5af70beaec0b001442b399

**Comment by ZeRego** [comment]
Thanks for clarifying.
I think the arb name having 'object' in it made me assume it was supposed to return an object. 

Maybe we could add that description to these places in the documentation:
- https://dubzzz.github.io/fast-check/#/2-API/fast-check/jsonObject?id=jsonobject-function
- https://dubzzz.github.io/fast-check/#/2-API/fast-check/jsonObject_1?id=jsonobject-function

Because those were the results when I searched for jsonObject.

I'm now using the object() arb which is what I want.

**Comment by dubzzz** [comment]
Please feel free to open a PR with the updated documentations 👍 

Can we close the issue for the moment (if I answered your question)?

**Comment by dubzzz** [comment]
Closing the issue. Please feel free to re-open
