### ISSUE TITLE
Shrinker never stops when there is the value that is not controlled by the generator

### ISSUE THREAD

**Issue by AlexeyRaga** [dubzzz/fast-check#4161]
## 🐛 Bug Report

This happens when writing a test which uses the generator to generate an object whose value is not fully controlled by the generator.

Example:
```typescript
  fit('this test never ends', async () => {
    await fc.assert(
      fc.asyncProperty(fc.gen(), async gen => {
        // I want the id to always be a new UUID, even when shrinking.
        // This is requited for an integration testing, when the events are sent,
        //   counted and asserted grouped by id
        const aggregateId = UUID.v4();
        console.warn(`aggregateId: ${aggregateId}`);

        const events = gen(fc.record, {id: fc.constant(aggregateId), type: fc.string()}, {});

        // can no nothing here

        throw new Error("Boom!");
      }), {numRuns: 1});
    });
```

This test runs endlessly.

adding `noShrink()` doesn't help:

```typescript
fc.constant(aggregateId).noShrink()
```

## To Reproduce

Steps to reproduce:

Run the test from the example above

## Expected behavior

The values that are "provided externally" and not generated do not affect shrinking behavior.

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| fast-check           |  3.12.0 |
| node                 |  v18.16.1 |
| TypeScript\*         | 5.1.6  |

\*Only for TypeScript's users

**Comment by dubzzz** [comment]
For now, none of the shrinker officially support having uncontrolled data passed as input. Having some internal checks for that would drop the performance of the library by a slightly important amount in some cases.

Instead of your current version, I'd rather go for:

```ts
  fit('this test never ends', async () => {
    await fc.assert(
      fc.asyncProperty(fc.gen(), async gen => {
        // I want the id to always be a new UUID, even when shrinking.
        // This is requited for an integration testing, when the events are sent,
        //   counted and asserted grouped by id
        const aggregateId = UUID.v4();
        console.warn(`aggregateId: ${aggregateId}`);

        const eventFC = gen(fc.record, {type: fc.string()}, {});
        const event = {...eventFC, id: aggregateId};

        // can no nothing here

        throw new Error("Boom!");
      }), {numRuns: 1});
    });
```

In other words, I put the fast-check and safe part on its side and the randomly generated one outside of the scope of fast-check.

**Comment by AlexeyRaga** [comment]
Yes, it works, and this is exactly how I workaround it, but still wanted to report a bug :)

**Comment by dubzzz** [comment]
I won't fix that one for now. Actually preventing such shrink is far from trivial as there are legit cases with `gen` being called with values that may changed from one run to another during shrink.

I actually planned to add such error case when I initially worked on the feature, but it seems that it was not a good idea when I read back the comment I put in the shrinker logic:

```ts
    // While tempting, one should not "Forbid users to diverge on the first generated value" or any other values
    // Actually it's legit case when the value is used in conjunction with other arbitraries as each will be shrunk separately
    // possibly leading from totally different sets of functions.
    // In other words: `preBuiltValue !== undefined && context.history.length === 0` is a legit case!
    // If we start to mismatch we run a new random value computation
    const g = arb.generate(localMrng, biasFactor);
    context.history.push({ arb, value: g.value_, context: g.context, mrng: localMrng.clone() });
    return g.value;
```
