### ISSUE TITLE
Add Ethereum name or address to package.json

### ISSUE THREAD

**Issue by lastmjs** [dubzzz/fast-check#421]
## 💡 Idea

I would like to see an Ethereum name or address added to the ethereum field of the package.json file. This will allow consumers of the project to know a cannonical address to send funds to. For example, I'm building an application that will allow developers to automatically donate ETH to all of their npm dependencies that have Ethereum addresses in their package.json files: https://sustainus.io

## Motivation

To enable open source sustainability through automated voluntary contributions and to see Sustainus and its model become successful

## Example

Just add an Ethereum address to the `ethereum` field of the package.json file, nothing more nothing less

**Comment by dubzzz** [comment]
Thanks for the suggestion. I'm closing it for the moment as I don't have any Ethereum address for the moment 😁
