### ISSUE TITLE
in place modification of array confuses shrinking and its output

### ISSUE THREAD

**Issue by joost2076** [dubzzz/fast-check#4404]
## 🐛 Bug Report
If you make any change in the property function to an array supplied by fc.array,  the starting point for the shrinking and the presented counterexample include the change to the array. This is confusing if you are unaware you must copy the array before making changes to it.   

## To Reproduce
This toy example shows what I mean: The array used in the shrinking and counterexample should not include 13 but only values 1 to 5. 
Also, returning false immediately (instead of randomly) leads to fast-check getting stuck in a loop

  ```
fc.assert(
    fc.property(
      fc.array(fc.integer({min:1, max:5}), {minLength:2, maxLength:4}),
      (arr)=>{
        console.log(arr)
        arr[0] = 13
        return Math.random() < 0.1? false:true
      }
    )
  )
  // [ 4, 4 ]
  // [ 1, 4, 1 ]
  // [ 5, 1, 1, 5 ]
  // [ 2, 2 ]
  // [ 5, 1 ]
  // [ 2, 4, 2 ]
  // [ 4, 2 ]
  // [ 1, 4, 2 ]
  // [ 7, 4, 2 ]
  // [ 10, 4, 2 ]
  // [ 12, 4, 2 ]
  // [ 13, 1, 2 ]
  // [ 13, 3, 2 ]
  // [ 13, 4, 1 ]
  
  // error: Error: Property failed after 6 tests
  // { seed: 1144030673, path: "5", endOnFailure: true }
  // Counterexample: [[13,4,2]]
  // Shrunk 0 time(s)
  // Got error: Property failed by returning false
```
## Expected behavior
Shrinking / counterexample start from / show original array. 

## Your environment
fast-check 3.13.1
deno 1.37.1

**Comment by dubzzz** [comment]
Not a bug as explained in: https://github.com/dubzzz/fast-check/issues/4161#issuecomment-1694348588

Supporting side-effects on the returned values would imply a huge performance penalty (at least in current state). I should probably better document that to make it clearer when reading the documentation 🤔

**Comment by joost2076** [comment]
ok understood,  I reread the arbitraries section in the docs looking for a warning like that before i opened the bug, but i see now the properties section makes more sense. Sorry about that.

**Comment by dubzzz** [comment]
> Sorry about that

No worry. It's ok, I may find a way to make it more visible
