### ISSUE TITLE
Missing documentation for `fc.frequency`

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#441]
## 💬 Question and Help

While `fc.frequency` should be described right after `fc.oneof` in the page https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/Arbitraries.md#combinors-of-arbitraries-t it seems that it was forgotten from the documentation.

**AIM** Add missing documentation

**Comment by giovannyg** [comment]
Hi, I'd like to claim this issue, I'll create a pr soon, thanks.

**Comment by dubzzz** [comment]
Perfect 👌
