### ISSUE TITLE
Improve security against supply chain attacks

### ISSUE THREAD

**Issue by paulmillr** [dubzzz/fast-check#4475]
Simply locking down `pure-rand` dependency version from `^6.0.0` to `6.0.0` would be enough to be much more resilient against supply chain attacks.

Right now, if malware is published in pure-rand 6.0.1, it would be automatically distributed to all fast-check users. Since fast-check is used in all kinds of important and security-critical projects, it can be disastrous.

Your pure-rand module is stable and has not been updated for many months. There is ZERO need in having its open-ended version range. If a bug arises, you will just publish new pure-rand WITH new fast-check. That's it.

**Comment by dubzzz** [comment]
No plan to change that. I follow semver and what I need is `^6.0.0`. I don't want to republish all my previous versions anytime pure-rand gets bumped.

If users want to protect themselves, they can use lock-files.

The dependency being `^` is an usual pattern. Jest or Redux also import their dependencies that way.

Additionally I am the author of pure-rand too. And since last time I now sign all the releases.

**Comment by dubzzz** [comment]
Well-known packages such as React have the same 'vulnerability' (if we consider it as a vuln): https://www.npmjs.com/package/react?activeTab=code.

In the case of React they depend on a package that has not been updated for 5 years and that doesn't even belong to them. But they import it with `^` scope too.

As the `^` is, in my opinion, the way to go as most packages do that, it reduces maintenance... I'll stay with it.

But thanks for the report ☺️

**Comment by paulmillr** [comment]
>I don't want to republish all my previous versions

What? Old versions will stay frozen, the same. You can't "republish" them.

**Comment by paulmillr** [comment]
Yes, this is a big problem in JS ecosystem which i'm trying to fix [^1] [^2]. This is the primary reason supply chain attacks are so successful. If maintainers were more aware, they would not have used ranges. I have opened an issue in React.


[^1]: https://paulmillr.com/posts/eth-cryptography/
[^2]: https://paulmillr.com/posts/chokidar-3-save-32tb-of-traffic/

**Comment by dubzzz** [comment]
> What? Old versions will stay frozen, the same. You can't "republish" them.

Not meaning republish as having a new code for an already published version. I was mostly thinking of:

Let's imagine I published fast-check 3.0.0...3.14.0 with strict dependency on pure-rand. As pure-rand may improve it's speed, it's packaging in next minor/patch. I might be keen into publishing 3.0.1...3.14.1 to reference this new version. So 15 versions of fast-check to publish. Additionally locking to one specific version is not a good idea if my users want themselves to pull pure-rand. Package will be downloaded several times...

**Comment by paulmillr** [comment]
>I might be keen into publishing 3.0.1...3.14.1 to reference this new version

No one does stuff like this. They just publish 3.15.0 with new version of pure-rand. Old versions are irrelevant unless it's security upgrade.
