### ISSUE TITLE
Enable the eslint rule `@typescript-eslint/no-unused-vars` in `.eslintrc.js`

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#448]
## 💡 Idea

Enable the eslint rule `@typescript-eslint/no-unused-vars` in `.eslintrc.js`.

Consider the rule configuration:

```
"@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_" }]
```

## Motivation

The rule `@typescript-eslint/no-unused-vars` helps to prevent unwanting behaviour by raising red flags when variables are declared but not used.

## Example

Example of fix:

```diff
   describe('AsyncProperty', () => {
     it('Should fail if predicate fails', async () => {
---    const p = asyncProperty(stubArb.single(8), async (arg: number) => {
+++    const p = asyncProperty(stubArb.single(8), async (_arg: number) => {
         return false;
       });
       expect(await p.run(p.generate(stubRng.mutable.nocall()).value)).not.toBe(null); // property fails
     });
```

Or:

```diff
       it('Should drop nothing', () => {
         function* g() {
           yield* [-4, -2, -3, 1, -8, 7];
         }
---      const s = stream(g()).dropWhile(v => false);
+++      const s = stream(g()).dropWhile(_ => false);
         expect([...s]).toEqual([-4, -2, -3, 1, -8, 7]);
       });
     });
```

## How?

As there are 147 errors like this, do not hesitate to split the PR into multiple sub-PRs if it makes the PR clearer.

Please to not hesitate to report strange unused variables.

**Comment by CSBatchelor** [comment]
I'll start working on this.

**Comment by dubzzz** [comment]
Perfect, thanks a lot 👌

**Comment by Tamy123** [comment]
Can i do this too?

**Comment by dubzzz** [comment]
@Tamy123 Please sync with @CSBatchelor

Normally the issue can be split into several chunks. For instance, one doing src, the other test/unit and another one test/e2e

**Comment by CSBatchelor** [comment]
@Tamy123 I started in test/e2e so I'll finish those up. Feel free to work on another directory, just let me know so I don't work on it when I'm done :+1:

**Comment by dubzzz** [comment]
@Tamy123 any updates?

**Comment by dubzzz** [comment]
@Tamy123 still wanting to do it?

**Comment by dubzzz** [comment]
@Tamy123 @CSBatchelor I'm gonna do this task in order to unlock this eslint flag

**Comment by Tamy123** [comment]
Sure
