### ISSUE TITLE
object arbitrary returns `unknown` type

### ISSUE THREAD

**Issue by ZeRego** [dubzzz/fast-check#458]
## 💥 Regression Report

New typing for object arbitrary is now causing lint errors in my project.

It used to be:
`function object(): Arbitrary<any>;`
and now is:
`function object(): Arbitrary<unknown>;`

## Versions

Worked up to version:

1.16.0

Stopped working in version:

1.18.0

## To Reproduce

```
interface Test {
    prop: object;
}

fc.record<Test>({
    prop: fc.object();  // has lint error because it returns 'unknown' and prop is 'object'
})
```

## Expected behavior

Since the expected result is an object it should be typed like so:
`function object(): Arbitrary<object>;`

**Comment by giogonzo** [comment]
This is my fault from #436

Using `Arbitrary<object>` as return type is not correct IMO, `object()` returns any possible JS object meaning also strings, booleans etc.

These are not `object` in TS terms

```ts
const a: object = 'asd' // Type 'string' is not assignable to type 'object'. ts(2322)
```

@dubzzz I can take a look at this in the next few days if you wish, I believe some other types should be updated accordingly after my change (i.e. I didn't test types all fast-check functions together with my PR)

**Comment by giogonzo** [comment]
Actually, taking a second look at the sourcecode for `object()`, it seems to be boxing every primitive value with `new ()`: https://github.com/dubzzz/fast-check/blob/master/src/check/arbitrary/ObjectArbitrary.ts#L55-L73

So `Arbitrary<object>` is probably correct, since:

```ts
const a: object = new String('asd')
```

is indeed valid TS

**Comment by dubzzz** [comment]
Arf, it's indeed a regression. `fc.object` is supposed to produce values like `{ [k:string] : unknown }` or `object`.

It basically generates a dictionary of `fc.anything`. I'll double-check the code. I'll let you know as soon as I get a fix released. 

See https://github.com/dubzzz/fast-check/blob/master/src/check/arbitrary/ObjectArbitrary.ts#L199-L201

**Comment by dubzzz** [comment]
@ZeRego Version 1.18.1 of fast-check should fix your issue. Please re-open the issue if it does not
