### ISSUE TITLE
Github releases showing no information and wrong latests release

### ISSUE THREAD

**Issue by ZeRego** [dubzzz/fast-check#460]
## 🐛 Bug Report

- The last releases seem to be missing information
- Github shows 1.16.3 as the latest release while npm shows 1.18.1 as the latest

<img width="1080" alt="Screen Shot 2019-10-25 at 17 26 22" src="https://user-images.githubusercontent.com/9117144/67587893-adfb1800-f74c-11e9-9630-bf4afd23ba89.png">

**Comment by dubzzz** [comment]
The only officially supported and up-to-date changelog is the one in the repository. The version history available within GitHub is configured for convenience but is a painful manual copy of the changelog I do from time to time.

See https://github.com/dubzzz/fast-check/blob/master/CHANGELOG.md for the official changelog.

**Comment by dubzzz** [comment]
Prefer closing the issue as the real changelog is up-to-date

**Comment by dubzzz** [comment]
@ZeRego I updated the release page on GitHub to keep it updated with the CHANGELOG file
