### ISSUE TITLE
Export Property, AsyncProperty and IProperty types

### ISSUE THREAD

**Issue by tinydylan** [dubzzz/fast-check#461]
## 🚀 Feature Request

Export the Property, AsyncProperty and IProperty types, so calling code can reference these types.

## Motivation

I am working on a custom test framework, and wish to make use of fast-check properties. I need to be able to accept a Property or AsyncProperty as a parameter, and run it in a special way, in order to wire up the pass/fail callbacks correctly.

## Example

My testing framework uses "Steps" which are asynchronous functions with logs. Below is how I would need to wire it up to run AsyncProperties. Currently, I can't refer to the AsyncProperty type, as it is not exported.

```
import { TestLogs } from '@ephox/agar';
import * as fc from 'fast-check';

export interface Step<T, U> {
  runStep: (value: T, next: (value: U, logs: TestLogs) => void, die: (err: any, logs: TestLogs) => void, logs: TestLogs) => void;
}

export const foo = <T, P>(name: string, makeProp: (t: T) => fc.AsyncProperty<P>): Step<T, T> =>
  ({
    runStep: (value, next, die, logs) => {
      fc.assert(makeProp(value)).then(() => next(value, logs)).catch((r) => {
        die(r, logs);
      });
    }
  });
```

**Comment by tinydylan** [comment]
What about something like this?

```
export interface IAsyncProperty {
}

class AsyncProperty implements IAsyncProperty {
}

```

**Comment by tinydylan** [comment]
BTW - thanks for your help! I'm loving fast-check so far. My team is using it to replace our use of JSVerify in the TinyMCE codebase.

**Comment by dubzzz** [comment]
You might be interested in https://github.com/dubzzz/jsverify-to-fast-check to help you migrate from jsverify

**Comment by dubzzz** [comment]
@tinydylan Just opened a PR to expose interfaces for properties. Would it fit your needs? - see #463

**Comment by tinydylan** [comment]
Yeah, that looks good to me.

**Comment by dubzzz** [comment]
Sorry for the delay. Version 1.19.0 of fast-check, should fit your needs

Please re-open the issue in case it does not
