### ISSUE TITLE
fc.array() hangs when optional parameters are given

### ISSUE THREAD

**Issue by akrejczinger** [dubzzz/fast-check#468]
## 🐛 Bug Report

`fc.array()` hangs when optional parameters are given

## To Reproduce

Steps to reproduce:
```js
it("throws an error with the generated value", () => {
  fc.assert(
    fc.property(fc.array(fc.nat(), { minLength: 1 }) , value => {
      throw value
    })
  )
})
```

## Expected behavior

A random array should be generated, then thrown as an error, which is then shown in the mocha test output.
Actual behavior: the test hangs and nothing is printed.
The same issue happens with `maxLength` as well.
The test works as expected if optional parameters are not given.

## Your environment

| Packages / Softwares  | Version(s)       |
| --------------------- | ---------------- |
| fast-check            | 1.18.1           |
| node                  | 10.17.0          |
| TypeScript*           | none, vanilla JS |

*Only for TypeScript's users

**Comment by dubzzz** [comment]
I don't think we should consider it has a bug as you are not calling `fc.array` with the right arguments. Please refer to https://dubzzz.github.io/fast-check/#/2-API/fast-check/array_3?id=array-function

Correct code should be:
```js
it("throws an error with the generated value", () => {
  fc.assert(
    fc.property(fc.array(fc.nat(), 1, 10) , value => {
      throw value
    })
  )
})
```

There is no min-only signature for `fc.array` for the moment, so you have to pass it both min and max.

**Comment by akrejczinger** [comment]
Oh I misunderstood the usage then. The example provided works, thank you for your help.
