### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by pcorey** [dubzzz/fast-check#485]
## 🐛 Bug Report

I wanted to test out fast-check, so I wrote a simple function with a single property test. My test generates two integers and a natural number. If I set a precondition on one of the integers that it can't equal zero, the test suite fails to finish and fails with a heap space exception.

```js
const _ = require("lodash");
const fc = require("fast-check");

const divisibleCount = (x, y, k) => {
  return _.chain(y - x)
    .range()
    .map(n => x + n)
    .reject(n => n % k)
    .size()
    .value();
};

test("works", () => {
  fc.assert(
    fc.property(fc.integer(), fc.integer(), fc.nat(), (x, k, n) => {
      fc.pre(k !== 0);
      let y = x + n * k;
      return n === divisibleCount(x, y, k);
    })
  );
});
```

It seems like the suite runs to completion without the precondition, but I'm guessing this is because `k = 0` causes the function under test to fail, so it doesn't go through a large number of combinations.

## To Reproduce

I pushed [my simple repo](https://github.com/pcorey/count_the_divisible_numbers) that recreates the issue for me. Just clone it, and run the test suite.

Steps to reproduce:
```bash
git clone https://github.com/pcorey/count_the_divisible_numbers \
cd count_the_divisible_numbers \
yarn \
yarn test
```

## Expected behavior

I would expect the test suite to pass, or at least to run to completion. Instead, I'm getting a "JavaScript heap out of memory" error:

```
FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory
 1: 0x10007e71b node::Abort() [/Users/pcorey/.nvm/versions/node/v12.12.0/bin/node]
 2: 0x10007e89f node::OnFatalError(char const*, char const*) [/Users/pcorey/.nvm/versions/node/v12.12.0/bin/node]
 3: 0x100176137 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/pcorey/.nvm/versions/node/v12.12.0/bin/node]
 4: 0x1001760d3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/pcorey/.nvm/versions/node/v12.12.0/bin/node]
 ...
```

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            |   1.19.0         |
| node                  |     12.12.0       |

**Comment by pcorey** [comment]
I should have noticed this before I filed the issue, but if I change to a solution that doesn't allocate potentially large arrays, everything works fine.

Any recommendations for testing code that can potentially build up large data structures?

**Comment by dubzzz** [comment]
Thanks for the report and the reproduction repository: this is indeed a known _issue_. Unfortunately, I am not sure I can even do something to fix it.

As you guessed, the issue is related to the fact that the code under test is taking more memory than what node can give it and causes node to crash.

Actually all the properties executed by fast-check are wrapped within a `try { property(); } catch (err) {}` block. So I don't know how I can even intercept such _exceptions_ (not raised) and prevent node from crashing 🤔 Even jest is unable to show which test failed 😭

**Comment by pcorey** [comment]
Are you holding onto all of the results throughout the duration of the test? Either intentionally, or captured in a closure somewhere? It seems like that's what's happening. All of the results (large arrays, in my case) are being kept around for every input combination, until all combinations come back successfully. Eventually, the GC can't free them, and the next result doesn't have any room to be stored, so the process dies.

If we let go of the results after every successfully executed input combination, the garbage collection should be able to free them as it goes. At least, I think...

I don't really understand where to look for this in the code, though. Maybe in the `Runner` or the `RunnerIterable`?

**Comment by dubzzz** [comment]
The crash can be reproduced without fast-check.

For instance if you take the follwoing inputs, `{ x: 0, n: 8, k: 385970259 }`, you should reproduce it.

### How I found them?

**Hardcoded `seed` parameter for `fc.assert`**

-> crash confirmed with `{seed: 42}`

**Dichotomy on `numRuns` parameter of `fc.assert`**

-> crash confirmed with `{seed: 42, numRuns: 1}`

**Check crash is not related to shrinking**

-> it seems to be related to shrinking `{seed: 42, numRuns: 1, endOnFailure: true}`

**Dichotomy to find which run is causing the crash**

```js
test("works", () => {
  let remainingRuns = 4;
  let data = null;
  fc.assert(
    fc.property(fc.integer(), fc.integer(), fc.nat(), (x, k, n) => {
      fc.pre(k !== 0);
      let y = x + n * k;
      if (--remainingRuns <= 0) {
        if (data === null) data = JSON.stringify({ x, n, k });
        throw new Error(`No memory issue for the moment but last was: ${data}`);
      }
      return n === divisibleCount(x, y, k);
    }),
    { seed: 42, numRuns: 1 }
  );
});
```

-> `remainingRuns = 4` is the last run without memory issue
-> it might be the origin of our problem: `{"x":0,"n":8,"k":385970259}`

**Simple test with those inputs only**

```js
test("works", () => {
  const { x, n, k } = { x: 0, n: 8, k: 385970259 };
  let y = x + n * k;
  divisibleCount(x, y, k);
});
```

-> memory crash

**Comment by dubzzz** [comment]
The point on closures is perfectly legit. I double-checked some parts were I might have memory leaks.

For instance if you take a look at https://github.com/dubzzz/fast-check/blob/master/src/check/runner/reporter/RunExecution.ts#L58, you'll see that I'm storing generated values into an execution tree when in very verbose mode. And only failures in normal scenario (no verbose flag).

The second potential sourec of leaks might be the shrinkers as they have to do some closures.

**Comment by pcorey** [comment]
Thanks for looking into it @dubzzz! Good point about your example not using fast-check. Seems like I'll have to reign in the generated integers no matter what. I appreciate the help!

**Comment by dubzzz** [comment]
I looked a little bit about ways to `catch` or quit gracefully in case of *out of memory* issues.

Unfortunately according to https://github.com/nodejs/help/issues/1026#issuecomment-352380446 it does not seem to be feasible. Or at least it was not when this issue has been opened. Honestly I am a bit surprised that there is nothing in node to do that (other languages like Java or C++ have such out of memory hooks). 

All the issues I found so far on Stackoverflow suggests to increase the memory of the node process.

In your case I believe that the best way is to limit the value of `y - x` in order to avoid generating large datasets. As I don't know anything about `_.chain` if the operator is supposed to be lazy and you really expect no crash, you might open an issue in lodash (and tell them you find it with fast-check 😜).

**Comment by pcorey** [comment]
No worries. Thanks for the help @dubzzz.

**Comment by ca-d** [comment]
@pcorey @dubzzz I don't know what it says about the state of communication on the wider web in general, but I feel the strong urge to point out how much my heart was warmed by the mutually constructive, respectful, and kind way in which the two of you exchanged feedback on each other's code in this thread. Thank you :heavy_heart_exclamation:
