### ISSUE TITLE
ESLint complains "Test has no assertions"

### ISSUE THREAD

**Issue by brandon-leapyear** [dubzzz/fast-check#486]
## 🐛 Bug Report

The ESLint rule `jest/expect-expect` shows a warning "Test has no assertions". Is this something that's potentially fixable, or do we just have to do `eslint-disable-next-line` for every test?

## To Reproduce

```js
test('foo', () => {
  fc.assert(fc.property(fc.string(), (s) => s === s))
})
```

`eslint foo.spec.js`

## Expected behavior

No ESLint warning?

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            |            |
| node                  |            |
| TypeScript*           |            |

*Only for TypeScript's users

**Comment by brandon-leapyear** [comment]
Sorry, never mind
https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/expect-expect.md#assertfunctionnames
```
'jest/expect-expect': [
      'error',
      {
        assertFunctionNames: ['expect', 'fc.assert'],
      },
    ],
```

**Comment by alshakero** [comment]
You can also add a comment to the top of your file

```js
/* eslint jest/expect-expect: ["error", { "assertFunctionNames": ["expect", "expectNoRedirect"] }] */
```
