### ISSUE TITLE
Feature Request: Add equivalent to QuickCheck's `checkCoverage` feature

### ISSUE THREAD

**Issue by benny-medflyt** [dubzzz/fast-check#488]
## 🚀 Feature Request

QuickCheck recently added a new function called [checkCoverage](http://hackage.haskell.org/package/QuickCheck-2.13.2/docs/Test-QuickCheck.html#v:checkCoverage)

It is an enhancement of fast-check's `fc.statistics` functionality, but will use statistical analysis to verify that we get enough test cases for each category.

## Motivation

This conference presentation video by John Hughes explains the motivation for the feature: <https://www.youtube.com/watch?v=NcJOiQlzlXQ&t=>

The feature is discussed near the end of the video, but I highly recommend watching the whole talk, it is very interesting. In fact I think it might be a useful addition to add a link to this talk to the list of references that fast-check documentation links to

Thank you

**Comment by dubzzz** [comment]
It would be a really great feature to add into fast-check. It's certainly one of the most important issue with property based testing: sometimes we think that we cover 'all' cases regularly while we only cover some in very rare cases. 

The feature is already tracked by https://github.com/dubzzz/fast-check/issues/342

**Comment by dubzzz** [comment]
Duplicated, 
Feel free to re-open if the issue is different from #342
