### ISSUE TITLE
Arbitrary records with optional fields

### ISSUE THREAD

**Issue by gnidan** [dubzzz/fast-check#490]
## 💬 Question and Help

Hi, I have an interface with optional fields, something like:

```typescript
interface Foo {
  bar?: number
}
```

I am trying to generate arbitraries for this, but `fc.option(fc.integer())` doesn't seem to do the trick, since it always includes the property (typed as `number | null`). I'd like to omit the property entirely as optional, but I believe I can settle for `number | undefined`.

What's the best way to do this?

Thanks!

**Comment by dubzzz** [comment]
Hi,

In order to achive this need I would suggest to use one of the following constructs:

```ts
fc.record({
  bar: fc.option(fc.integer(), { nil: undefined }),
})
// key 'bar' is either a number or undefined
// instance.hasOwnProperty('bar') will always be true
```

```ts
fc.record({
  bar: fc.integer(),
}, {
  withDeletedKeys: true
})
// key 'bar' is either a number or do not exist at all
// instance.hasOwnProperty('bar') will be true if and only if instance['bar'] is a number
```

Or mix the two examples above:

```ts
fc.record({
  bar: fc.option(fc.integer(), { nil: undefined }),
}, {
  withDeletedKeys: true
})
```

**Comment by gnidan** [comment]
Ah, I was looking at the `withDeletedKeys` option, but my interface is slightly more sophisticated than my example, in that it has some optional fields and some required fields:
```typescript
interface Foo {
  foo: number,
  bar?: number
}
```

It seems like `withDeletedKeys` doesn't take into account which keys to delete?

No matter, I didn't realize you could specify what "nil" is; I think this will suffice for my purposes.

Thank you!

**Comment by dubzzz** [comment]
For the moment, there is no built-in way to select which keys should be deleted when using `withDeletedKeys`. But there is an opened issue on this subject.

You can maybe do:

```ts
fc.tuple(
  fc.record({
    foo: fc.integer(),
  },
  fc.record({
    bar: fc.integer(),
  }, {
    withDeletedKeys: true
  })
).map(([o1, o2]) => ({...o1, ...o2}))
```

That you might wrap as follow:

```ts
function myRecord<T, U>(
  recordModel: { [K in keyof T]: Arbitrary<T[K]> },
  optionalRecordModel: { [K in keyof U]: Arbitrary<U[K]> },
) {
  return fc.tuple(
    fc.record(recordModel),
    fc.record(optionalRecordModel, {withDeletedKeys: true})
  ).map(([o1,o2])=> ({...o1,...o2}))
}
```

**Comment by gnidan** [comment]
Mm, I thought about a solution like this, but I can see how it gets complicated with more optional fields, since I'd want the arbitrary to cover all combinations of optional field omissions.

Anyway, I don't need to rely on checking `hasOwnProperty` in my tests, so my use case isn't blocked waiting for the future `withDeletedKeys` enhancement you mention.

Cheers! Excellent work building this library!

**Comment by gnidan** [comment]
Just following up here to share my solution, since I ended up going with a dynamic approach after all. My goal here is to omit specific optional fields in specific tests.

I came up with this (using [typelevel-ts](https://github.com/gcanti/typelevel-ts)):

```typescript
import * as fc from "fast-check";
import { OptionalKeys, RequiredKeys } from "typelevel-ts";

interface IWithArbitraryOptionalOptions<T> {
  required: {
    [K in RequiredKeys<T>]: fc.Arbitrary<T[K]>
  },
  optional: {
    [K in OptionalKeys<T>]: fc.Arbitrary< Exclude<T[K], undefined> >
  },
  omit?: OptionalKeys<T>[]
}

const withArbitraryOptional = <T>({
  required,
  optional,
  omit = []
}: IWithArbitraryOptionalOptions<T>): fc.Arbitrary<T> => {
  const mustOmit = new Set(omit);

  const canInclude = Object.keys(optional) as OptionalKeys<T>[];
  const mayInclude = canInclude.filter((prop) => !mustOmit.has(prop));

  return fc.subarray(mayInclude)
    .chain(included => fc.record(
      included.reduce(
        (obj, prop) => ({ ...obj, [prop]: optional[prop] }),
        required as { [K in keyof T]: fc.Arbitrary<T[K]> }
      )
    ));
};
```

Which I can now use to define concrete arbitraries for each test, e.g.:

```typescript
interface Foo {
  foo: string,
  bar?: string,
  baz?: string
}

const arbitraryFooMissingBaz = withArbitraryOptional<Foo>({
  required: {
    foo: fc.string(),
  },
  optional: {
    bar: fc.string(),
    baz: fc.string()
  },
  omit: ["bar"]
});
```

Seems to work nicely! (Although I am a bit unsure of the behavior of `fc.subarray` and its shuffled variant; will be looking into that more)

**Comment by dubzzz** [comment]
@gnidan The feature is now native in fast-check 2.11.0 🥳 

Look for `record` and `requiredKeys` in https://github.com/dubzzz/fast-check/blob/master/documentation/Arbitraries.md#object

**Comment by gnidan** [comment]
Thank you @dubzzz! I just ran into this situation again and was quite surprised to see that past-me opened this issue over a year ago! And that you fixed it!

**Comment by AlexErrant** [comment]
Keeping arbitraries in sync with your changing domain types is annoying and error-prone. Here's how I used Typescript to type my arbitraries and yell at me if/when any optional fields change:

```ts
interface MyInterface {
  id: number
  some1?: string
  some2?: string
}

// https://stackoverflow.com/a/72760489 note the `Required`
type GetOptionalKeys<T> = Required<{
  [K in keyof T as undefined extends T[K] ? K : never]: T[K]
}>

type GetRequiredKeys<T> = {
  [K in keyof T as undefined extends T[K] ? never : K]: T[K]
}

const myInterfaceArbitrary: Arbitrary<MyInterface> = fc
  .tuple(
    fc.record<GetRequiredKeys<MyInterface>>({
      id: fc.integer(),
    }),
    fc.record<
      GetOptionalKeys<MyInterface>,
      RecordConstraints<"some1" | "some2">
    >(
      {
        some1: fc.string(),
        some2: fc.string(),
      },
      {
        withDeletedKeys: true,
      }
    )
  )
  .map(([o1, o2]) => ({ ...o1, ...o2 }))

const generated = fc.sample(myInterfaceArbitrary)
console.log(generated)
```

Output:
```
  { id: 14, some1: 'P', some2: '?R' },
  { id: -968907207 },
  { id: 1820062861, some2: 'tj' },
  { id: -1970329586, some1: '!', some2: '$]!/`IiR?' },
```

ngl I'm not entirely sure why TS requires that I provide `RecordConstraints<"some1" | "some2">` when I provide a second arg (`withDeletedKeys: true`) buuuuut I'm pretty noob at this so whatever 😅

**Comment by AlexErrant** [comment]
With some more braincells, I wrote this:

```ts
import fc, { Arbitrary, RecordConstraints } from "fast-check"

type OptionalKeys<T> = Required<{
  [K in keyof T as undefined extends T[K] ? K : never]: T[K]
}>

type RequiredKeys<T> = {
  [K in keyof T as undefined extends T[K] ? never : K]: T[K]
}

export function recordWithOptionalFields<T>(
  required: {
    [K in keyof RequiredKeys<T>]: Arbitrary<T[K]>
  },
  optional: {
    [K in keyof OptionalKeys<T>]: Arbitrary<T[K]>
  }
): Arbitrary<T> {
  const ret = fc
    .tuple(
      fc.record<RequiredKeys<T>>(required),
      fc.record<OptionalKeys<T>, RecordConstraints<keyof OptionalKeys<T>>>(
        optional,
        {
          withDeletedKeys: true,
        }
      )
    )
    .map(([r, o]) => ({ ...r, ...o }))
  return ret as unknown as Arbitrary<T>
}
```
I'm not proud of the `ret as unknown as Arbitrary<T>` but not sure how to fix. TypeScript scares me 😅.

Example usage:
```ts
interface MyInterface {
  id: number
  some1?: string
  some2?: string
}

const myInterfaceArbitrary = recordWithOptionalFields<MyInterface>(
  {
    id: fc.integer(),
  },
  {
    some1: fc.string(),
    some2: fc.string(),
  }
)

console.log(fc.sample(myInterfaceArbitrary))
```
TypeScript will yell at you if the first arg is missing any required keys and if the second arg is missing any optional keys.
