### ISSUE TITLE
How do make TypeScript see the .d.ts files provided by fast-check?

### ISSUE THREAD

**Issue by stephen-smith** [dubzzz/fast-check#498]
## 💬 Question and Help

I'm writing my *tests* as well as my code in TypeScript.  However, when I `import * as fc from "fast-check"` I'm getting as error from TypeScript (or maybe the loader): `TS2307: Cannot find module 'fast-check'.`  I see the \*.d.ts files under node_modules, though I don't see a index.d.ts under node_modules/fast-check

I'm fairly new to the NPM / JS / TS community, so I'm assuming I'm doing something wrong, but I've been poking around with ts-loader configuration and tsconfig.json for a bit and not making any headway.  That said, I'm not explicitly importing anything else from node_modules, so it's possible I have something systemic wrong; jest is being imported implicitly.

GitHub isn't down with attaching .js or .json files; So, I'm attaching what I think is the relevant configuration, with the .txt extension added.

[tsconfig.json.txt](https://github.com/dubzzz/fast-check/files/3948577/tsconfig.json.txt)
[webpack.config.js.txt](https://github.com/dubzzz/fast-check/files/3948578/webpack.config.js.txt)
[package.json.txt](https://github.com/dubzzz/fast-check/files/3948580/package.json.txt)

If there's a better support forum, sorry for the noise and could you please point me that way?

**Comment by dubzzz** [comment]
Normally TypeScript is supposed to detect the typings defined by fast-check by relying on the field `types` set within fast-check's package.json.

Can you try with an older release of fast-check? Meanwhile I'll try to see on my side if the version 1.20.1 - the one you're using - has been released with some kind of bug.

**Comment by dubzzz** [comment]
@stephen-smith I do not reproduce the issue. Here is what I've done it can help you:

1. `npm init -y` - from a new directory, it creates a fresh new JavaScript project
2. `npm i -D fast-check typescript @types/node` - install the minimum requirements to run fast-check using TypeScript
3. Create a file called `main.ts` with the following content:

```ts
import * as fc from "fast-check";
console.log(fc.sample(fc.nat()));
```

4. Edit `package.json` as follow:

```diff
     "scripts": {
+++    "build": "tsc main.ts"
---    "test": "echo \"Error: no test specified\" && exit 1"
     },
```

5. `npm run build` - transpiles `main.ts` to its JavaScript version `main.js`
6. `node main.js` - runs the script

**Comment by stephen-smith** [comment]
Didn't help much, but it did get me thinking.  From my existing project, if I `npx tsc src/queue.test.ts`, I *don't* get the error.  If I `npm run test`, I *don't* get the error.  If I `npm run build` or `npx webpack`, I do get the error.  I think it is because webpack is (somehow) making sure the pack doesn't depend on fast-check (which makes sense, since it is a dev dependency).

I think the best strategy for me is to figure out how to get webpack / ts-loader to ignore the tests.

Doesn't seem like an issue with fast-check at all.  Thanks for the help; closing the issue.
