### ISSUE TITLE
Allow deterministic snapshot testing

### ISSUE THREAD

**Issue by dbartholomae** [dubzzz/fast-check#501]
## 🚀 Feature Request

Add a function that uses arbitraries to deterministically create output.

## Motivation

When working with legacy code it is often hard to define exact properties. The main goal usually is to "keep the existing behavior". Nonetheless, property-based testing can help here by generating random inputs for a fixed seed and returning input-output pairs. These can then be saved and compared with help of snapshot testing tools, e. g. [Jest Snapshot testing](https://jestjs.io/docs/en/snapshot-testing).

## Example
This could be implemented as
```
interface IOutput<T1, R> {
  inputs: [T1],
  output: R
}

function generateResults<T1, R>(
        arb1: Arbitrary<T1>,
        resultGetter: (t1:T1) => R): IOutput<T1, R>[];
```
and then used in jest as
```
function add(a, b) {
  return a+b
}

...

it('returns the same results as before', () => {
  const results = fc.generateResults(
    fc.float(),
    fc.float(),
    add
  )
  expect(results).toMatchSnapshot()
})
```

## Open questions
- How to handle seeding? The output needs to be deterministic (otherwise the snapshot will fail all the time). My preferred solution would be to just add a global option for a seed that by default is `0`, but I am not sure how fast-check behaves with a fixed seed `0`.
- I would be willing to try myself at a PR, if there is interest in this, but haven't worked with the internals of the library before, so I might need some pointers where to start.

**Comment by dubzzz** [comment]
I'd say that there is currently a _built-in_ way to achieve that purpose using fast-check:

```js
const results = fc.sample(fc.tuple(fc.nat(), fc.nat()).map(add), {seed})
```

🤔 For the moment, I'd prefer not adding a `generateResults` with default seed as a first class citizen in fast-check. I prefer to focus on the property based aspect of the framework. Random values generation can be seen as a necessary feature to achieve that.

Just in case: Please note that fast-check might change the way it generates values between two minors as it is purely an implementation details for this project. To be honest, I've not changed any so far.

**Comment by dbartholomae** [comment]
Using `sample` is a nice idea. Unfortunately it only returns an array of results, and not the inputs, which makes it almost impossible to debug which cases are failing now.
If I were to set up this functionality in another repo, is there some API you would consider stable I could link in to? Or would it be better if I just duplicate the generation logic?

**Comment by dubzzz** [comment]
Alternatively you could use:

```js
const results = fc.sample(
    fc.tuple(fc.nat(), fc.nat())
      .map(inputs => ({ inputs, output: add(...inputs) })),
    { seed }
);
```

`results` will contain the inputs and the corresponding output.

`fc.sample` and `Arbitraries` are stable within a fixed minor. So if you fix the minor version it should be OK. I can't guarantee the stability accross minors, otherwise I'd be forced to bump the major each time I enhance the way to detect bugs earlier (generate values that go streat to the bug).

**Comment by dbartholomae** [comment]
D'oh, I should have seen that xD
Well, I'll stick to sample then for now :)
Is there any other feature you would like me help with? Just tag me in the relevant issue, I have some spare time between the years.

**Comment by dubzzz** [comment]
@dbartholomae 

For your information:

The next minor version of fast-check - 1.22.0 - will certainly change the way fast-check generates random values. Up to 1.21.0 random instances generated by fast-check were too close - see https://github.com/dubzzz/fast-check/issues/524. I had to change the way fast-check uses random generators to fix this issue.

You might need to update your snapshots.
