### ISSUE TITLE
Duplicate paragraph in docs

### ISSUE THREAD

**Issue by nmay231** [dubzzz/fast-check#5018]
## 🐛 Bug Report

It looks like this section has two very similar paragraphs. I'm assuming one was a rewrite and the other was not removed.

https://github.com/dubzzz/fast-check/blob/main/website/docs/tutorials/detect-race-conditions/your-first-race-condition-test.mdx#towards-next-test

Thanks for the awesome package, btw :slightly_smiling_face: I just prevented/fixed half a dozen bugs I never would have found myself.

**Comment by dubzzz** [comment]
Woups indeed, duplicated! If you want I can let you drop one of them and keep the best. So that you can be contributor to the project 👍

**Comment by dubzzz** [comment]
Otherwise I'll do in the coming days

**Comment by nmay231** [comment]
Sure!
