### ISSUE TITLE
Allow usage of `expect`

### ISSUE THREAD

**Issue by brandon-leapyear** [dubzzz/fast-check#502]
## 🚀 Feature Request

Multiple times, I've wanted to do things like the following:

```js
// neither == nor === does the correct thing here
// currently having to use lodash.isEqual
fc.property(fc.integer(), (x) => {
  expect(...).toMatchObject({ foo: 'bar' })
})
```
```js
// currently using &&
// not the end of the world in this case
fc.property(fc.integer(), (x) => {
  const result = ...
  expect(result.foo).toBe(...)
  expect(result.bar).toBe(...)
})
```
```js
// currently explicitly doing a try..catch
// and returning true/false
fc.property(fc.integer(), (x) => {
  expect(() => ...).toThrow()
})
```

I'm thinking maybe letting the property throw errors and handling those as `false`? (I believe `expect` throws an error if it fails)

## Motivation

See above

## Example

See above

**Comment by dubzzz** [comment]
`expect` is supposed to be handled properly by `fast-check` as soon as it throws on errors.

Unfortunately depending on your test runner - _`jasmine`, `mocha`, `jest`, `ava` or any other_ - and your expect library - _`chai` or any other_ - it is not always the case.

Which test runner are you using? Which expect lib? Does it really throw on errors?

Please refer to the configuration of:
- ava: https://github.com/dubzzz/fast-check-examples/blob/master/test-ava/example.spec.js
- jasmine: https://github.com/dubzzz/fast-check-examples/blob/master/test-jasmine/example.spec.js
- jest: https://github.com/dubzzz/fast-check-examples/blob/master/test-jest/example.spec.js
- mocha: https://github.com/dubzzz/fast-check-examples/blob/master/test/longest%20common%20substr/test.js
- tape: https://github.com/dubzzz/fast-check-examples/blob/master/test-tape/example.spec.js

**Comment by brandon-leapyear** [comment]
*facepalm thanks for that. I didn't see the framework-specific examples, only the general documentation (which are great, btw!). Would it maybe be possible to mention that framework methods of assertions (like `expect` in jest/ava/jasmine, or `assert` in mocha) also work? Reading the general docs, it seemed like `fc.assert` required a boolean response, and I wasn't sure if it would handle an error as normal, or if it treated errors as unexpected failures of the test environment (as opposed to a test failure)

**Comment by dubzzz** [comment]
Really great remark:

> Reading the general docs, it seemed like fc.assert required a boolean response, and I wasn't sure if it would handle an error as normal, or if it treated errors as unexpected failures of the test environment (as opposed to a test failure)

We definitely need to add this information directly into the README.md. It already appears in many other parts of the documentation but it might be great to have it directly in the README.md without having to dig into the full documentation.

@brandon-leapyear  Which one is the best in your opinion?

1. Update the example in the README.md by adding a comment like:

```diff
  // string a + b + c always contains b, whatever the values of a, b and c
  it('should always contain its substrings', () => {
---    fc.assert(fc.property(fc.string(), fc.string(), fc.string(), (a,b,c) => contains(a+b+c, b)));
+++    fc.assert(fc.property(fc.string(), fc.string(), fc.string(), (a,b,c) => {
+++      // Alternatively: no return statement and direct usage of expect or assert
+++      return contains(a+b+c, b);
+++    ));
  });
```

2. Just add a quick note below the example

Do you want to do it?

**Comment by brandon-leapyear** [comment]
Yeah, I can submit a PR!
