### ISSUE TITLE
Testing streaming API

### ISSUE THREAD

**Issue by mynameisdaniil** [dubzzz/fast-check#516]
## 💬 Question and Help
Hello there. I need a little help. Basically I'm trying to figure out how to test streaming API. To make things easier let's assume we have our streams in `objectMode=true` and all I need is to make sure say strings that go into one stream are the same that go out of another stream.

**Comment by dubzzz** [comment]
Hello,

From what I understand from your ticket, you might try something like:

```js
fc.assert(
  fc.property(
    fc.string(),
    data => {
      sendIntoStreamA(data);
      expect(readFromStreamB()).toBe(data);
    }
  )
)
```

The test build a random string, passes it to stream A and expects stream B to give back the value that we passed into stream A.

Does it answer your question? Does it solve your issue?

**Comment by mynameisdaniil** [comment]
Yep. Thanks for the answer. I was thinking it is something to do with `infiniteStream` and I just couldn't put it to good use.
