### ISSUE TITLE
Dedup arbitrary doesn't appear to work properly

### ISSUE THREAD

**Issue by mwgamble** [dubzzz/fast-check#530]
## 🐛 Bug Report

Based on the documentation, my understanding is that the `dedup` arbitrary is supposed to guarantee that the resulting tuple contains no duplicates. However, I see duplicates on every single run. The empty string `""` always shows up. Occasionally, various non-latin symbols (such as Chinese characters) show up too.

## To Reproduce

Use this `package.json`:

```json
{
  "dependencies": {
    "chai": "4.2.0",
    "fast-check": "1.21.0"
  }
}
```

Run the following script with `node test.js`:

```javascript
const { assert } = require("chai");
const fc = require("fast-check");

fc.assert(
    fc.property(fc.dedup(fc.unicodeString(), 2), vals => {
        assert.isTrue(vals[0] !== vals[1]);
    }), 
    { verbose: true },
);
```

I reproduced this with node v12.14.1 and node v10.18.1.

## Expected behavior

The above script should terminate without any output.

## Your environment

| Packages / Softwares  | Version(s)       |
| --------------------- | ---------------- |
| fast-check            | 1.21.0           |
| chai                  | 4.2.0            |
| node                  | 12.14.1, 10.18.1 |

**Comment by dubzzz** [comment]
@mwgamble 
It's totally expected. The aim of `dedup` is to produce duplicated values. Nonetheless values will have different references (in the case of objects).

So you might expect:
```js
fc.assert(fc.property(
  fc.dedup(fc.array(fc.nat(), 2),
  ([o1, o2]) => {
    return o1 != o2 && deepEqual(o1, o2);
   }))
```

In order to have no duplicates in a tuple you'll have to use `.filter` or `fc.pre`.

**Comment by mwgamble** [comment]
I assumed `dedup` was short for "de-duplicated". If that's not the case, what is it supposed to mean? Nothing in the documentation seems to clarify this or provide any examples of its output.

**Comment by dubzzz** [comment]
Indeed both the doc and the name are unclear 🤔

Opened to PR to update the doc, and suggestions for a correct naming (anyway `dedup` name will not be removed, just be aliased. It will stay at least until the next major release)

**Comment by dubzzz** [comment]
Renaming `dedup` into something better has been added into my to-do list ;)
Anyway it will require a major version bump to remove the badly named arbitrary and many PR across huge repositories relying on it.

Suggestions for the name are more than welcomed

**Comment by dubzzz** [comment]
What about `fc.dups` or `fc.clone`? 🤔

**Comment by dubzzz** [comment]
Or maybe `fc.twin`... But I'm not fan of twin as it does not sound correct when you use it to generate three times the same value
