### ISSUE TITLE
fc.array() never minimizes to less than `minLength` entries

### ISSUE THREAD

**Issue by philip-stoev** [dubzzz/fast-check#5423]
## 🚀 Feature Request

During minimization, it would be nice for `fc.array()` to be able to to below `minLength` entries, e.g. down to 1 or zero even if `minLength` is greater than 1.

A separate `minMinimizedLength` or `observeMinLengthWhenMinimizing` would be nice to have.

## Motivation

In testing databases, it is important to run tests against a large set of records (thousands) in order to increase the probability that a bug is found. Therefore, `minLength`  is set accordingly, but it is not a hard lower limit on the validity of the test.

Once a bug is found, ideally the test case should be minimized to a very small number of records, potentially 0 or 1, as the test remains valid even with a small number of records.

Another way to think of this is in terms of startup costs -- in a test with high startup costs (e.g. creating a table and indexes over it), it makes sense to amortize that startup cost over many records. However, this consideration does not apply for the minimized test case -- it does not have to optimally amortize anything. Instead, it should be as small as possible.

## Example

With MongoDB:

```
const documentArb = fc.record({
    f1: valueArb,
    f2: valueArb,
    f3: literalArb
});

const datasetArb = fc.array(documentArb, {minLength: 100, maxLength: 500});

fc.assert(fc.property(testCaseArb, ([dataset, indexes, pipelines]) => {
    coll.drop();
    # Expensive dataset population
    coll.insert(dataset);
    ... # run a bunch of tests
}
```

So a `dataset` of at least 100 records is best while the test is running, but the minimized test does not have to have `100` records, it should be allowed to go down to 1 or 0.

**Comment by gruhn** [comment]
If you want to make sure that you test larger arrays but the interface you're testing does not strictly expect a minimum length, you could also increase the `size` parameter of `fc.array`. You can use [`fc.statistics` ](https://fast-check.dev/docs/core-blocks/runners/#statistics) to get some insight about the array length distribution. For example:

```typescript
function classify(array) {
  const len = array.length
  const digits = String(len).length
  return `between ${10**(digits-1)} and ${10**digits} item(s)`
}

fc.statistics(
  fc.array(fc.nat(), { size: '+4' }),
  classify,
  { numRuns: 100 },
)
```
Output:
```
between 1000 and 10000 item(s)..86.00%
between 1 and 10 item(s).........7.00%
between 100 and 1000 item(s).....4.00%
between 10 and 100 item(s).......3.00%
```

**Comment by dubzzz** [comment]
As said by @gruhn, the recommended approach is to use: `const datasetArb = fc.array(documentArb, { size: '+4' });`.
