### ISSUE TITLE
Support type guards while filtering

### ISSUE THREAD

**Issue by gcanti** [dubzzz/fast-check#545]
## 🚀 Feature Request

Add an overloading to `filter`... 

## Motivation

...in order to refine the result type.

## Example

With the current definition:

```ts
export interface Arbitrary<T> {
  filter(predicate: (t: T) => boolean): Arbitrary<T>
  map<U>(mapper: (t: T) => U): Arbitrary<U>
}

interface Left<E> {
  type: 'Left'
  right: E
}
interface Right<A> {
  type: 'Right'
  right: A
}
type Either<E, A> = Left<E> | Right<A>

declare function isRight<E, A>(e: Either<E, A>): e is Right<A>

declare const arb: Arbitrary<Either<string, number>>

arb.filter(isRight).map(e => /* e is still Either<string, number> */ e)
```

Proposed change:

```ts
export interface Arbitrary<T> {
  filter<U extends T>(refinement: (t: T) => t is U): Arbitrary<U>
  filter(predicate: (t: T) => boolean): Arbitrary<T>
  map<U>(mapper: (t: T) => U): Arbitrary<U>
}

arb.filter(isRight).map(e => /* e is Right<number> now */ e)
```

**Comment by dubzzz** [comment]
I've never thought about this one but it's clearly a very good idea to support type guards while filtering.

Let's go for it 🤩

As you already did most of the job, feel free to open a PR with the change. Otherwise I can do it a bit later

**Comment by dubzzz** [comment]
@gcanti  Thanks a lot for the suggestion, the feature has been merged in master. I'll work on your second suggestions in the coming days.

**Comment by gcanti** [comment]
@dubzzz awesome, thank you

p.s.
Sorry, I forked fast-check sometimes ago but I haven't found the time to submit a PR
