### ISSUE TITLE
add `files` to package.json

### ISSUE THREAD

**Issue by gcanti** [dubzzz/fast-check#547]
## 💡 Idea

After installing `fast-check@latest` (v1.22.1) I can see in `node_modules` lots of unnecessary files

<img width="234" alt="fast-check-node-modules" src="https://user-images.githubusercontent.com/878912/73725781-682bf380-472e-11ea-8059-368c56df31a0.png">

I suggest to add the [`files`](https://docs.npmjs.com/files/package.json#files) entry to `package.json` (which whitelists rather than blacklists like `.npmignore`)

**Comment by dubzzz** [comment]
Thanks a lot for the suggestion

The fix — #550 — has been published with [version 1.22.2 of fast-check](https://unpkg.com/browse/fast-check@1.22.2/)

Please free to re-open if you were thinking of something else with this issue ;)

**Comment by gcanti** [comment]
Just installed, I can confirm that there's no more unnecessary files, thank you for the quick response.
