### ISSUE TITLE
fc.stringMatching(/[a-z0-9]/) eventually generates string that don't match the regex?

### ISSUE THREAD

**Issue by dflock** [dubzzz/fast-check#5492]
## 🐛 Bug Report

I need an arbitrary string, which is alphanumeric, without punctuation or special characters. Otherwise I'll sometimes get strings that look like `., 0` or `0..` and the test will fail, due to the punctuation manipulation in the function under test.

I would expect the following two lines to produce the same kind of strings:

```
fc.stringMatching(/[a-z0-9]/)
fc.string({ unit: fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz0123456789') })
```

but they don't seem to? If I use `fc.stringMatching()`, I eventually get strings that don't match that regex - eg: `..\\{6E0_eV9/i<)y($@`, `..aV9/i<)y($@` or `..a`. If I use `fc.string()` with the custom unit, I only ever get purely alphanumeric strings.

## To Reproduce

I didn't see this every time - it seem like it mostly works, but eventually starts producing non-matching strings. To get this to happen consistently, I had to do a lot of runs:

`fc.configureGlobal({ numRuns: 10000, verbose: true })`

## Expected behavior

I would expect `fc.stringMatching(/[a-z0-9]/)` to only ever produce strings matching the regex.

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| fast-check           | 3.23.1 |
| node                 | v22.11.0 |
| TypeScript\*         | 5.6.2 |

\*Only for TypeScript's users

**Comment by gruhn** [comment]
I think the regex does match those strings, because the regex matches any sub-string and these strings contain alphanumeric characters. To *only* generate alphanumeric characters you something like:
```
fc.stringMatching(/^[a-z0-9]*$/)
```

**Comment by dubzzz** [comment]
@gruhn was faster than me. As said you probably meant: `fc.stringMatching(/^[a-z0-9]*$/)`.

**Comment by dflock** [comment]
Thankyou! Yep, `/^[a-z0-9]*$/` works, sorry!!
