### ISSUE TITLE
Getting typescript errors after importing fast-check.

### ISSUE THREAD

**Issue by ashutoshbhadoria** [dubzzz/fast-check#553]
## 💬 Question and Help
I am using typescript version 2.7.2
Is there a specific version of typescript I should use?

I just imported fast-check
`import * as fc from 'fast-check';`

I got this error while I tried running tests (without actually adding any test suites),

`Error: node_modules/fast-check/lib/types/check/arbitrary/DedupArbitrary.d.ts(2,47): error TS1005: ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/DedupArbitrary.d.ts(2,66): error TS1005: ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/DedupArbitrary.d.ts(2,86): error TS1005: ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/DedupArbitrary.d.ts(2,109): error TS1005: ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/DedupArbitrary.d.ts(2,135): error TS1005: ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/EmailArbitrary.d.ts(6,47): error TS1144: '{' or ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/EmailArbitrary.d.ts(6,91): error TS1005: '(' expected.
node_modules/fast-check/lib/types/check/arbitrary/HostArbitrary.d.ts(10,41): error TS1144: '{' or ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/HostArbitrary.d.ts(10,85): error TS1005: '(' expected.
node_modules/fast-check/lib/types/check/arbitrary/HostArbitrary.d.ts(12,47): error TS1144: '{' or ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/HostArbitrary.d.ts(12,91): error TS1005: '(' expected.
node_modules/fast-check/lib/types/check/arbitrary/RecordArbitrary.d.ts(14,65): error TS1005: ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/RecordArbitrary.d.ts(14,134): error TS1005: '(' expected.
node_modules/fast-check/lib/types/check/arbitrary/RecordArbitrary.d.ts(14,148): error TS1005: '(' expected.
node_modules/fast-check/lib/types/check/arbitrary/WebArbitrary.d.ts(20,84): error TS1144: '{' or ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/WebArbitrary.d.ts(20,128): error TS1005: '(' expected.
node_modules/fast-check/lib/types/check/arbitrary/WebArbitrary.d.ts(28,45): error TS1144: '{' or ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/WebArbitrary.d.ts(28,89): error TS1005: '(' expected.
node_modules/fast-check/lib/types/check/arbitrary/WebArbitrary.d.ts(36,53): error TS1144: '{' or ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/WebArbitrary.d.ts(36,97): error TS1005: '(' expected.
node_modules/fast-check/lib/types/check/arbitrary/WebArbitrary.d.ts(44,47): error TS1144: '{' or ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/WebArbitrary.d.ts(44,91): error TS1005: '(' expected.
node_modules/fast-check/lib/types/check/arbitrary/WebArbitrary.d.ts(69,11): error TS1144: '{' or ';' expected.
node_modules/fast-check/lib/types/check/arbitrary/WebArbitrary.d.ts(69,55): error TS1005: '(' expected.
node_modules/fast-check/lib/types/check/model/command/ICommand.d.ts(9,43): error TS1005: ';' expected.
node_modules/fast-check/lib/types/check/model/command/ICommand.d.ts(9,59): error TS1005: ';' expected.
node_modules/fast-check/lib/types/check/model/commands/CommandWrapper.d.ts(7,43): error TS1144: '{' or ';' expected. node_modules/fast-check/lib/types/check/model/commands/CommandWrapper.d.ts(7,59): error TS1005: ';' expected.
node_modules/fast-check/lib/types/check/property/IRawProperty.d.ts(29,26): error TS1005: ')' expected.
node_modules/fast-check/lib/types/check/property/IRawProperty.d.ts(29,41): error TS1005: ';' expected.
node_modules/fast-check/lib/types/check/property/IRawProperty.d.ts(29,69): error TS1005: ',' expected.
node_modules/fast-check/lib/types/check/property/IRawProperty.d.ts(29,86): error TS1109: Expression expected.
node_modules/fast-check/lib/types/check/property/IRawProperty.d.ts(29,93): error TS1005: ';' expected.
node_modules/fast-check/lib/types/check/property/IRawProperty.d.ts(29,95): error TS1109: Expression expected.
node_modules/fast-check/lib/types/check/property/IRawProperty.d.ts(29,106): error TS1005: ')' expected.
node_modules/fast-check/lib/types/check/property/IRawProperty.d.ts(29,167): error TS1005: ';' expected.
node_modules/fast-check/lib/types/check/property/IRawProperty.d.ts(30,1): error TS1128: Declaration or statement expected.
`

**Comment by dubzzz** [comment]
You should ideally use TypeScript 3.2 or higher.

Meanwhile, if I'm not wrong TypeScript 3.1 should also be fine with fast-check 1.x (support for 3.1 will be removed in the next major of fast-check but for the moment, this next major is not really planned).

**Comment by dubzzz** [comment]
@ashutoshbhadoria Did bumping towards more recent versions of TypeScript solved the issue?

**Comment by ashutoshbhadoria** [comment]
@dubzzz  Thanks for the follow up, my issues were resolved after upgrading the typescript version.
