### ISSUE TITLE
Add arbitrary.reject(predicate)

### ISSUE THREAD

**Issue by sluukkonen** [dubzzz/fast-check#560]
## 🚀 Feature Request

Add `arbitrary.reject(predicate)` as a dual for `arbitrary.filter(predicate)`.

## Motivation

Often times when generating data, I find writing code like `arbitrary.filter(v => !predicate(v))` or `arbitrary.filter(_.negate(predicate))`. This would be a bit cleaner if there existed a method which did the opposite of `filter`, e.g. accepted all the values that did not match the predicate.

## Example

```diff
-const notNull = fc.anything().filter(_.negate(_.isNull))
+const notNull = fc.anything().reject(_.isNull) 
```

**Comment by dubzzz** [comment]
First of all, thanks a lot for opening such feature requests. It's one of the most important way to get ideas from the users of OOS projects.

While I perfectly get the reason why one might want to have a shorthand to filter on a negated predicate I'd say that for the moment, this kind of shorthand is not suitable in fast-check. Here are some of the reasons why, as a maintainer, I would not be willing to add such:

- It adds another method to document, test, and maintain. Even if must of the code might be the same it is still another method where people may ask stuff. I prefer to limit as much as possible the number of methods defined on `Arbitrary.prototype`. For the moment, we have `filter`, `map` and `chain`.

- It means one single way to filter: `.filter()`. One single way to map elements: `.map()`. One single way to take the result of a random generation to seed another generator: `.chain()`.

- It mimics the API of JavaScript `Array`s. Only a `filter` no `negate`.

- It cannot be properly typed in TypeScript contrary to `filter`. `fc.boolean().filter((b): b is true => b) // Arbitrary<true>`.
