### ISSUE TITLE
Will shrinker work for composed generators

### ISSUE THREAD

**Issue by magnusart** [dubzzz/fast-check#574]
## 💬 Question and Help

I'm trying to wrap my head around what needs to be upheld for shrinkers. I want to duplicate some elements in an array.

Given the code below ...
1. will `numDuplicates` be shrinkable? 
1. If not, does that mean that the shrinked report will always contain the duplicates?
1. if so, what would be a better way to implement this? 

```typescript
import fc, { Arbitrary } from "fast-check"
import * as AR from "fp-ts/lib/Array"
import { pipe } from "fp-ts/lib/pipeable"

export const duplicateElements =
  (maxDuplicates: number, mrng: fc.Random) =>
    <T>(arb: Arbitrary<T[]>): Arbitrary<T[]> => {
      const numDuplicates = () => fc.integer(1, maxDuplicates).generate(mrng).value
      return arb.map(transactions =>
        pipe(
          transactions,
          AR.chain(e => (new Array<T>(numDuplicates())).fill(e))
        )
      )
    }
```

**Comment by dubzzz** [comment]
Hi,

1. will `numDuplicates` be shrinkable? 

Unfortunately not, but hopefully there is a simple pattern to do that.

Worst than that, the arbitrary produced by `duplicateElements(.., ..)` cannot be replayed.
Indeed you can check that using the following code snippet:
```js
// arb has been built using duplicateElements(.., ..)(..)
console.log(fc.sample(arb, {seed: 0}))
console.log(fc.sample(arb, {seed: 0}))
// The two calls should produce the very same items
```

2. If not, does that mean that the shrinked report will always contain the duplicates?

The shrinker used by the code when shrinking will be the one of the passed `arb`.
Each time this arbitrary will be shrunk it will produce a new set of transactions that will be passed to pipe and trigger a call to `numDuplicates()` (unfortunately not shrunk and not related to the original value).

3. if so, what would be a better way to implement this? 

My suggestion would be the following, use `chain` or `map` to preserve some shrinking capabilities (`chain` removes part of it but you'll still be able to shrink - whenever possible you should prefer `map`+`fc.tuple` over `chain`). With `chain`:
```ts
const duplicatesElement = <T>(maxDuplicates: number, arb: Arbitrary<T[]>): Arbitrary<T[]> => {
  return arb.chain(transactions =>
    fc.integer(1, maxDuplicates).map(n => pipe(
      transactions,
      AR.chain(e => (new Array<T>(n)).fill(e))
    ))
  );
}
```

Or a better option - _as `chain` might reduce shrinking capabilities_:
```ts
const duplicatesElement = <T>(maxDuplicates: number, arb: Arbitrary<T[]>): Arbitrary<T[]> => {
  return fc.tuple(arb, fc.integer(1, maxDuplicates)).map(([transactions, n]) =>
    pipe(
      transactions,
      AR.chain(e => (new Array<T>(n)).fill(e))
    )
  );
}
```

**Comment by magnusart** [comment]
Nice! Hadn't noticed that there was an `fc.tuple`. That makes my life much easier. Thanks!
