### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by brainkim** [dubzzz/fast-check#589]
## Question and Help

This is by far the best property-based testing library out there but every time I try to look for it, I haven’t been able to find it until I manually look through my stars or open an old project and find the name. I end going to `testcheck-js`/`jsverify` and wondering where the other library that did this stuff go. This is about the third time I’ve run into this problem. I even tried searching for `JS testing library Monkey T` this time. The keyword I used this time was `generative testing`. Maybe it could be put somewhere in the description or the README, because it is a common alternative description of “property-based testing” that I always seem to fall back on when I forget. Alternatively, maybe a more memorable name could help (“jasmine,” “jest,” “mocha,” “ava” all spring to mind as names for testing libraries which I don’t forget).

Mostly opening this issue so I don’t forget the name of this library a fourth time. `fast-check`, `fast-check`, `fast-check`, `fast-check`, `fast-check`.

**Comment by dubzzz** [comment]
Hello @brainkim,

Thanks a lot for the feeback. I'll will have a look to what I can do to have a better SEO for fast-check.
Using specific keywords like "generative testing"can indeed be a first solution. For the moment I only use it as a GitHub topic and it seems that GitHub topics are not exposed as keywords for search engines.

I think that most of the time jsverify comes first in the search results as it is by far the Property Based Testing library for JavaScript with the higher number of external references including articles (the project has been there for a while).
