### ISSUE TITLE
Improve awesomeness of the project description 

### ISSUE THREAD

**Issue by fabienbk** [dubzzz/fast-check#597]
Description should include the words "lightweight" and "blazing fast" as it is industry standard for real-world frontend libraries !

Also host it on its own github account, i.e. fast-check/fast-check !

Also where are the promotional stickers ??!

C'mon man !

**Comment by dubzzz** [comment]
Promotional stickers here ⬇️ 

![600x200](https://user-images.githubusercontent.com/5300235/86511943-e08e0200-bdfd-11ea-8130-fe4f118cb754.jpg)

I'll give you one next time we see each others 👍
