### ISSUE TITLE
FP in Model testing

### ISSUE THREAD

**Issue by codingedgar** [dubzzz/fast-check#598]
First of all, I love this library, thank you very much 💛

## 💡 Idea

Could it be possible to make the Model testing interface more "Functional" (meaning, lose the need of classes)

### TL;DR:

In summary:
- It seems pointless to use Classes.
- It just seems odd to rely on mutating an argument (the model), that is constantly injected anyways.
- I'm not sure what could be a better replacement for Classes in Model Testing.

### Long version:

fast-check has been an amazing functional library that elegantly abstracts all the "states" related to property testing.

So far fast-check is pretty immutable and adapted to common monadic interfaces (`chain`, `map`, etc), but the model testing part is pushing the mutable side (of the model) to userland relying on an OOP interface, therefore forcing the `run` command to lose "purity".

I see it is convenient and easy to wrap our hands around the "if Class = Command then `this` & `m.x = y` are valid", but it seems that the class part is unnecessary.

If the `constructor`, `model`, and `real` arguments are passed each time, what is the instance even used for? and the classes are constantly instantiated, it seems like a plain record of pure functions could do the job.

#### Counters to this idea:
- Change.
- Having just one `update` function might feel limiting because currently, we have the freedom of updating the model anywhere on the `run` function, the pipeline might need something before and after of `run`.

## Example

```ts
export const AddTrackCommand =
  (readonly position: number, readonly trackName: string) => ({

    check: (m: MusicPlayerModel) => {
      return !m.tracksAlreadySeen[trackName];
    },

    update: (m: MusicPlayerModel, p: MusicPlayer) => {
      return {
        ...m,
        numTracks: m.numTracks++,
        tracksAlreadySeen: {
          ...m.tracksAlreadySeen,
          [trackName]: true
        }
      }
    },

    run: (m: MusicPlayerModel, p: MusicPlayer) => {
      const trackBefore = p.currentTrackName();
      p.addTrack(trackName, position % (m.numTracks - 1)); // old model
      assert.equal(p.playing(), m.isPlaying);
      assert.equal(p.currentTrackName(), trackBefore);
    },

    toString: () => {
      return `AddTrack(${position}, "${trackName}")`;
    }
  })
```

Hope this idea doesn't sound too stupid, I feel like Model Testing is amazing, but somehow it feels a bit awkward to work with it, atm.

**Comment by dubzzz** [comment]
Thanks for the feedback on the library, pretty cool to see positive feedbacks on it ;)

Concerning the class-based approach of model based testing in fast-check, I think the main reason is that I took my inspiration from [RapidCheck](https://github.com/emil-e/rapidcheck), a C++ library to do Property Based Testing. By the way, I recommand [this article](https://labs.spotify.com/2015/06/25/rapid-check/) from the author of this library. You can see their model based testing approach code [here](https://github.com/emil-e/rapidcheck/blob/master/examples/database/main.cpp).

Internally, fast-check does not use any `Class` is `Command` to do anything. So I believe a more functional API like the one you suggest might be possible 🤔

Anyway, it will need a bit of work, specs around it... and if it really becomes the new way to go for model based in fast-check, I'll need to offer a migration path for existing users while preserving the two approaches for a certain amount of time (at least up to the next major).

**Comment by edgarjrg** [comment]
That article was amazing, thank you for sharing ✨ 

If there's anything I could help with, let me know.

**Comment by dubzzz** [comment]
While checking for the opened PR, I found back this one: #445

It basically offer some kind a more functional API for model based testing. For the moment, it takes an `initialModel`, generates a sequence of actions and produces `{ model /*model after actions*/, actions /*actions to apply to move from initialModel to model*/ }`.

I'd say that a more functional model based testing might maybe be inspired partly by this one 🤔 
But instead of the final model, we want the `updater(Model, Action) => Model` and the `initialModel`.
Nonetheless it can somehow be a good starting point...

---

📔 For the record, one the problems with that approach compared to the current one is that I don't have any clue (so far) on how I'd be able to tell the shrinker where I stopped in the actions before finding the issue.

In the current model based testing approach, the framework generates long arrays of commands such a `[ca, cb, cc, cd, ce...]`. But when running the commands, if for instance `cc` fails and `cb` was not executed (check failed), it will shrink `[ca, cc]` and not the whole array.

**Comment by codingedgar** [comment]
I think that maybe, if the `run` returns a model, it should be an array of fns instead of one fn, to be able to ensure a sequential series of steps, because breaking it down to commands just distance the chances to sequentially apply two actions that only make sense one after the other, just taking the idea from xstate `machine.on[action].actions`, because:

1. I have found myself updating the model more than once per command, and lately I’ve needed to keep in sync two properties. So the usual state “problems” are rising.
2. I also have been needing the model in the toString method, for example picking an item from an item array is calculated in `run`, and cannot re/calculate it in `toString`, nor set a variable in the `constructor`.

I think that PR is the same idea, a command could be : model -> actions -> new model, it arrives to the same conslusion.

**Comment by codingedgar** [comment]
This is my current test, testing editing in http://todomvc.com/examples/react/#/:

```ts
      await fc.assert(
        fc.asyncProperty(
          fc.commands(
            [
              validToDoArbitrary()
                .chain(text => fc.record({
                  text: fc.constant(text),
                  number: fc.nat().noShrink()
                }))
                .map(({ text, number }) => new EditCancelCommand(
                  {
                    text,
                    type: 'valid'
                  },
                  number
                )),
            ],
          ),
          async (commands) => {
```
Command:
```ts
export class EditCancelCommand implements fc.AsyncCommand<Model, Page, false> {

  model: Model | undefined

  constructor(readonly todo: Model['input'], readonly number: number) { }

  check(m: Readonly<Model>) {

    this.model = m;
    return m.toDos.length > 0;

  };

  async run(m: Model, page: Page) {
    this.model = m;

    await page
      .$$(CLASS_SELECTORS.TODO_ITEMS_LABEL)
      .then(async els => {

        const el = els[pickToDo(this.number, m)];

        await el.click({ clickCount: 2 });

        m.toDos[0].editing = true

        await Promise
          .all(
            m.toDos[0].text.split('')
              .map(() =>
                page.keyboard.press('Backspace')
              )
          );


        await checkModel(m)

        await el.type(this.todo.text);

        await page.keyboard.press('Escape');
        m.toDos[0].editing = false

      });

    await checkModel(m)
    
  };

  toString = () => `${EditCancelCommand.name} ${JSON.stringify(this.todo)} ${pickToDo(this.number, this.model!)}`;

}
```

Following the last comment, this is a rough proposal:

```ts
      await fc.assert(
        fc.asyncProperty(
          fc.commands(
            [
              validToDoArbitrary()
                .chain(text => fc.record({
                  text: fc.constant(text),
                  number: fc.nat().noShrink()
                }))
                .map(({ text, number }) => ({
                  cond: editCancelCommandCondition({text, type: 'valid'}, number),
                  actions: [
                    EditAction({text, type: 'valid'}, number),
                    DeleteTodoAction({text, type: 'valid'}, number),
                    checkModelAction({text, type: 'valid'}, number),
                    TypeToDoAction({text, type: 'valid'}, number),
                    checkModelAction({text, type: 'valid'}, number),
                  ],
                  toString: editCancelCommandToString({text, type: 'valid'}, number)
                  })
            ],
          ),
          async (commands) => {
```
Rest:
```ts
export function editCancelCommandCondition(todo: Model['input'], number: number) {
  return function (m: Model, page: Page) {
    return m.toDos.length > 0;
  }
}

export function editCancelCommandToString(todo: Model['input'], number: number) {
  return function (m: Model, page: Page) {
    return `Edit Cancel Command ${number} ${pickToDo(number, m)}`;
  }
}

export async function EditAction(todo: Model['input'], number: number) {
  return async function (m: Model, page: Page) {

    await page
      .$$(CLASS_SELECTORS.TODO_ITEMS_LABEL)
      .then(async els => {

        const el = els[pickToDo(number, m)];

        await el.click({ clickCount: 2 });

        m.toDos[0].editing = true

      });

  };
};

export async function DeleteTodoAction(todo: Model['input'], number: number) {
  return async function (m: Model, page: Page) {

    await Promise
      .all(
        m.toDos[pickToDo(number, m)].text.split('')
          .map(() =>
            page.keyboard.press('Backspace')
          )
      );

  };
};

export async function TypeToDoAction(todo: Model['input'], number: number) {
  return async function (m: Model, page: Page) {

    await page
      .$$(CLASS_SELECTORS.TODO_ITEMS_LABEL)
      .then(async els => {

        const el = els[pickToDo(number, m)];

        await el.type(todo.text);

        await page.keyboard.press('Escape');
        m.toDos[0].editing = false

      })

  };
};

export async function checkModelAction(todo: Model['input'], number: number) {
  return async function (m: Model, page: Page) {

    await checkModel(m)

  };
};
```

this might be a bit crappy, but I hope the order of things works as a good example.

**Comment by codingedgar** [comment]
I forgot to add the `return model` part 😹 , sorry.

**Comment by codingedgar** [comment]
@dubzzz I tried to change a bit the game, and just use xstate to modify the state of the Model, however, I ran into a pretty basic mistake, if I do this:

```ts
    m = modelMachine.transition(
      m,
      {
        type: 'ASSIGN_INPUT',
        payload: this.input
      }
    )
```


Then `m` is not modified, because I just modify the reference in my scope, therefore all tests start with the initial value and dont "stack" changes, I'm going to try a different approach with `interpret` to see if it works better, as I just `send` events to the interpreter and keep using the same instance.

**Comment by codingedgar** [comment]
I tried with 
```ts
// model: modelMachine.initialState,
                model: interpret(modelMachine).start(),
```

and `model: interpret(modelMachine).start()` works.

instead of 
```ts
    m = modelMachine.transition(
      m,
      {
        type: 'ASSIGN_INPUT',
        payload: this.input
      }
    )
```
i have: 

```ts
m.send(
      {
        type: 'ASSIGN_INPUT',
        payload: this.input
      }
    )
```

and all the references work fine.
