### ISSUE TITLE
Running with Mocha returning wrong result

### ISSUE THREAD

**Issue by afonsojramos** [dubzzz/fast-check#601]
## 🐛 Bug Report

I am running fast-check with mocha programmatically and after the tests fail, mocha sees tests as passing even though they are clearly failing.

Test: 
```
fc.assert(
  fc.asyncProperty(
    fc.array(
      fc.boolean().map((b) => (b ? 'E' : 'D')),
      1000
    ),
    async (ns) => testAsyncQueueBehavior(ns)
  ),
  { numRuns: 100 }
)
```

fast-check output:
```
UnhandledPromiseRejectionWarning: Error: Property failed after 3 tests
{ seed: 1520339943, path: "2:1:1:2:2:5:2:3:18:16:57:30:5:1:11", endOnFailure: true }
Counterexample: [["D","E","D"]]
Shrunk 14 time(s)
Got error: Property failed by returning false

Hint: ...
```

Mocha output: `1 passing (619ms)`

Maybe I'm doing something wrong, but not sure what it is. Is it because of the asyncProperty? Even so, shouldn't it fail on mocha either way?

## Expected behavior

Outputting 1 failed tests.

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check | 1.24.2 |
| mocha | 7.2.0 | 
| node |  12.16.3 |
| TypeScript | 3.9.3 |

**Comment by dubzzz** [comment]
Hello,

Just to be sure, when calling `fc.assert` on asynchronous properties you have to `await` it. Wrapping it in Mocha should look as follow:
```diff
+++ it(async () => {
+++   await fc.assert(
---   fc.assert(
        fc.asyncProperty(
          fc.array(
            fc.boolean().map((b) => (b ? 'E' : 'D')),
            1000
          ),
          async (ns) => testAsyncQueueBehavior(ns)
        ),
        { numRuns: 100 }
      )
+++ })
```

It should work if awaited. Please let me know if you stiff have the failure after that suggestion.

**Comment by afonsojramos** [comment]
You are correct, thank you for your help! 😊
