### ISSUE TITLE
Parallel asyncProperty and/or shrinking

### ISSUE THREAD

**Issue by codingedgar** [dubzzz/fast-check#610]
## 💡 Idea

Be able to make a shrinking parallel.

## Motivation

When shrinking, sometimes it takes a big amount of time to shrink, especially with e2e/UI.

## Example

```ts
   await fc.assert(
        fc.asyncParallelProperty(
```

If used with, for example, Puppeteer it will open multiple tabs and test in each one separately. 

Of course, the tab management is userland.

Note: I'm not sure how this would work, I'm testing with jest, and they do handle parallelization but if file based, with fast-check (Model Based) all the test is just one spec, it would be nice to be able to speed it up a bit.

**Comment by dubzzz** [comment]
Thanks for the suggestion. Let's merge this issue with https://github.com/dubzzz/fast-check/issues/190 which seems to deal with the same topic.

Feel free to re-open if subjects are too far away.

---

Just in case it can help you may have a look to the following flag `interruptAfterTimeLimit` (and maybe `markInterruptAsFailure` or `skipAllAfterTimeLimit`). While it does not solve the issue they at least avoid the test to timeout during shrinking or execution.

`interruptAfterTimeLimit` has been mostly introduced to handle model based testing runs that were causing most runners (jest included) to timeout during long shrinking processes. The flag is ideal for a CI. In case of failure in the CI, you can still resume the shrinking process locally if needed (seed + path).

**Comment by codingedgar** [comment]
Oh that’s perfect, both the timeouts and the other issue, os exactly the same point 🎯
