### ISSUE TITLE
Is it possible to have an arbitrary seeded from an iterable?

### ISSUE THREAD

**Issue by nth-commit** [dubzzz/fast-check#638]
## 💬 Question and Help

I'm basically looking for this function:

`type FromArray<T> = (arb: Arbitrary<Array<T>>) => Arbitrary<T>`

Where the values generated from the output arbitrary, are the sequence from the input arbitrary array. When that sequence is exhausted, you would expect the next value of the input arbitrary to be generated and then streamed into the output.

**Comment by dubzzz** [comment]
From what I understand from your question : _you are looking for a way to generate an infinite stream of values starting with some manually defined values_.

If so, it can be achieved with something like:

```ts
const fromArbitrary = <T>(startingValues: T[] | ReadonlyArray<T>, arb: fc.Arbitrary<T>): IterableIterator<T> => {
  return fc.infiniteStream(fc.nat())
    .map(function*(s) {
        yield* startingValues;
        yield* s;
    });
}

// fromArbitrary([1,2,3], fc.nat()) will generate infinite sequence
// starting by 1, 2, 3 and followed by values generated by fc.nat()
```

**Comment by nth-commit** [comment]
Hey @dubzzz, thanks for the quick response.

> From what I understand from your question : _you are looking for a way to generate an infinite stream of values starting with some manually defined values._

Not quite. I want the the result arbitrary to emit each item in the array individual, and then move on to the next array.

For example;

```typescript
const arrayArb: fc.Arbitrary<number[]> = // _Given some seed, generates [1, 2, 3], [4, 5, 6], [7, 8, 9]_
const itemArb: fc.Arbitrary<number> = fromArbitraryArray(arrayArb); // _Generates 1, 2, 3, 4, 5, 6, 7, 8, 9_
```

**Comment by dubzzz** [comment]
> Not quite. I want the the result arbitrary to emit each item in the array individual, and then move on to the next array.

How would you use `arrayArb` or `itemArb` within `fc.assert` or `fc.property`? What would be your usage, I mean in terms of code, property...?

```js
fc.assert(fc.property(arrayArb, arr => {/* build values for itemArb here? how much? when? */}))
```

A code snippet just putting the need in code would help.

**Comment by nth-commit** [comment]
Hey, great question! Especially when I think more about the relationship between a random, a property and an arbitrary.

The thing I had in my head may not apply to other use-cases. But I was thinking that one generation of one property would contribute a number of runs to the property function (depending on the size of the array). Potentially the property would run once for each item in the array, and that number would need to be combined with the other arbitraries given to a property.

```typescript
const arrayArb: fc.Arbitrary<number[]> = fc.constant([1, 2, 3]);
const itemArb: fc.Arbitrary<number> = fromArbitraryArray(arrayArb);

fc.assert(fc.property(itemArb, item => {
  console.log(item);
}));

// Prints:
//   1
//   2
//   3
//   1
//   2
//   3
//   etc..
```

**Comment by dubzzz** [comment]
For the moment, there is no built-in arbitrary to do that in fast-check and I don't think that it is possible to build such arbitrary.

One of the most important things is that runs of property have to be independent. So running 1 then 2 then 3 or 2 then 3 then 1 should not change the way the property behaves. The function to test in a property is supposed stateless.

**Comment by dubzzz** [comment]
```
let previousN = -1;
fc.assert(
  fc.property(
    fc.nat(),
    n => {
      expect(n > previousN). toBe(true);
      previousN = n;
   }
 ) 
) 
```
Is an invalid property. The test is not stateless so nothing can be done properly. For instance, shrinker will be more or less lost and reports errors that will not be reproducible.

**Comment by nth-commit** [comment]
Ah right, OK. Thanks for your patience with me, and taking the time to explain your reasoning 😄 

Potentially the value injected into the property could be made dependent on the random factor, i.e. `fc.nat().map(x => array[x % array.length])`?

But anyway, the main purpose of this was to tackle the situation described in #424, so I'll close this one 👍

**Comment by dubzzz** [comment]
The following property would be perfectly legit and legal:

```js
const array = [1, 5, 8];

fc.assert(
  fc.property(
    fc.nat().map(x => array[x % array.length]),
    n => codeUnderTest(n),
  )
)
```

But indeed, `array` has to be a known value, not the output of an arbitrary (_it can be_ if you use `chain`).
