### ISSUE TITLE
Demonstration of Property Based Testing

### ISSUE THREAD

**Issue by afonsojramos** [dubzzz/fast-check#643]
## 💬 Question and Help

I need to make a demonstration of Property-Based Testing, showing simple cases where fast-check is able to find a failing test case where example-based test cases cannot. Do you have any example of such?

**Comment by dubzzz** [comment]
Hey, I believe you could have a look into the examples of bugs discovered using fast-check on famous libraries.

See https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/IssuesDiscovered.md

To be honest, any issue that can be discovered by fast-check can be found with a simple unit test. The question is more: can we find this unit test by our own? Or is property based able to find bugs we never thought about? I'd go for the second option.

You may also refer to the articles and videos referred in https://github.com/dubzzz/awesome-fast-check/

**Comment by afonsojramos** [comment]
Exactly what I am trying to prove 😁

That's why I'm trying to present cases where everything seems well covered with example-based unit tests to see if it is possible for a developer to find the bug either way, and then presenting the property based test to evaluate the difference.

**Comment by dubzzz** [comment]
Bugs discovered in the repo JavaScript Algorithms might be useful

**Comment by afonsojramos** [comment]
While creating some tests I ran into a question, is it possible to create strings with integers inside?

**Comment by afonsojramos** [comment]
Yeah, sorry, I'll close the issue! 😁

Thanks!
