### ISSUE TITLE
`record` could preserve more type information

### ISSUE THREAD

**Issue by amonks** [dubzzz/fast-check#71]
Currently, Record drops type information about the individual properties in recordModel.

For example, let's say Users have two properties:

```typescript
interface User {
  name: string;
  age: number;
}
```

If I'd like to use fast-check to generate this record, I must type it like this:

```typescript
fc.record<string | number>({
  name: fc.string(),
  age: fc.integer(),
});
```

The resultant object has the type `{ [k: string]: string | number }`, not the type `User`.

Record would be more powerful if it could be used like this:

```typescript
fc.record<User>({
  name: fc.string(),
  age: fc.integer(),
});
```

It could achieve that with a declaration using mapped types, like this:

```typescript
declare function record<T>(recordModel: {
  [K in keyof T]: Arbitrary<T[K]>;
}): Arbitrary<{
  [K in keyof T]: T[K];
}>;
```

Going even further, it could capture the result of calling with with_deleted_keys set to `true` as the mapped type `Partial<T>`, using the conditional type operator:

```typescript
export interface RecordConstraints { 
  with_deleted_keys?: boolean 
}
interface RecordConstraintsWithDeletedKeys {
  with_deleted_keys: true
}

declare function record<T>(
  recordModel: {
    [K in keyof T]: Arbitrary<T[K]>;
  },
  constraints?: RecordConstraints,
): Arbitrary<
  RecordConstraints extends RecordConstraintsWithDeletedKeys 
    ? { [K in keyof T]: T[K] } 
    : Partial<{[K in keyof T]: T[K]}>
>;
```

If you'd like, I can work on a PR for either or both of these changes.

**Comment by dubzzz** [comment]
Indeed I struggled to find a way to achieve that easily. It would be very nice to have it. 

As you want for the fix. Either you can do it and issue a pr or I can handle it on my side.

**Comment by dubzzz** [comment]
@amonks I have not yet taken the time to do the change on my side. Sorry for the delay. I will assist myself to the ticket as soon as I start working on it

**Comment by dubzzz** [comment]
@amonks 
Thanks a lot for the update. If you are curretly using fast-check, you should get a try to the last version 1.0.0. It provides smaller stack traces and come with a replay feature ;)

Typings for record will come in a next release. genericTuple caused me problems too ;)

**Comment by dubzzz** [comment]
@amonks The fix will be available in the nest release - it should be version 1.1.0

Thanks a lot for your help with your initial comment
