### ISSUE TITLE
`document.all` is falsy too

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#745]
## 🐛 Bug Report

`document.all` is falsy too
https://twitter.com/mathias/status/385677152261513216

Do we want to handle it in `fc.falsy()`? 🤔 

## To Reproduce

--

## Expected behavior

--

## Your environment

--

**Comment by dgerrells** [comment]
I did not know this which makes me think it should be. 😅

**Comment by dubzzz** [comment]
Well, finally I'll not add it. In usual test runners such as Jest we can have `document` but `document.all` is just `undefined` (not another falsy value).
