### ISSUE TITLE
Simplify creation of arbitraries, giving the ability to build one from an example

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#75]
Do more or less what has been done in https://github.com/dubzzz/fuzz-rest-api/blob/master/test/inferPayloadArbitrary.js
But in a better way ;)

**Comment by dubzzz** [comment]
The source might also be a type, a swagger file or any other stuff able to describe a data structure

**Comment by dubzzz** [comment]
See t.TypeOf of https://github.com/gcanti/io-ts/blob/master/README.md

**Comment by ashnur** [comment]
JSON-Schema :)

**Comment by dubzzz** [comment]
Just found something that might be a great idea to start with: https://github.com/DaveWM/swagger-testcheck

It takes swagger definition as input and produces the JavaScript code to generate the arbitraries.

I first wanted to see if it could be easily adapted for fast-check. Then I should see how it could be used without having the intermediate source code.

**Comment by dubzzz** [comment]
A quick generator of fast-check code based on swagger contracts: https://github.com/DaveWM/swagger-testcheck/issues/1
