### ISSUE TITLE
Lift Arbitrary<T>[] to Arbitrary<T[]>

### ISSUE THREAD

**Issue by cwstra** [dubzzz/fast-check#778]
## 🚀 Feature Request

Add alternate tuple (or overload) with different type to allow for more functionality.

## Motivation

When using Typescript, it can be difficult to chain an array of generators into a generator of arrays, due to the limits of the type system; this tends to throw errors such as `Expected 1-22 arguments, but got 0 or more`. 

As far as my humble eyes can tell, the cause of these errors is not underlying JS, but the limits of the generated tuple types. If this is correct, by aliasing the `tuple` Arbitrary's functionality into an arbitrary (say, `liftArbitraryList`), with type `<T>(arbs: Arbitrary<T>[]): Arbitrary<T[]>`, we'd get some functionality for free. Alternatively, maybe another overload of `tuple` would work?

## Example

Let's say you want to make a list of arbitrary `Thing`s with unique ids. If we have `fc.liftArbitraryList: <T>(arbs: Arbitrary<T>[]): Arbitrary<T[]>` as described above, and a `factory: (id: string) => Arbitrary<Thing>`, then we could generate our `Arbitrary<Thing[]>` with:
`fc.set(fc.uuid()).chain(ids => fc.liftArbitraryList(ids.map(factory)))`

**Comment by dubzzz** [comment]
Hello, 

Thanks for the suggestion.

I believe there is already an arbitrary for that need. You should check `genericTuple`. It should do what you are looking for. 

Regards, 
_sent from my mobile_

**Comment by cwstra** [comment]
Derp. Very correct. Missed it somehow.
