### ISSUE TITLE
Introduce a placeholder for min/max parameters

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/fast-check#89]
Building an array of length 3 or more is currently not ideal, solutions are the following:
- `fc.array(fc.nat()).filter(data => data.length >= 3)` - not optimized, will reject too many arrays
- `fc.array(fc.nat(), 3, 100)` - but why 100? Why do the user has to specify this value?
- `fc.tuple(fc.nat(), fc.nat(), fc.nat(), fc.array(fc.nat())).map(([a,b,c,data]) => [a,b,c,...data])` - really to complicated

The idea is to introduced a placeholder whenever possible to be able to do:
- `fc.array(fc.nat(), 3, fc._)` - min = 3, max = auto
- `fc.array(fc.nat(), fc._, 3)` - min = auto, max = 3
- `fc.array(fc.nat(), fc._, fc._)` - min = auto, max = auto

**Comment by dubzzz** [comment]
The feature is more or less ready. But I prefer to delay it for the v1.2.0.

**Comment by SupernaviX** [comment]
Would an options hash be an acceptable API? I think `fc.array(fc.nat(), { min: 3 })` is a pretty idiomatic way to solve this.

**Comment by dubzzz** [comment]
@SupernaviX 
Indeed I think I will move to this kind of signature - with `min` and `max` as attributes of an object.
The placeholder way - `fc.array(fc.nat(), 3, fc._)` - seems less idiomatic and does not adapt to all situations. The only benefit I see is that it seems lighter for cases where you need to specify both min and max.

I think I will update the branch I started to implement this feature to the `{min,max}` way.

In any cases, I need some kind of: *I want a min not a max, or the contrary*. I prefer not forcing the user into specifying a value for min or max - the framework should do the magical part itself ;)

**Comment by SupernaviX** [comment]
Definitely agreed. With this kind of library in particular, it's useful for consumers to only describe constraints they need, and fall back to sensible defaults everywhere else.

**Comment by dubzzz** [comment]
@SupernaviX Even if the `{min, max}` notation is more idiomatic ES6+, I think I will stay to the placeholder approach for the moment (at least for 1.x versions).

Indeed it better fits with the current API. The `{min, max}` would have introduced another notation. 

Moreover, knowing that I will not remove any of the existing signatures for 1.x (want to respect semver as much as possible), I am not sure users wanting only a max will be using `fc.array(arb, {max: maxSize})` as they can simply call `fc.array(arb, maxSize)` instead.

Maybe one day named parameters will be part of JavaScript or TypeScript as they are in Python and C#. 

The last point is that the current notation would be closer from jsverify one.

**Comment by dubzzz** [comment]
@SupernaviX 

> Would an options hash be an acceptable API? I think `fc.array(fc.nat(), { min: 3 })` is a pretty idiomatic way to solve this.

It took me a while, but I think this is the way to go ^^
It is clearly more idiomatic.

I need to revive my old review

**Comment by ethanresnick** [comment]
I'm not sure what the status of this issue is, but maybe a reasonably intuitive and backwards-compatible way would be to take `Infinity` and have it behave like the proposed placeholder would have? So `fc.array(fc.nat(), 3, Infinity)` generates an array of 3+ items.

**Comment by dubzzz** [comment]
@ethanresnick For the moment the approach I wanted to experiment is the one suggested by @SupernaviX. I did try the other one a while ago but it didn't fit with the framework. The object based syntax has been spread and used in all the recent arbitraries and works perfectly: typings are easier, no need for 'overloaded' functions...

**Comment by dubzzz** [comment]
Solved with #992
