### ISSUE TITLE
Model Based Testing - Restore State on Shrinking

### ISSUE THREAD

**Issue by ignaciobll** [dubzzz/fast-check#898]
## 💬 Question and Help

First time with a question here :D I would like to thank you for the library, it is a great tool that have help a lot. I have search though the docs and other issues, but I couldn't find exactly what I'm looking for. So here is my question.

### Is there a way to restore state before every shrink?
Or said in a different way,
**Is there a way to execute a command/function before each shrink?**

When doing Model Based Testing for me it's fundamental to restore the state of the system after every test. This is mandatory when there is an state mutation and shared resources. There is an easy way to do it:

```typescript
fc.asyncProperty(
  fc.commands(commands),
  async (cmds) => {
    await restoreState(); // For example, cleaning a db
    const s = () => ({ model: { ... }, real: new DbClient() });
    fc.asyncModelRun(s, cmds);
  }
);
```
But when an error is found, I didn't found a way to restore the state between every shrink. I have to enable `endOnFailure`, which produces non minimal counterexamples.

I think that this library is powerful enough to find very useful counterexamples in these cases. Is it possible to restore the state before each shrink?

Please, if you want me to elaborate more on the question or provide more examples, I'll include them.

It there is no solution or alternative, I'll happy trying to implement this if considered.

### Others workaraunds that I tried

I tried to modify the command generator to always include an sepecific first command in the sequence, but couldn't apply `.map(...)` to the generator in order to append that command.

**Comment by dubzzz** [comment]
You may have a look into `beforeEach` method available on `asyncProperty`, it should do what you are looking for.

**Comment by ignaciobll** [comment]
Thank you very much! That was very helpful and was exactly what I was looking for. I don't know how couldn't I see that before, but thank you for your response.

**Comment by dubzzz** [comment]
> I don't know how couldn't I see that before

Please let me know if you have any idea. Would be pretty useful for futur users that have the same need. I might need to add a section about that feature into the [Tips documentation](https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/Tips.md) 🤔

**Comment by vvp** [comment]
Fwiw, the initial state provider is called on each shrinking run and it can be async too, so we used something like this to restore a snapshot state: 
```typescript
asyncProperty(commands(...), async (cmds) => {
  const initialState = async () => {
    let stateSnapshot = await restoreState(...)
    console.log("Restored state snapshot")
    return {
      model: await initializeModel(stateSnapshot),
      real: stateSnapshot,
    }
  }
  await asyncModelRun(initialState, cmds)
})
```
