### ISSUE TITLE
Describe shrinking in the readme?

### ISSUE THREAD

**Issue by bitjson** [dubzzz/fast-check#97]
Thanks for the very thorough readme!

One thing I’m not quite clear on is the shrinking process, and how it works in this library. I understand the concept from prior-knowledge about property based testing, but it’s not clear to me how it’s implemented or what the purpose of `noShrink()` is. Could you add a bit more info about it?

**Comment by dubzzz** [comment]
Hello @bitjson ,

I will definitely add a section on it.

The `noShrink` is just a way to idle the shrink on a specific Arbitrary - _It basically builds a new Arbitrary based on the current one but without the shrink ability_.

I think that it can be useful in somecases.

**Comment by dubzzz** [comment]
Concerning the implementation of the shrink, more or less all the arbitraries derive their shrink from the integer one.

**The integer shrinking process can be summarized as follow:**

**Case integer between -M and N:**

Shrink towards 0

If the failing values is A > 0, the algorithm will try to minimize the case with a dichotomy towards 0.
The first shrinking level will be: `0`, `A/2`, `3*A/4`, `7*A/8`...
Let's say `3*A/4` fails, then the next generation will be: `(3*A/4)/2`, `3*(3*A/4)/4`, `7*(3*A/4)/8`...

**Case integer between M and N:**

Shrink towards M

**Comment by dubzzz** [comment]
Just started to document the shrinking in the Readme (not yet in master). I might add more details on it to have it clearer

**Comment by dubzzz** [comment]
Hello @bitjson,

I just created a PR related to this issue.
Can you please tell me if I need to add stuff into it?

PR: https://github.com/dubzzz/fast-check/pull/110

Thanks in advance,
Nicolas

**Comment by dubzzz** [comment]
I updated the documentation to give more details concerning the shrinking process.
See: https://github.com/dubzzz/fast-check/blob/master/documentation/AdvancedArbitraries.md#shrinking

Does it answer your question?
Do I need to add a section about the way the framework ingest those values?

**Comment by bitjson** [comment]
Hey, sorry to not respond before – that certainly helps to answer my question! 

It might be helpful to add a bit more detail though (especially for users who have never seen property-based testing before).

**Comment by dubzzz** [comment]
I opened the issue #119 to deal with the basic documentation of: What is property based? How to run fast-check?

It should basically result in a tutorial starting from scratch and resulting in a property based test using fast-check in TypeScript.

---

I also need to detail a bit more the way the shrinking works in a more advanced documentation. Basically I should give more details on the tree of shrunks values. A graph of shrunk values of an integer might give a good idea of what produces a shrinker.

**Comment by dubzzz** [comment]
@bitjson I took me a while... more than a year, close to 2 years but it's finally here.

Here is a full documentation explaining how fast-check works under-the-hood from generators to shrinkers... See https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/HowItWorks.md

Please let me know what you think of this document. How you would enhance it or if some things can be made cleaner and easier to understand

**Comment by dubzzz** [comment]
It should be fixed now. Please feel to re-open :)

**Comment by bitjson** [comment]
Hey @dubzzz, fantastic work on that guide! That's extremely helpful. I didn't see any confusing parts in my first read-through. Thanks for the heads up! (I'll probably be linking directly to your guide when I use the term "property based testing" in other articles now too. 😄)

Sorry I've been quiet in this repo for a couple years now. If you're curious, I'm still loving [fast-check in Libauth](https://github.com/bitauth/libauth/search?q=fast-check). I've added fast-check tests for pretty much everything, and I've probably found hundreds of tiny issues over the years. So thanks for the fantastic project!
